import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/addons/utils/SkeletonUtils.js';
import { EGOSHOOT_ASSETS } from './egoshoot-assets.js?v=20260819-egoshoot-assets-v510-19-weapons';

(() => {
  'use strict';

  const VERSION = '2026-08-19-egoshoot-kl-v510-fps-tactical-rebuild';
  const ASSET = 'assets/egoshoot-kl/';
  const FP_ARMS_ASSET = './assets/shared/arme-first-person.glb';
  const STORAGE_KEY = 'jk-games-egoshoot-kl-v248';
  const MAX_REMOTE = 64;
  const WALK_SPEED = 4.8;
  const RUN_SPEED = 8.4;
  const BOT_COUNT = 8;

  const WEAPONS = [
    {id:'knife',name:'Messer Schwarz/Grau',file:'knife.glb',slot:'melee',type:'melee',starter:true,minKills:0,cost:0,damage:50,rate:.78,stability:100,range:2.25,durabilityLoss:.45,desc:'Nahkampf · ignoriert Shield · 2 Treffer auf 100 Leben.'},
    {id:'baseball',name:'Baseballschläger',file:'baseball-bat.glb',slot:'melee',type:'melee',minKills:25,cost:8,damage:50,rate:.92,stability:100,range:2.55,durabilityLoss:.5,desc:'Nahkampf · Rückenhalterung · ignoriert Shield.'},
    {id:'katana',name:'Katana-Schwert',file:'katana.glb',slot:'melee',type:'melee',minKills:60,cost:18,damage:50,rate:.62,stability:100,range:2.8,durabilityLoss:.35,desc:'Schneller Nahkampf · Rückenhalterung · ignoriert Shield.'},

    {id:'glock',name:'Glock',file:'glock.glb',slot:'sidearm',type:'pistol',starter:true,minKills:0,cost:0,damage:30,rate:.28,stability:88,mag:17,reload:1.45,range:105,durabilityLoss:.10,desc:'Starter-Pistole · präzise und zuverlässig.'},
    {id:'sand-pistol',name:'Pistole Grau/Sand',file:'sand-pistol.glb',slot:'sidearm',type:'pistol',minKills:15,cost:5,damage:34,rate:.31,stability:86,mag:14,reload:1.5,range:110,durabilityLoss:.11,desc:'Etwas stärker als die Glock.'},
    {id:'revolver',name:'Revolver',file:'revolver.glb',slot:'sidearm',type:'pistol',minKills:35,cost:10,damage:48,rate:.56,stability:82,mag:6,reload:1.8,range:120,durabilityLoss:.14,desc:'Langsam, aber hoher Einzelschaden.'},
    {id:'desert-eagle',name:'Desert Eagle',file:'desert-eagle.glb',slot:'sidearm',type:'pistol',minKills:60,cost:18,damage:56,rate:.5,stability:79,mag:7,reload:1.75,range:125,durabilityLoss:.15,desc:'Sehr schwere Pistole mit hoher Durchschlagskraft.'},
    {id:'mini-uzi',name:'Mini Uzi',file:'mini-uzi.glb',slot:'sidearm',type:'smg',minKills:100,cost:28,damage:17,rate:.085,stability:66,mag:28,reload:1.7,range:82,durabilityLoss:.075,desc:'Sehr schnell · niedriger Schaden pro Treffer.'},
    {id:'uzi',name:'Uzi',file:'uzi.glb',slot:'sidearm',type:'smg',minKills:130,cost:36,damage:19,rate:.09,stability:70,mag:32,reload:1.75,range:88,durabilityLoss:.075,desc:'Schnelle Maschinenpistole mit größerem Magazin.'},
    {id:'ump9',name:'UMP 9',file:'ump9.glb',slot:'sidearm',type:'smg',minKills:170,cost:48,damage:22,rate:.105,stability:76,mag:30,reload:1.8,range:96,durabilityLoss:.08,desc:'Stabilste Maschinenpistole.'},

    {id:'tommy',name:'Tommy Gun',file:'tommy-gun.glb',slot:'long',type:'rifle',minKills:210,cost:58,damage:27,rate:.115,stability:70,mag:40,reload:2.15,range:130,durabilityLoss:.08,desc:'Frühe Langwaffe mit großem Magazin.'},
    {id:'m4',name:'M4',file:'m4.glb',slot:'long',type:'rifle',minKills:260,cost:72,damage:32,rate:.105,stability:82,mag:30,reload:2.05,range:155,durabilityLoss:.075,desc:'Ausgewogenes Sturmgewehr.'},
    {id:'ak12',name:'AK-12',file:'ak12.glb',slot:'long',type:'rifle',minKills:320,cost:88,damage:35,rate:.11,stability:78,mag:30,reload:2.15,range:158,durabilityLoss:.08,desc:'Mehr Schaden, etwas mehr Rückstoß.'},
    {id:'an94',name:'AN-94',file:'an94.glb',slot:'long',type:'rifle',minKills:380,cost:105,damage:36,rate:.1,stability:81,mag:30,reload:2.15,range:165,durabilityLoss:.08,desc:'Schnelles, kontrollierbares Sturmgewehr.'},
    {id:'scar',name:'SCAR',file:'scar.glb',slot:'long',type:'rifle',minKills:450,cost:125,damage:39,rate:.12,stability:84,mag:30,reload:2.25,range:175,durabilityLoss:.085,desc:'Stark und sehr stabil.'},
    {id:'suppressed',name:'Sturmgewehr mit Schalldämpfer',file:'suppressed-rifle.glb',slot:'long',type:'rifle',minKills:520,cost:145,damage:37,rate:.1,stability:90,mag:30,reload:2.1,range:178,durabilityLoss:.075,desc:'Sehr präzise · reduzierte Mündungswirkung.'},
    {id:'ak47',name:'AK-47 Black Brown',file:'ak47-black-brown.glb',slot:'long',type:'rifle',minKills:600,cost:165,damage:43,rate:.125,stability:72,mag:30,reload:2.35,range:180,durabilityLoss:.09,desc:'Sehr hoher Sturmgewehr-Schaden.'},
    {id:'shotgun',name:'Shotgun',file:'shotgun.glb',slot:'long',type:'shotgun',minKills:700,cost:195,damage:13,rate:.82,stability:61,mag:8,reload:2.55,range:48,pellets:7,durabilityLoss:.16,desc:'7 Schrotkugeln · extrem stark auf kurze Distanz.'},
    {id:'barrett',name:'Sniper Barrett',file:'barrett.glb',slot:'long',type:'sniper',minKills:900,cost:250,damage:92,rate:1.25,stability:96,mag:5,reload:2.9,range:300,durabilityLoss:.18,desc:'Späte Sniper · Kopftreffer sind meist tödlich.'},
  ];
  const WEAPON_MAP = Object.fromEntries(WEAPONS.map(w => [w.id,w]));
  const SLOT_ORDER = ['melee','sidearm','long'];
  const UPGRADE_COSTS = [0,20,35,55,80,120,170,230,300,390];
  const SPAWNS = [
    new THREE.Vector3(-48,0,-48), new THREE.Vector3(48,0,-48),
    new THREE.Vector3(-48,0,48), new THREE.Vector3(48,0,48),
    new THREE.Vector3(0,0,-60), new THREE.Vector3(0,0,60)
  ];

  const loader = new GLTFLoader();
  const glbCache = new Map();
  const assetObjectUrls = new Map();
  const characterCache = new Map();
  const UI = { overlay:null, body:null, sourcePhone:'', session:null, keys:Object.create(null), mouse:{down:false,ads:false}, touch:{forward:false,back:false,left:false,right:false,fire:false,run:false}, modal:null, toastTimer:0 };
  let stateCache = null;
  let persistTimer = 0;
  let fpArmsTemplatePromise = null;

  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
  const lerpAngle=(a,b,t)=>{let d=(b-a+Math.PI)%(Math.PI*2)-Math.PI;if(d<-Math.PI)d+=Math.PI*2;return a+d*clamp(t,0,1);};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString('de-DE');
  const isTouch=()=>matchMedia('(pointer:coarse)').matches || innerWidth<760;
  const rootState=()=>window.JKGamesGetActiveState?.()||null;
  function roleKey(){return String(window.LifeBuilderSettingsMenu?.getRole?.()?.role||window.LifeBuilderSettingsMenu?.getRole?.()?.roleKey||'').toLowerCase();}
  function isStaff(){const r=roleKey();return r==='owner'||r==='admin'||!!window.LifeBuilderSettingsMenu?.isOwner?.();}

  function defaultState(){
    const weaponState={}; for(const w of WEAPONS) if(w.starter) weaponState[w.id]={owned:true,level:1,durability:100};
    return {version:2,gender:'',totalKills:0,killTokens:0,deaths:0,headshots:0,weaponState,equipped:{melee:'knife',sidearm:'glock',long:''},inventory:{heal:0,speed:0,shield100:0,shield150:0,shield200:0},settings:{lastMap:'dustline',lastGameMode:'deathmatch'},stats:{onlineKills:0,botKills:0,bestStreak:0,gunGameWins:0},lastMode:'lobby'};
  }
  function normalizeState(raw){
    const b=defaultState(),s=raw&&typeof raw==='object'?raw:{};
    b.gender=['man','woman'].includes(s.gender)?s.gender:'';
    b.totalKills=Math.max(0,Math.floor(Number(s.totalKills)||0));
    b.killTokens=Math.max(0,Math.floor(Number(s.killTokens)||0));
    b.deaths=Math.max(0,Math.floor(Number(s.deaths)||0));
    b.headshots=Math.max(0,Math.floor(Number(s.headshots)||0));
    b.weaponState={...b.weaponState};
    if(s.weaponState&&typeof s.weaponState==='object') for(const [id,v] of Object.entries(s.weaponState)){if(!WEAPON_MAP[id])continue;b.weaponState[id]={owned:!!v?.owned,level:clamp(Math.floor(v?.level||1),1,10),durability:clamp(v?.durability??100,0,100)};}
    b.equipped={...b.equipped,...(s.equipped&&typeof s.equipped==='object'?s.equipped:{})};
    for(const slot of SLOT_ORDER){const id=b.equipped[slot];if(id&&(!WEAPON_MAP[id]||WEAPON_MAP[id].slot!==slot||!b.weaponState[id]?.owned))b.equipped[slot]=slot==='melee'?'knife':slot==='sidearm'?'glock':'';}
    b.inventory={...b.inventory,...(s.inventory&&typeof s.inventory==='object'?s.inventory:{})};
    b.settings={...b.settings,...(s.settings&&typeof s.settings==='object'?s.settings:{})};
    if(!['dustline','harbor','metro'].includes(b.settings.lastMap))b.settings.lastMap='dustline';
    if(!['deathmatch','gungame'].includes(b.settings.lastGameMode))b.settings.lastGameMode='deathmatch';
    b.stats={...b.stats,...(s.stats&&typeof s.stats==='object'?s.stats:{})};
    b.lastMode=String(s.lastMode||'lobby');
    return b;
  }
  function state(){const root=rootState();if(root){if(root.egoshootKL?.version!==2)root.egoshootKL=normalizeState(root.egoshootKL);return root.egoshootKL;}if(stateCache?.version!==2){try{stateCache=normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'));}catch{stateCache=defaultState();}}return stateCache;}
  function persist(){if(persistTimer){clearTimeout(persistTimer);persistTimer=0;}const s=state(),root=rootState();if(root){root.egoshootKL=s;window.JKGamesPersistState?.();}else try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}catch{};window.dispatchEvent(new CustomEvent('egoshoot-kl-state-changed',{detail:{kills:s.totalKills,tokens:s.killTokens,gender:s.gender}}));}
  function persistSoon(delay=1200){if(persistTimer)return;persistTimer=setTimeout(()=>{persistTimer=0;persist();},Math.max(250,Number(delay)||1200));}
  function weaponState(id){const s=state();if(!s.weaponState[id])s.weaponState[id]={owned:false,level:1,durability:100};return s.weaponState[id];}
  function weaponStats(id){const w=WEAPON_MAP[id]||WEAPON_MAP.glock,ws=weaponState(w.id),lvl=clamp(ws.level,1,10),damage=w.damage*(1+(lvl-1)*.04),stability=clamp(w.stability+(lvl-1)*2.1,0,99.5),rate=Math.max(.045,w.rate*(1-(lvl-1)*.012));return {...w,level:lvl,damage,stability,rate,durability:ws.durability};}

  function bundledAssetKey(url){return String(url||'').split(/[?#]/,1)[0].split('/').pop()||'';}
  function bundledAssetUrl(url){
    const key=bundledAssetKey(url),b64=EGOSHOOT_ASSETS[key];
    if(!b64)throw new Error(`Egoshoot.KL Asset fehlt im V510-Bundle: ${key||url}`);
    if(assetObjectUrls.has(key))return assetObjectUrls.get(key);
    const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
    const objectUrl=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'}));assetObjectUrls.set(key,objectUrl);return objectUrl;
  }
  function loadGLB(url){
    const key=bundledAssetKey(url);
    if(!glbCache.has(key))glbCache.set(key,new Promise((resolve,reject)=>{
      let source='';try{source=bundledAssetUrl(url);}catch(err){reject(err);return;}
      loader.load(source,g=>resolve(g),undefined,err=>reject(new Error(`Egoshoot.KL konnte ${key} nicht laden: ${String(err?.message||err)}`)));
    }));
    return glbCache.get(key);
  }
  async function characterTemplate(gender){
    if(characterCache.has(gender))return characterCache.get(gender);
    const p=(async()=>{const walk=await loadGLB(`${ASSET}${gender==='woman'?'woman-walk':'man-walk'}.glb`),run=await loadGLB(`${ASSET}${gender==='woman'?'woman-run':'man-run'}.glb`);return {walkScene:walk.scene,runScene:run.scene,walk:walk.animations?.[0]||null,run:run.animations?.[0]||null};})();
    characterCache.set(gender,p); return p;
  }
  function normalizeCharacter(scene){
    // Die gelieferten Mann/Frau-Rigs sind bereits Y-up. Die Mesh-Bind-Pose sieht in der
    // BoundingBox zwar liegend aus, die Bones stehen aber korrekt. Deshalb wird hier
    // KEINE 90-Grad-Korrektur mehr auf das gesamte Modell gelegt.
    const wrapper=new THREE.Group();wrapper.userData.esklCharacterWrapper=true;wrapper.add(scene);
    scene.position.set(0,0,0);scene.rotation.set(0,0,0);scene.scale.set(1,1,1);wrapper.updateMatrixWorld(true);

    // Groesse/Fussboden werden ueber das Skelett ermittelt, nicht ueber die ungepose-te
    // SkinnedMesh-BoundingBox. So bleibt die Figur dauerhaft hochkant und ca. 1,72 m gross.
    const bones=[];scene.traverse(o=>{if(o?.isBone||/^bip /i.test(String(o?.name||'')))bones.push(o);});
    const head=bones.find(o=>/^bip Head_/i.test(o.name))||bones.find(o=>/Head/i.test(o.name));
    const feet=bones.filter(o=>/^bip [LR] Foot_/i.test(o.name));
    const pelvis=bones.find(o=>/^bip Pelvis_/i.test(o.name));
    const wp=new THREE.Vector3(),headPos=new THREE.Vector3(),pelvisPos=new THREE.Vector3();
    if(head)head.getWorldPosition(headPos);
    if(pelvis)pelvis.getWorldPosition(pelvisPos);
    let floorY=Infinity;for(const foot of feet){foot.getWorldPosition(wp);floorY=Math.min(floorY,wp.y);}
    if(!Number.isFinite(floorY))floorY=0;
    const skeletonHeight=head?Math.max(.75,headPos.y-floorY+.20):1.72;
    const scale=clamp(1.72/skeletonHeight,.72,1.45);wrapper.scale.setScalar(scale);
    wrapper.position.set(-(pelvis?pelvisPos.x*scale:0),-floorY*scale,-(pelvis?pelvisPos.z*scale:0));
    wrapper.updateMatrixWorld(true);return wrapper;
  }
  function sanitizeCharacterClip(clip){
    if(!clip)return null;const c=clip.clone();
    // Nur echte In-Place-Bewegung: globale Export-Roots duerfen weder Position noch
    // Rotation der kompletten Figur veraendern. Arme, Beine, Oberkoerper usw. bleiben animiert.
    c.tracks=c.tracks.filter(track=>{
      const name=String(track.name||'');
      return !/(^|[./])(bip_01|bip Footsteps|RootNode|rig_CharRoot|_rootJoint)\.(position|quaternion|rotation|scale)$/i.test(name);
    });
    c.resetDuration?.();return c;
  }
  function buildStableIdleClip(walkClip){
    if(!walkClip?.tracks?.length)return null;
    // Der Export besitzt keine eigene Idle-Animation. Frame 0 der Laufdatei ist fuer
    // einige Skins jedoch keine gueltige zusammenhaengende Pose (Hüfte/Beine trennen sich).
    // Deshalb wird eine vollstaendige statische Pose aus zwei gegenueberliegenden,
    // gueltigen Gehphasen gemittelt. So bleiben ALLE Bones konsistent zueinander.
    const duration=Math.max(.001,Number(walkClip.duration)||1),ta=duration*.25,tb=duration*.75,tracks=[];
    for(const track of walkClip.tracks){
      try{
        const ia=track.createInterpolant(),ib=track.createInterpolant(),a=ia.evaluate(ta),b=ib.evaluate(tb);let values=[];
        if(track instanceof THREE.QuaternionKeyframeTrack){
          const qa=new THREE.Quaternion(a[0],a[1],a[2],a[3]),qb=new THREE.Quaternion(b[0],b[1],b[2],b[3]);if(qa.dot(qb)<0)qb.set(-qb.x,-qb.y,-qb.z,-qb.w);qa.slerp(qb,.5).normalize();values=[qa.x,qa.y,qa.z,qa.w];
        }else values=Array.from(a,(v,i)=>(Number(v)+Number(b[i]??v))*.5);
        tracks.push(new track.constructor(track.name,[0],values));
      }catch{}
    }
    return tracks.length?new THREE.AnimationClip('ESKL_StableIdle',1,tracks):null;
  }
  function normalizeWeapon(scene,target=.75){const box=new THREE.Box3().setFromObject(scene),size=new THREE.Vector3();box.getSize(size);const max=Math.max(size.x,size.y,size.z,.001),sc=target/max;scene.scale.setScalar(sc);box.setFromObject(scene);const c=new THREE.Vector3();box.getCenter(c);scene.position.sub(c);return scene;}
  function orientWeaponForward(scene,w){
    // Die meisten gelieferten Waffen zeigen in +X, einige in +/-Z. Fuer die Ego-Sicht
    // werden alle Modelle auf dieselbe Vorwaertsrichtung (-Z der Kamera) vereinheitlicht.
    const box=new THREE.Box3().setFromObject(scene),size=new THREE.Vector3();box.getSize(size);
    let yaw=0;if(size.x>size.z*1.18)yaw=Math.PI/2;
    else if(w?.id==='katana'||w?.id==='sand-pistol')yaw=Math.PI;
    scene.rotation.y+=yaw;scene.userData.esklForwardYaw=yaw;scene.updateMatrixWorld(true);return scene;
  }
  function fpModelSize(w){if(!w)return .5;if(w.type==='pistol')return .46;if(w.type==='smg')return .55;if(w.type==='melee')return (w.id==='katana'||w.id==='baseball') ? .66 : .56;return .72;}
  function fpPose(w){
    if(w.type==='melee')return {pos:new THREE.Vector3(.20,-.31,-.67),ads:new THREE.Vector3(.10,-.28,-.71),rot:new THREE.Euler(0,0,0,'XYZ')};
    if(w.type==='pistol')return {pos:new THREE.Vector3(.16,-.25,-.62),ads:new THREE.Vector3(0,-.215,-.66),rot:new THREE.Euler(0,0,0,'XYZ')};
    if(w.type==='smg')return {pos:new THREE.Vector3(.18,-.27,-.72),ads:new THREE.Vector3(0,-.225,-.76),rot:new THREE.Euler(0,0,0,'XYZ')};
    return {pos:new THREE.Vector3(.22,-.29,-.88),ads:new THREE.Vector3(0,-.235,-.91),rot:new THREE.Euler(0,0,0,'XYZ')};
  }
  async function makeCharacter(gender,label=''){
    const t=await characterTemplate(gender),walkVisual=normalizeCharacter(cloneSkeleton(t.walkScene)),runVisual=normalizeCharacter(cloneSkeleton(t.runScene));
    const root=new THREE.Group(),modelGroup=new THREE.Group();root.add(modelGroup);modelGroup.add(walkVisual,runVisual);
    // Die gelieferten Skins schauen in ihrer Modell-Datei genau entgegengesetzt zur
    // Spiel-Vorwaertsrichtung. Deshalb werden NUR die sichtbaren Rigs dauerhaft um 180°
    // gedreht. Der Controller/Root bleibt starr und teilt sich weiterhin exakt s.yaw.
    walkVisual.rotation.set(0,Math.PI,0);runVisual.rotation.set(0,Math.PI,0);runVisual.visible=false;
    const walkMixer=new THREE.AnimationMixer(walkVisual),runMixer=new THREE.AnimationMixer(runVisual),actions={},walkClip=sanitizeCharacterClip(t.walk),runClip=sanitizeCharacterClip(t.run),idleClip=buildStableIdleClip(walkClip);
    if(idleClip){actions.idle=walkMixer.clipAction(idleClip);actions.idle.play();actions.idle.setEffectiveWeight(1);}
    if(walkClip){actions.walk=walkMixer.clipAction(walkClip);actions.walk.play();actions.walk.setEffectiveWeight(0);actions.walk.timeScale=1;}
    if(runClip){actions.run=runMixer.clipAction(runClip);actions.run.play();actions.run.paused=true;actions.run.timeScale=1.05;}
    const head=new THREE.Mesh(new THREE.BoxGeometry(.34,.32,.32),new THREE.MeshBasicMaterial({visible:false}));head.position.set(0,1.59,0);head.userData.hitZone='head';root.add(head);
    const body=new THREE.Mesh(new THREE.BoxGeometry(.72,1.16,.5),new THREE.MeshBasicMaterial({visible:false}));body.position.set(0,.82,0);body.userData.hitZone='body';root.add(body);
    if(label){const sp=makeLabel(label);sp.position.y=2.15;root.add(sp);}
    const findRigBones=visual=>{const rig={};visual?.traverse?.(o=>{const n=String(o?.name||'');if(!(o?.isBone||/^bip /i.test(n)))return;if(/bip Pelvis|Pelvis/i.test(n))rig.pelvis=o;else if(/bip Spine1|Spine1|Chest/i.test(n))rig.spine1=o;else if(/bip Spine|Spine/i.test(n))rig.spine=o;else if(/bip L UpperArm|LeftUpperArm|L_UpperArm/i.test(n))rig.lUpper=o;else if(/bip L Forearm|LeftForearm|L_Forearm/i.test(n))rig.lFore=o;else if(/bip L Hand|LeftHand|L_Hand/i.test(n))rig.lHand=o;else if(/bip R UpperArm|RightUpperArm|R_UpperArm/i.test(n))rig.rUpper=o;else if(/bip R Forearm|RightForearm|R_Forearm/i.test(n))rig.rFore=o;else if(/bip R Hand|RightHand|R_Hand/i.test(n))rig.rHand=o;else if(/bip L Thigh|LeftThigh|L_Thigh/i.test(n))rig.lThigh=o;else if(/bip L Calf|LeftCalf|L_Calf/i.test(n))rig.lCalf=o;else if(/bip L Foot|LeftFoot|L_Foot/i.test(n))rig.lFoot=o;else if(/bip R Thigh|RightThigh|R_Thigh/i.test(n))rig.rThigh=o;else if(/bip R Calf|RightCalf|R_Calf/i.test(n))rig.rCalf=o;else if(/bip R Foot|RightFoot|R_Foot/i.test(n))rig.rFoot=o;});rig.rest={};for(const k of ['pelvis','spine','spine1','lUpper','lFore','lHand','rUpper','rFore','rHand','lThigh','lCalf','lFoot','rThigh','rCalf','rFoot']){const b=rig[k];if(b)rig.rest[k]={q:b.quaternion.clone(),p:b.position.clone()};}return rig;};
    const walkRig=findRigBones(walkVisual),runRig=findRigBones(runVisual);
    return {root,modelGroup,walkVisual,runVisual,walkMixer,runMixer,actions,motion:'',stance:'stand',idlePhase:Math.random()*Math.PI*2,head,body,walkRig,runRig,walkHand:walkRig.rHand,runHand:runRig.rHand,heldWeapon:null,holsteredWeapons:[]};
  }
  function setMotion(ch,motion){
    if(!ch||ch.motion===motion)return;ch.motion=motion;const running=motion==='run',walking=motion==='walk'||motion==='walk-back';ch.walkVisual.visible=!running;ch.runVisual.visible=running;
    if(ch.actions.idle){ch.actions.idle.enabled=true;ch.actions.idle.paused=false;ch.actions.idle.setEffectiveWeight(running||walking?0:1);}
    if(ch.actions.walk){ch.actions.walk.enabled=true;ch.actions.walk.paused=false;ch.actions.walk.setEffectiveWeight(walking?1:0);ch.actions.walk.timeScale=motion==='walk-back'?.78:1;}
    if(ch.actions.run){ch.actions.run.paused=!running;if(running)ch.actions.run.setEffectiveWeight(1);ch.actions.run.timeScale=1.05;}
  }
  function setCharacterStance(ch,stance='stand'){if(!ch)return;ch.stance=stance;const crouch=stance==='crouch',prone=stance==='prone';ch.head.position.set(0,prone?.43:crouch?1.08:1.59,prone?-.48:0);ch.body.position.set(0,prone?.35:crouch?.69:.82,prone?-.16:0);ch.head.scale.set(1,1,1);ch.body.scale.set(1,crouch?.82:prone?.50:1,prone?1.65:1);}
  function activeRig(ch){return ch?.runVisual?.visible?(ch.runRig||ch.walkRig):(ch?.walkRig||ch?.runRig);}
  function rootLocalToWorld(ch,x,y,z){const v=new THREE.Vector3(x,y,z);ch.root.updateMatrixWorld(true);return ch.root.localToWorld(v);}
  function restoreRigBone(rig,key,restorePosition=true){const b=rig?.[key],r=rig?.rest?.[key];if(!b||!r)return;if(restorePosition&&r.p)b.position.copy(r.p);if(r.q)b.quaternion.copy(r.q);}
  function aimBoneFromRest(rig,boneKey,childKey,targetWorld){const bone=rig?.[boneKey],child=rig?.[childKey],rest=rig?.rest?.[boneKey];if(!bone?.parent||!child||!rest?.q||!targetWorld)return false;bone.parent.updateMatrixWorld(true);const targetLocal=bone.parent.worldToLocal(targetWorld.clone()),dir=targetLocal.sub(bone.position);if(dir.lengthSq()<1e-8)return false;dir.normalize();const base=child.position.clone();if(base.lengthSq()<1e-8)return false;base.normalize().applyQuaternion(rest.q).normalize();const delta=new THREE.Quaternion().setFromUnitVectors(base,dir);bone.quaternion.copy(delta.multiply(rest.q));bone.updateMatrixWorld(true);return true;}
  function solveLimbFromRest(rig,upperKey,lowerKey,endKey,elbowWorld,endWorld){if(!rig)return false;restoreRigBone(rig,upperKey,false);restoreRigBone(rig,lowerKey,false);const a=aimBoneFromRest(rig,upperKey,lowerKey,elbowWorld);rig?.[upperKey]?.updateWorldMatrix?.(true,true);const b=aimBoneFromRest(rig,lowerKey,endKey,endWorld);return a&&b;}
  function updateCharacterAnimation(ch,dt){if(!ch)return;ch.walkMixer?.update?.(dt);ch.runMixer?.update?.(dt);const stance=ch.stance||'stand',prone=stance==='prone',crouch=stance==='crouch',ease=Math.min(1,dt*16),targetY=prone?.43:0,targetZ=prone?.16:0,targetX=prone?-Math.PI/2:0,targetScaleY=crouch?.84:1;ch.modelGroup.position.x=0;ch.modelGroup.position.y+=(targetY-ch.modelGroup.position.y)*ease;ch.modelGroup.position.z+=(targetZ-ch.modelGroup.position.z)*ease;ch.modelGroup.rotation.x+=(targetX-ch.modelGroup.rotation.x)*ease;ch.modelGroup.rotation.y=0;ch.modelGroup.rotation.z=0;ch.modelGroup.scale.x=1;ch.modelGroup.scale.z=1;ch.modelGroup.scale.y+=(targetScaleY-ch.modelGroup.scale.y)*ease;}

  function makeLabel(text){const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d');x.fillStyle='rgba(5,9,15,.82)';x.fillRect(4,12,504,72);x.fillStyle='#fff';x.font='700 29px system-ui';x.textAlign='center';x.fillText(String(text).slice(0,30),256,58);const tex=new THREE.CanvasTexture(c),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.scale.set(4.8,.9,1);return sp;}
  async function makeWeaponModel(id,target=.72){const w=WEAPON_MAP[id],g=await loadGLB(`${ASSET}${w.file}`),scene=orientWeaponForward(normalizeWeapon(cloneSkeleton(g.scene),target),w);scene.userData.esklAnimations=g.animations||[];scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return scene;}

  const MAPS = Object.freeze({
    dustline:{id:'dustline',name:'Dustline',subtitle:'Wüste · Mid · Long · Tunnel',sky:0x9b7b4f,fog:0xc8a56d,ground:0xb89661},
    harbor:{id:'harbor',name:'Harbor Yard',subtitle:'Container · Warehouse · Catwalk',sky:0x30455a,fog:0x607789,ground:0x394853},
    metro:{id:'metro',name:'Metro Core',subtitle:'Station · Plattform · Servicegänge',sky:0x0d1620,fog:0x223444,ground:0x20262c}
  });
  const GUN_GAME_ORDER = Object.freeze(['glock','sand-pistol','revolver','desert-eagle','mini-uzi','uzi','ump9','tommy','m4','ak12','an94','scar','suppressed','ak47','shotgun','barrett','katana','knife']);
  const DEFAULT_MAP_SPAWNS = Object.freeze([
    [-55,0,-48],[54,0,-50],[-56,0,47],[54,0,48],[-6,0,-59],[8,0,58],[-44,0,0],[46,0,3]
  ]);

  function resetInputs(){
    UI.keys=Object.create(null);UI.mouse.down=false;UI.mouse.ads=false;UI.touch={forward:false,back:false,left:false,right:false,fire:false,run:false,ads:false};
    if(UI.session){UI.session.shotHeld=false;UI.session.moving=false;UI.session.running=false;}
  }

  function open(sourcePhone=''){
    close(false);UI.sourcePhone=sourcePhone||window.JKGamesOwnedPhoneItem?.()||'';
    const overlay=document.createElement('div');overlay.className='eskl-overlay';overlay.dataset.egoshootKl='1';overlay.innerHTML=`<div class="eskl-shell"><header class="eskl-topbar"><div class="eskl-brand"><small>JK.GAMES · TOP GAME</small><h1>Egoshoot.KL</h1><span>FPS ONLY</span></div><div class="eskl-stats"><span><small>KILLS</small><b data-eskl-kills>0</b></span><span><small>KILL-PUNKTE</small><b data-eskl-tokens>0</b></span></div><div class="eskl-actions"><button data-eskl-lobby>Lobby</button><button data-eskl-arsenal>Arsenal</button><button data-eskl-shop>Shop</button><button data-eskl-jk>JK</button><button data-eskl-info>?</button><button class="close" data-eskl-close>×</button></div></header><main class="eskl-body" data-eskl-body></main><div class="eskl-toast" data-eskl-toast></div></div>`;
    document.body.append(overlay);document.body.classList.add('egoshoot-kl-open');UI.overlay=overlay;UI.body=overlay.querySelector('[data-eskl-body]');
    overlay.querySelector('[data-eskl-close]').onclick=()=>close(true);
    overlay.querySelector('[data-eskl-lobby]').onclick=()=>startLobby();
    overlay.querySelector('[data-eskl-jk]').onclick=()=>window.JKCoinApp?.openForGame?.('egoshoot');
    overlay.querySelector('[data-eskl-arsenal]').onclick=()=>UI.session?.mode==='lobby'?openArsenal():toast('Loadout nur in der Lobby ändern.','bad');
    overlay.querySelector('[data-eskl-shop]').onclick=()=>UI.session?.mode==='lobby'?openShop():toast('Shop nur in der Lobby.','bad');
    overlay.querySelector('[data-eskl-info]').onclick=()=>openInfo();
    window.addEventListener('keydown',onKeyDown,{passive:false});window.addEventListener('keyup',onKeyUp,{passive:false});window.addEventListener('mousemove',onMouseMove,{passive:true});window.addEventListener('mousedown',onMouseDown,{passive:false});window.addEventListener('mouseup',onMouseUp,{passive:true});window.addEventListener('contextmenu',onContextMenu);
    document.addEventListener('pointerlockchange',onPointerLockChange);
    refreshHeader();if(!state().gender)renderGenderChoice();else startLobby();setTimeout(()=>window.JKCoinApp?.applyPendingGameEntitlements?.(),500);
  }
  function close(returnTopGames=false){stopWorld();if(persistTimer)persist();closeModal();window.removeEventListener('keydown',onKeyDown);window.removeEventListener('keyup',onKeyUp);window.removeEventListener('mousemove',onMouseMove);window.removeEventListener('mousedown',onMouseDown);window.removeEventListener('mouseup',onMouseUp);window.removeEventListener('contextmenu',onContextMenu);document.removeEventListener('pointerlockchange',onPointerLockChange);resetInputs();try{document.exitPointerLock?.();}catch{}UI.overlay?.remove();UI.overlay=null;UI.body=null;document.body.classList.remove('egoshoot-kl-open');if(returnTopGames)setTimeout(()=>window.JKGamesOpenTopGames?.(UI.sourcePhone),80);}
  function refreshHeader(){if(!UI.overlay)return;UI.overlay.querySelector('[data-eskl-kills]').textContent=fmt(state().totalKills);UI.overlay.querySelector('[data-eskl-tokens]').textContent=fmt(state().killTokens);}
  function toast(message,tone=''){const el=UI.overlay?.querySelector('[data-eskl-toast]');if(!el)return;clearTimeout(UI.toastTimer);el.textContent=message;el.className=`eskl-toast show ${tone}`;UI.toastTimer=setTimeout(()=>el.className='eskl-toast',2800);}
  function renderGenderChoice(){stopWorld();UI.body.innerHTML=`<section class="eskl-choice"><small>CHARAKTER</small><h2>Wähle deinen Online-Charakter</h2><p>Du spielst selbst ausschließlich in Ego-Perspektive. Andere Spieler sehen diesen Charakter samt aktuell gehaltener Waffe.</p><div class="eskl-choice-grid"><button data-gender="man"><b>♂ Mann</b><small>Online-Modell</small></button><button data-gender="woman"><b>♀ Frau</b><small>Online-Modell</small></button></div></section>`;UI.body.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{state().gender=b.dataset.gender;persist();startLobby();});}

  function openInfo(){showModal(`<div class="eskl-modal-head"><div><small>V510 · FPS REBUILD</small><h2>Egoshoot.KL</h2></div><button data-modal-close>×</button></div><div class="eskl-info-grid"><article><b>🎯 Nur Ego</b><p>Keine Third-Person-Umschaltung mehr. WASD bewegt, Maus zielt, Linksklick feuert, Rechtsklick ADS, R lädt, SPACE springt, C duckt.</p></article><article><b>🔫 Lobby-Schießen</b><p>In der Lobby darfst du mit deinem Loadout schießen und die Ziele im Trainingsbereich treffen. Spieler- oder Bot-Schaden ist dort vollständig deaktiviert.</p></article><article><b>🗺️ Taktische Maps</b><p>Dustline, Harbor Yard und Metro Core sind eigenständige CS-artige Karten mit Mid, Long, Tunneln, Containern, Sites und Servicegängen.</p></article><article><b>🌐 Online</b><p>Online-Spieler werden nur angezeigt, wenn Map und Modus übereinstimmen. Ihre aktuelle Waffe ist direkt am Charakter sichtbar.</p></article><article><b>🔁 Waffengame</b><p>Jeder eigene Kill schaltet sofort die nächste Waffe der Runde frei. Die letzten Stufen sind Barrett, Katana und Messer.</p></article><article><b>⚙️ Performance</b><p>Reduzierte Pixelratio, weniger Shadow-Last und selteneres HUD-Rendering sorgen für flüssigere Bewegung.</p></article></div>`);}

  function openShop(){const s=state();showModal(`<div class="eskl-modal-head"><div><small>LOBBY SHOP</small><h2>Waffen & Versorgung</h2><p>${fmt(s.totalKills)} Kills · ${fmt(s.killTokens)} Kill-Punkte</p></div><button data-modal-close>×</button></div><div class="eskl-shop-tabs"><button class="active" data-shop-tab="weapons">Waffen</button><button data-shop-tab="supply">Versorgung</button><button data-shop-tab="repair">Reparatur / Level</button></div><div data-shop-body></div>`);UI.modal.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{UI.modal.querySelectorAll('[data-shop-tab]').forEach(x=>x.classList.toggle('active',x===b));renderShopTab(b.dataset.shopTab);});renderShopTab('weapons');}
  function renderShopTab(tab){const host=UI.modal?.querySelector('[data-shop-body]');if(!host)return;const s=state();if(tab==='weapons')host.innerHTML=`<div class="eskl-shop-grid">${WEAPONS.map(w=>{const ws=weaponState(w.id),locked=s.totalKills<w.minKills;return `<article><small>${w.slot.toUpperCase()} · ${w.type.toUpperCase()}</small><h3>${esc(w.name)}</h3><p>${esc(w.desc)}</p><div class="eskl-mini-stats"><span>DMG <b>${Math.round(weaponStats(w.id).damage)}</b></span><span>STAB <b>${Math.round(weaponStats(w.id).stability)}%</b></span>${w.mag?`<span>MAG <b>${w.mag}</b></span>`:''}<span>LVL <b>${ws.level}/10</b></span></div>${ws.owned?'<button disabled>Besitzt du</button>':locked?`<button disabled>🔒 ab ${fmt(w.minKills)} Kills</button>`:`<button data-buy-weapon="${w.id}">${w.cost} Kill-Punkte · kaufen</button>`}</article>`;}).join('')}</div>`;
    else if(tab==='supply')host.innerHTML=`<div class="eskl-shop-grid">${[{id:'heal',name:'Lebenstrank',cost:4,text:'+60 Leben im Kampf'},{id:'speed',name:'Speed-Trank',cost:6,text:'12 Sekunden schneller'},{id:'shield100',name:'Shield',cost:10,text:'+100 Schutz'},{id:'shield150',name:'Verbesserter Shield',cost:18,text:'+150 Schutz'},{id:'shield200',name:'Ultra-Shield',cost:30,text:'+200 Schutz'}].map(x=>`<article><small>VERSORGUNG</small><h3>${x.name}</h3><p>${x.text}</p><button data-buy-supply="${x.id}" data-cost="${x.cost}">${x.cost} Kill-Punkte · kaufen</button></article>`).join('')}</div>`;
    else host.innerHTML=`<div class="eskl-shop-grid">${WEAPONS.filter(w=>weaponState(w.id).owned).map(w=>{const ws=weaponState(w.id),next=UPGRADE_COSTS[ws.level]||0,repair=Math.max(2,Math.ceil((100-ws.durability)/20)+ws.level);return `<article><small>${esc(w.name)}</small><h3>Level ${ws.level}/10</h3><p>Haltbarkeit ${Math.round(ws.durability)}%</p><div class="eskl-row-buttons"><button data-repair="${w.id}" ${ws.durability>=99.9?'disabled':''}>Reparieren · ${repair}</button><button data-upgrade="${w.id}" ${ws.level>=10?'disabled':''}>${ws.level>=10?'MAX':'Level +1 · '+next}</button></div></article>`;}).join('')}</div>`;bindShopActions();}
  function bindShopActions(){UI.modal?.querySelectorAll('[data-buy-weapon]').forEach(b=>b.onclick=()=>{const w=WEAPON_MAP[b.dataset.buyWeapon],s=state();if(!w||s.totalKills<w.minKills||s.killTokens<w.cost)return toast('Noch nicht genug Kills/Kill-Punkte.','bad');s.killTokens-=w.cost;weaponState(w.id).owned=true;weaponState(w.id).durability=100;persist();refreshHeader();renderShopTab('weapons');toast(`${w.name} freigeschaltet.`,'good');});UI.modal?.querySelectorAll('[data-buy-supply]').forEach(b=>b.onclick=()=>{const s=state(),cost=Number(b.dataset.cost)||0,id=b.dataset.buySupply;if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;s.inventory[id]=Number(s.inventory[id]||0)+1;persist();refreshHeader();renderShopTab('supply');toast('Gekauft.','good');});UI.modal?.querySelectorAll('[data-repair]').forEach(b=>b.onclick=()=>{const id=b.dataset.repair,ws=weaponState(id),cost=Math.max(2,Math.ceil((100-ws.durability)/20)+ws.level),s=state();if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;ws.durability=100;persist();refreshHeader();renderShopTab('repair');});UI.modal?.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const id=b.dataset.upgrade,ws=weaponState(id),cost=UPGRADE_COSTS[ws.level]||99999,s=state();if(ws.level>=10)return;if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;ws.level++;persist();refreshHeader();renderShopTab('repair');});}
  function openArsenal(){const s=state();showModal(`<div class="eskl-modal-head"><div><small>LOADOUT</small><h2>Dein Waffen-Set</h2><p>Diese Waffen benutzt du in Lobby und Deathmatch. Im Waffengame wird das Loadout temporär durch die Waffenleiter ersetzt.</p></div><button data-modal-close>×</button></div><div class="eskl-loadout">${SLOT_ORDER.map(slot=>`<section><h3>${slot==='melee'?'Nahkampf':slot==='sidearm'?'Pistole / SMG':'Langwaffe'}</h3><div>${WEAPONS.filter(w=>w.slot===slot&&weaponState(w.id).owned).map(w=>`<button class="${s.equipped[slot]===w.id?'active':''}" data-equip="${w.id}"><b>${esc(w.name)}</b><small>Level ${weaponState(w.id).level} · ${Math.round(weaponState(w.id).durability)}%</small></button>`).join('')||'<p>Noch keine Waffe.</p>'}</div></section>`).join('')}</div>`);UI.modal.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const w=WEAPON_MAP[b.dataset.equip];if(!w)return;s.equipped[w.slot]=w.id;persist();closeModal();openArsenal();if(UI.session?.mode==='lobby')updateFpWeapon(UI.session);});}
  function showModal(html){closeModal();resetInputs();try{document.exitPointerLock?.();}catch{}const m=document.createElement('div');m.className='eskl-modal-wrap';m.innerHTML=`<div class="eskl-modal-card">${html}</div>`;document.body.append(m);UI.modal=m;m.querySelector('[data-modal-close]')?.addEventListener('click',closeModal);m.addEventListener('mousedown',e=>{if(e.target===m)closeModal();});return m;}
  function closeModal(){UI.modal?.remove();UI.modal=null;resetInputs();}

  function worldHtml(s){const lobby=s.mode==='lobby';return `<div class="eskl-world"><div class="eskl-canvas" data-eskl-canvas></div><div class="eskl-hud"><div class="eskl-top-left"><div class="eskl-bars"><label><span>HP <b data-hp-text>100</b></span><i><em class="hp" data-hp-bar></em></i></label><label><span>SHIELD <b data-shield-text>0</b></span><i><em class="shield" data-shield-bar></em></i></label></div><div class="eskl-match-card"><small data-mode-label>${lobby?'TRAINING LOBBY':'MATCH'}</small><b data-map-label>${lobby?'FPS TRAINING':esc(MAPS[s.mapId]?.name||'Arena')}</b><span data-online-label>${lobby?'Schießen erlaubt · kein Schaden':'0 Spieler online'}</span></div></div><div class="eskl-top-right"><span><small>WAFFE</small><b data-world-weapon>-</b></span><span><small>AMMO</small><b data-world-ammo>-</b></span><span class="gungame" data-gungame-box hidden><small>WAFFENGAME</small><b data-gungame-level>1/${GUN_GAME_ORDER.length}</b></span></div><div class="eskl-crosshair" data-crosshair><i></i><i></i></div><div class="eskl-hitmarker" data-hitmarker>×</div><div class="eskl-prompt" data-world-prompt></div><div class="eskl-bottom-left"><button data-use="heal">❤️ <b data-count="heal">0</b></button><button data-use="speed">⚡ <b data-count="speed">0</b></button><button data-use="shield100">🛡100 <b data-count="shield100">0</b></button><button data-use="shield150">🛡150 <b data-count="shield150">0</b></button><button data-use="shield200">🛡200 <b data-count="shield200">0</b></button></div><div class="eskl-weaponbar"><button data-slot="melee"><small>1</small><b>Nahkampf</b></button><button data-slot="sidearm"><small>2</small><b>Sidearm</b></button><button data-slot="long"><small>3</small><b>Langwaffe</b></button></div><div class="eskl-bottom-right"><button data-reload>R · Laden</button><button data-interact>E · Aktion</button>${isStaff()?'<button class="staff" data-staff-mod>Q · MOD</button>':''}</div><div class="eskl-touch"><div class="move"><button data-touch="forward">▲</button><button data-touch="left">◀</button><button data-touch="back">▼</button><button data-touch="right">▶</button></div><div class="combat"><button data-touch="run">RUN</button><button data-action="crouch">DUCK</button><button data-action="jump">JUMP</button><button data-touch="ads">ADS</button><button class="fire" data-touch="fire">FIRE</button></div></div></div></div>`;}

  async function startLobby(){await startWorld({mode:'lobby',mapId:'lobby',gameMode:'training',online:false});}
  async function startCombat(mapId,gameMode='deathmatch',online=true){const id=MAPS[mapId]?mapId:'dustline',gm=gameMode==='gungame'?'gungame':'deathmatch';state().settings.lastMap=id;state().settings.lastGameMode=gm;persist();await startWorld({mode:'combat',mapId:id,gameMode:gm,online:!!online});}
  async function startWorld(cfg){
    stopWorld();closeModal();resetInputs();const mode=cfg.mode||'lobby',mapId=cfg.mapId||'lobby',gameMode=cfg.gameMode||'training';state().lastMode=mode;persist();
    const dummy={mode,mapId,gameMode};UI.body.innerHTML=worldHtml(dummy);const wrap=UI.body.querySelector('[data-eskl-canvas]'),scene=new THREE.Scene(),map=MAPS[mapId];scene.background=new THREE.Color(mode==='lobby'?0x09131c:(map?.sky||0x071019));scene.fog=new THREE.FogExp2(mode==='lobby'?0x0d1b27:(map?.fog||0x21313b),mode==='lobby'?.0105:.0052);
    const camera=new THREE.PerspectiveCamera(72,1,.055,360),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',alpha:false});scene.add(camera);renderer.setPixelRatio(Math.min(devicePixelRatio,isTouch()?1.15:1.35));renderer.shadowMap.enabled=!isTouch();renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;wrap.append(renderer.domElement);
    scene.add(new THREE.HemisphereLight(mode==='lobby'?0xaed8ff:0xcfe7ff,mode==='lobby'?0x0e161d:0x1a2020,2.4));const sun=new THREE.DirectionalLight(mode==='lobby'?0xd5edff:0xffe2b8,2.4);sun.position.set(36,58,24);sun.castShadow=!isTouch();sun.shadow.mapSize.set(768,768);scene.add(sun);
    const timer=new THREE.Timer();try{timer.connect(document);}catch{}timer.update();
    const s={mode,mapId,gameMode,online:mode==='combat'&&!!cfg.online,scene,camera,renderer,timer,wrap,gender:state().gender,pos:new THREE.Vector3(),yaw:0,pitch:0,velocity:new THREE.Vector3(),moving:false,running:false,hp:100,maxHp:100,shield:0,maxShield:0,alive:true,currentSlot:'sidearm',ammo:{},reloadUntil:0,lastShotAt:0,speedBoostUntil:0,collision:[],shootables:[],bots:new Map(),remoteVisuals:new Map(),remoteWriteBusy:false,lastRemoteWrite:0,lastRemoteKey:'',seenHits:new Set(),seenRewards:new Set(),pendingHitWrites:[],hitFlushTimer:0,staff:{fly:false,vanish:false,god:false,speed:1},raf:0,worldTime:0,streak:0,weaponKick:0,meleeSwing:0,stance:'stand',verticalVelocity:0,onGround:true,pointerLockBlocked:false,fpArms:null,fpArmsRaw:null,fpArmsMixer:null,fpArmsActions:new Map(),fpArmsAction:'',fpArmsHand:null,fpArmsBuildId:0,bounds:{minX:-72,maxX:72,minZ:-72,maxZ:72},spawns:[],places:{},nearPlace:null,gunLevel:0,matchKills:0,hudNext:0,onlineCount:0,impactPool:[],practiceTargets:[]};UI.session=s;
    for(const w of WEAPONS)s.ammo[w.id]=w.mag||0;
    if(mode==='lobby')buildLobbyMap(s);else buildTacticalMap(s,mapId);
    s.pos.copy(mode==='lobby'?new THREE.Vector3(0,0,23):randomSpawn(s));camera.position.set(s.pos.x,1.6,s.pos.z);await ensureFpArms(s);await updateFpWeapon(s);
    if(mode==='combat'&&!s.online)createBots(s);if(s.online)startOnline(s).catch(err=>toast(`Online nicht verfügbar: ${String(err?.message||err).slice(0,90)}`,'bad'));
    bindWorldUi(s);resizeWorld(s);window.addEventListener('resize',s.resize=()=>resizeWorld(s));renderer.domElement.addEventListener('click',()=>{if(!isTouch()&&!document.pointerLockElement&&!s.pointerLockBlocked&&!UI.modal)renderer.domElement.requestPointerLock?.();});bindTouchLook(s,renderer.domElement);updateHud(s,true);s.raf=requestAnimationFrame(t=>loop(s,t));
  }

  function mat(color,roughness=.86,metalness=.05){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
  function addBox(s,{x=0,y=0,z=0,w=1,h=1,d=1,color=0x444444,material=null,solid=true,shot=true,cast=true,receive=true,name=''}){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material||mat(color));m.position.set(x,y+h/2,z);m.castShadow=cast&&!isTouch();m.receiveShadow=receive;m.name=name;s.scene.add(m);if(solid)addCollider(s,x,z,w,d,m,shot);else if(shot){m.userData.blockShot=true;s.shootables.push(m);}return m;}
  function addPlaneFloor(s,size,color){const g=new THREE.Mesh(new THREE.PlaneGeometry(size,size),mat(color,.96));g.rotation.x=-Math.PI/2;g.receiveShadow=true;s.scene.add(g);return g;}
  function addCollider(s,x,z,w,d,mesh,shot=true){s.collision.push({minX:x-w/2-.35,maxX:x+w/2+.35,minZ:z-d/2-.35,maxZ:z+d/2+.35});if(mesh&&shot){mesh.userData.blockShot=true;s.shootables.push(mesh);}}
  function addBoundary(s,color=0x27303a){addBox(s,{x:0,z:-73,w:148,h:7,d:2,color});addBox(s,{x:0,z:73,w:148,h:7,d:2,color});addBox(s,{x:-73,z:0,w:2,h:7,d:148,color});addBox(s,{x:73,z:0,w:2,h:7,d:148,color});}
  function addLabel(s,text,x,y,z,scale=1){const sp=makeLabel(text);sp.position.set(x,y,z);sp.scale.multiplyScalar(scale);s.scene.add(sp);return sp;}
  function addPlace(s,id,x,z,color,label,kind='action',radius=4.8){const ring=new THREE.Mesh(new THREE.RingGeometry(3.2,4.2,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.62,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.055,z);s.scene.add(ring);const p=new THREE.PointLight(color,2.4,13);p.position.set(x,2.8,z);s.scene.add(p);addLabel(s,label,x,2.9,z,.9);s.places[id]={id,x,z,radius,label,kind};}
  function addSite(s,label,x,z,color){const ring=new THREE.Mesh(new THREE.RingGeometry(5.5,7.2,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.3,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.03,z);s.scene.add(ring);addLabel(s,label,x,3.0,z,.72);}
  function addContainer(s,x,z,rot=0,color=0x1f5d78){const g=new THREE.Group();const body=addBox(s,{x,z,w:6.2,h:2.7,d:2.6,color,solid:true});body.rotation.y=rot;if(rot!==0){s.collision.pop();const swap=Math.abs(Math.sin(rot))>.5;addCollider(s,x,z,swap?2.6:6.2,swap?6.2:2.6,body,true);}for(let i=-2;i<=2;i++){const rib=new THREE.Mesh(new THREE.BoxGeometry(.07,2.45,.04),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.12}));rib.position.set(x+i*1.2,1.38,z+(rot?0:1.32));rib.rotation.y=rot;s.scene.add(rib);}return g;}
  function addCrate(s,x,z,size=2,color=0x6f4b2d){return addBox(s,{x,z,w:size,h:size,d:size,color});}

  function buildLobbyMap(s){s.bounds={minX:-39,maxX:39,minZ:-39,maxZ:39};addPlaneFloor(s,82,0x17212b);addBoundary(s,0x202c38);addBox(s,{x:0,z:38,w:80,h:6,d:2,color:0x253240});addBox(s,{x:-38,z:0,w:2,h:6,d:80,color:0x253240});addBox(s,{x:38,z:0,w:2,h:6,d:80,color:0x253240});
    // Lobby-Inseln und Trainingsbereich
    addBox(s,{x:0,z:8,w:26,h:.3,d:14,color:0x273442,solid:false,shot:false});addLabel(s,'TRAINING RANGE',0,2.8,-25,.95);
    for(let i=0;i<5;i++){const x=-16+i*8,z=-30;const target=new THREE.Mesh(new THREE.CylinderGeometry(.78,.78,.12,32),new THREE.MeshStandardMaterial({color:0xe9edf2,emissive:0x000000}));target.rotation.x=Math.PI/2;target.position.set(x,1.45,z);target.userData.practiceTarget=true;target.userData.blockShot=false;s.scene.add(target);s.shootables.push(target);s.practiceTargets.push(target);const stand=addBox(s,{x,z:z-.3,w:.15,h:1.6,d:.15,color:0x555b60,solid:false,shot:false});}
    addPlace(s,'shop',-29,24,0x55e3ae,'SHOP · E','shop');addPlace(s,'arsenal',29,24,0x8a7dff,'ARSENAL · E','arsenal');
    addPlace(s,'dustline',-24,2,0xe1b45d,'DUSTLINE · E','map');addPlace(s,'harbor',0,2,0x54b9ff,'HARBOR YARD · E','map');addPlace(s,'metro',24,2,0xa87cff,'METRO CORE · E','map');
    addLabel(s,'FPS ONLY · LINKSKLICK = SCHIESSEN',0,3.4,31,.95);addLabel(s,'In der Lobby verursacht kein Treffer Schaden',0,2.2,31,.62);
    for(const x of [-34,34])for(const z of [-20,12])addBox(s,{x,z,w:3,h:2.6,d:3,color:0x354351});
  }

  function buildTacticalMap(s,mapId){addPlaneFloor(s,148,MAPS[mapId]?.ground||0x30343a);addBoundary(s,mapId==='dustline'?0x7a6246:mapId==='harbor'?0x243542:0x1a2229);if(mapId==='harbor')buildHarbor(s);else if(mapId==='metro')buildMetro(s);else buildDustline(s);}
  function buildDustline(s){s.spawns=[[-60,-55],[58,-55],[-59,52],[58,52],[-7,-60],[8,59],[-55,4],[55,-3]].map(([x,z])=>new THREE.Vector3(x,0,z));
    const sand=0x9f7d50,stone=0x7c654d,dark=0x4b4035;addSite(s,'SITE A',48,-38,0xffb84f);addSite(s,'SITE B',-45,38,0x64cfff);addLabel(s,'MID',0,3,0,.72);
    // Mid spine
    addBox(s,{x:-14,z:0,w:8,h:5,d:34,color:stone});addBox(s,{x:14,z:0,w:8,h:5,d:34,color:stone});addBox(s,{x:0,z:-21,w:12,h:5,d:7,color:stone});addBox(s,{x:0,z:22,w:12,h:5,d:7,color:stone});
    // Long A with offset cover
    addBox(s,{x:44,z:-7,w:12,h:5,d:26,color:sand});addBox(s,{x:58,z:11,w:12,h:6,d:13,color:stone});addBox(s,{x:35,z:-44,w:20,h:5,d:8,color:stone});addCrate(s,46,-31,3,dark);addCrate(s,52,-43,2.4,dark);
    // B tunnels
    addBox(s,{x:-50,z:-9,w:13,h:5,d:34,color:dark});addBox(s,{x:-35,z:13,w:16,h:4,d:8,color:stone});addBox(s,{x:-56,z:42,w:12,h:5,d:12,color:stone});addCrate(s,-43,33,3,dark);addCrate(s,-53,27,2.4,dark);
    // connector / short
    addBox(s,{x:28,z:21,w:14,h:4,d:7,color:sand});addBox(s,{x:-22,z:-34,w:18,h:4,d:7,color:sand});for(const [x,z] of [[23,-8],[32,39],[-25,43],[-8,47],[5,38],[-39,-45]])addCrate(s,x,z,2.6,dark);
  }
  function buildHarbor(s){s.spawns=[[-61,-51],[61,-50],[-60,51],[60,50],[-16,-61],[18,60],[-61,5],[61,7]].map(([x,z])=>new THREE.Vector3(x,0,z));addSite(s,'WAREHOUSE A',48,-35,0xffa94d);addSite(s,'DOCK B',-48,38,0x5cc8ff);addLabel(s,'CONTAINER MID',0,3,0,.72);
    // Warehouses
    addBox(s,{x:48,z:4,w:25,h:7,d:24,color:0x38434a});addBox(s,{x:-49,z:-5,w:22,h:7,d:25,color:0x303a42});
    // Container lanes
    const cols=[0x1f6b82,0x8a3f32,0x5a6d32,0x785e28];[[ -24,-36,0],[ -15,-23,Math.PI/2],[ -4,-36,0],[8,-22,Math.PI/2],[18,-38,0],[ -28,26,Math.PI/2],[-13,36,0],[2,26,Math.PI/2],[16,39,0],[29,27,Math.PI/2]].forEach((r,i)=>addContainer(s,r[0],r[1],r[2],cols[i%cols.length]));
    // Catwalk supports and central warehouse split
    addBox(s,{x:0,z:6,w:8,h:5,d:27,color:0x29353e});addBox(s,{x:0,z:-14,w:28,h:3.8,d:6,color:0x2b3740});for(const [x,z] of [[36,-42],[44,-26],[-39,43],[-55,29],[31,42],[-35,-40]])addCrate(s,x,z,2.7,0x73553a);
  }
  function buildMetro(s){s.spawns=[[-58,-52],[58,-52],[-58,52],[58,52],[-9,-59],[9,59],[-57,0],[57,0]].map(([x,z])=>new THREE.Vector3(x,0,z));addSite(s,'PLATFORM A',44,-40,0xffb45a);addSite(s,'SERVICE B',-44,40,0x70baff);addLabel(s,'CENTRAL HALL',0,3,0,.72);
    // platforms + rails
    addBox(s,{x:-19,z:0,w:11,h:.55,d:82,color:0x42494e,solid:true});addBox(s,{x:19,z:0,w:11,h:.55,d:82,color:0x42494e,solid:true});
    for(let z=-50;z<=50;z+=6){const a=new THREE.Mesh(new THREE.BoxGeometry(.16,.08,4.8),new THREE.MeshBasicMaterial({color:0x777b7d}));a.position.set(-7,.04,z);s.scene.add(a);const b=a.clone();b.position.x=7;s.scene.add(b);}addBox(s,{x:-7,z:0,w:.16,h:.08,d:118,color:0xa0a0a0,solid:false,shot:false});addBox(s,{x:7,z:0,w:.16,h:.08,d:118,color:0xa0a0a0,solid:false,shot:false});
    // halls / service corridors
    addBox(s,{x:0,z:-31,w:24,h:5,d:9,color:0x28323a});addBox(s,{x:0,z:31,w:24,h:5,d:9,color:0x28323a});addBox(s,{x:-44,z:0,w:12,h:5,d:34,color:0x252f37});addBox(s,{x:44,z:0,w:12,h:5,d:34,color:0x252f37});addBox(s,{x:-31,z:-47,w:17,h:5,d:8,color:0x303b43});addBox(s,{x:31,z:47,w:17,h:5,d:8,color:0x303b43});
    for(const [x,z] of [[-28,-18],[-29,18],[28,-17],[29,17],[-49,-35],[49,35]])addCrate(s,x,z,2.4,0x5b646a);
  }

  function randomSpawn(s){const list=s?.spawns?.length?s.spawns:DEFAULT_MAP_SPAWNS.map(([x,y,z])=>new THREE.Vector3(x,y,z));return list[Math.floor(Math.random()*list.length)].clone();}
  function openModePicker(s,mapId){const m=MAPS[mapId];if(!m)return;showModal(`<div class="eskl-modal-head"><div><small>MAP AUSWÄHLEN</small><h2>${esc(m.name)}</h2><p>${esc(m.subtitle)}</p></div><button data-modal-close>×</button></div><div class="eskl-mode-grid"><button data-play="online-dm"><b>🌐 Online Deathmatch</b><small>Dein normales Loadout · echte Spieler auf dieser Map</small></button><button data-play="online-gg"><b>🌐 Online Waffengame</b><small>Kill → nächste Waffe · gleiche Map/gleicher Modus</small></button><button data-play="bot-dm"><b>🤖 Bot Deathmatch</b><small>Training gegen ${BOT_COUNT} Bots</small></button><button data-play="bot-gg"><b>🔁 Bot Waffengame</b><small>Waffenleiter gegen Bots</small></button></div>`);UI.modal.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const v=b.dataset.play;closeModal();startCombat(mapId,v.includes('gg')?'gungame':'deathmatch',v.startsWith('online'));});}

  function bindWorldUi(s){
    UI.body.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>useConsumable(s,b.dataset.use));
    UI.body.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>setSlot(s,b.dataset.slot));
    UI.body.querySelector('[data-reload]')?.addEventListener('click',()=>beginReload(s));
    UI.body.querySelector('[data-interact]')?.addEventListener('click',()=>interact(s));
    UI.body.querySelector('[data-staff-mod]')?.addEventListener('click',()=>openStaffMenu(s));
    UI.body.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='jump')jumpPlayer(s);else if(b.dataset.action==='crouch')toggleStance(s);});
    UI.body.querySelectorAll('[data-touch]').forEach(b=>{const k=b.dataset.touch;const set=v=>{UI.touch[k]=v;if(k==='fire'){UI.mouse.down=v;if(!v)s.shotHeld=false;}if(k==='ads')UI.mouse.ads=v;};for(const ev of ['pointerdown','touchstart'])b.addEventListener(ev,e=>{e.preventDefault();set(true);},{passive:false});for(const ev of ['pointerup','pointercancel','touchend','touchcancel'])b.addEventListener(ev,e=>{e.preventDefault();set(false);},{passive:false});});
  }
  function bindTouchLook(s,canvas){let pointer=null,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target?.closest?.('button'))return;pointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;try{canvas.setPointerCapture(pointer);}catch{}},{passive:true});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||e.pointerType!=='touch'||UI.modal)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;s.yaw-=dx*.006;s.pitch=clamp(s.pitch-dy*.0048,-1.15,1.1);},{passive:true});const end=e=>{if(e.pointerId===pointer)pointer=null;};canvas.addEventListener('pointerup',end,{passive:true});canvas.addEventListener('pointercancel',end,{passive:true});}
  function resizeWorld(s){if(!s?.renderer||!s.wrap)return;const r=s.wrap.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);s.renderer.setSize(w,h,false);s.camera.aspect=w/h;s.camera.updateProjectionMatrix();}
  function onPointerLockChange(){const s=UI.session;if(!s)return;if(document.pointerLockElement!==s.renderer?.domElement){UI.mouse.down=false;UI.mouse.ads=false;s.shotHeld=false;for(const k of Object.keys(UI.keys))if(/^Key[WASD]$|^Arrow/.test(k))UI.keys[k]=false;}}

  function loop(s){if(UI.session!==s)return;s.timer.update();const dt=Math.min(.05,Math.max(.001,s.timer.getDelta?.()||.016));s.worldTime+=dt;s.fpWeapon?.userData?.mixer?.update?.(dt);s.fpArmsMixer?.update?.(dt);advanceWeaponAnimation(s,dt);updateMovement(s,dt);if(s.mode==='combat'&&!s.online)updateBots(s,dt);if(s.online){syncOnlineWrite(s,performance.now());updateRemoteLerp(s,dt);}updateShooting(s,performance.now());updateCamera(s,dt);updateLobbyPrompt(s);updateHud(s);s.renderer.render(s.scene,s.camera);s.raf=requestAnimationFrame(()=>loop(s));}
  function advanceWeaponAnimation(s,dt){s.weaponKick=Math.max(0,(Number(s.weaponKick)||0)-dt*7.5);s.meleeSwing=Math.max(0,(Number(s.meleeSwing)||0)-dt*4.7);}
  function forwardFromYaw(yaw,out=new THREE.Vector3()){return out.set(-Math.sin(yaw),0,-Math.cos(yaw));}
  function moveInput(){return {f:(UI.keys.KeyW||UI.keys.ArrowUp||UI.touch.forward?1:0)-(UI.keys.KeyS||UI.keys.ArrowDown||UI.touch.back?1:0),r:(UI.keys.KeyD||UI.keys.ArrowRight||UI.touch.right?1:0)-(UI.keys.KeyA||UI.keys.ArrowLeft||UI.touch.left?1:0),run:!!(UI.keys.ShiftLeft||UI.keys.ShiftRight||UI.touch.run)};}
  function collides(s,x,z){const b=s.bounds||{minX:-71,maxX:71,minZ:-71,maxZ:71};if(x<b.minX||x>b.maxX||z<b.minZ||z>b.maxZ)return true;return s.collision.some(c=>x>c.minX&&x<c.maxX&&z>c.minZ&&z<c.maxZ);}
  function tryMove(s,dx,dz){const nx=s.pos.x+dx,nz=s.pos.z+dz;if(collides(s,nx,nz))return false;s.pos.x=nx;s.pos.z=nz;return true;}
  function updateMovement(s,dt){if(!s.alive||UI.modal)return;const inp=moveInput(),boost=performance.now()<s.speedBoostUntil?1.55:1,stanceMult=s.stance==='crouch'?.58:1,running=inp.f>0&&inp.run&&s.stance==='stand',speed=(running?RUN_SPEED:WALK_SPEED)*s.staff.speed*boost*stanceMult,len=Math.max(1,Math.hypot(inp.f,inp.r)),f=inp.f/len,r=inp.r/len,fw=forwardFromYaw(s.yaw),rx=Math.cos(s.yaw),rz=-Math.sin(s.yaw),mx=fw.x*f+rx*r,mz=fw.z*f+rz*r,dx=mx*speed*dt,dz=mz*speed*dt,ox=s.pos.x,oz=s.pos.z;
    if(isStaff()&&s.staff.fly){s.pos.x+=dx;s.pos.z+=dz;if(UI.keys.Space)s.pos.y+=speed*dt;if(UI.keys.ControlLeft||UI.keys.ControlRight)s.pos.y-=speed*dt;s.pos.y=clamp(s.pos.y,.1,80);s.verticalVelocity=0;s.onGround=false;}else{tryMove(s,dx,0);tryMove(s,0,dz);s.verticalVelocity-=18*dt;s.pos.y+=s.verticalVelocity*dt;if(s.pos.y<=0){s.pos.y=0;s.verticalVelocity=0;s.onGround=true;}else s.onGround=false;}
    s.moving=Math.hypot(s.pos.x-ox,s.pos.z-oz)>.002;s.running=s.moving&&running;s.bodyYaw=s.yaw;
  }
  function toggleStance(s){if(!s?.alive||s.staff.fly)return;s.stance=s.stance==='crouch'?'stand':'crouch';updateHud(s,true);}
  function jumpPlayer(s){if(!s?.alive||s.staff.fly||!s.onGround)return;if(s.stance==='crouch')s.stance='stand';s.verticalVelocity=6.3;s.onGround=false;}
  function updateCamera(s,dt){const eye=s.stance==='crouch'?1.08:1.60;s.camera.position.set(s.pos.x,s.pos.y+eye,s.pos.z);s.camera.rotation.order='YXZ';s.camera.rotation.y=s.yaw;s.camera.rotation.x=s.pitch;s.camera.rotation.z=0;const targetFov=UI.mouse.ads?54:72;s.camera.fov+=(targetFov-s.camera.fov)*Math.min(1,dt*13);s.camera.updateProjectionMatrix();if(s.fpArms)s.fpArms.visible=!s.staff.vanish;updateFpPresentation(s,dt);}

  function thirdPersonWeaponSize(w){if(!w)return .62;if(w.type==='pistol')return .47;if(w.type==='smg')return .54;if(w.id==='knife')return .48;if(w.type==='melee')return .65;return .73;}
  function holsteredWeaponSize(w){return thirdPersonWeaponSize(w)*.86;}
  function anchorHeldWeapon(ch,g,w){if(!g||!w)return;g.rotation.set(0,0,0);if(w.type==='pistol'){g.position.set(.18,1.12,-.25);g.rotation.set(-.08,.02,.06);}else if(w.type==='melee'){g.position.set(.20,1.03,-.25);g.rotation.set(w.id==='knife'?.15:-.25,.05,-.18);}else{g.position.set(.13,1.12,-.38);g.rotation.set(-.08,.02,.03);}}
  function anchorHolsteredWeapon(ch,g,w){if(!g||!w)return;if(w.slot==='sidearm'){g.position.set(.31,.78,.05);g.rotation.set(-Math.PI/2,0,.06);}else if(w.id==='knife'){g.position.set(-.30,.78,.05);g.rotation.set(-Math.PI/2,0,.1);}else if(w.id==='katana'||w.id==='baseball'){g.position.set(-.12,1.14,.18);g.rotation.set(-1.0,0,-.55);}else{g.position.set(0,1.05,.20);g.rotation.set(-.9,0,.06);}}
  function updateHeldWeaponPose(ch){if(ch?.heldWeapon)anchorHeldWeapon(ch,ch.heldWeapon,ch.heldWeapon.userData.weapon);}
  function updateHolsteredWeaponPoses(ch){for(const g of ch?.holsteredWeapons||[])anchorHolsteredWeapon(ch,g,g.userData.weapon);}
  function clearRemoteWeapons(ch){if(!ch)return;for(const child of [...ch.root.children])if(child.userData?.remoteLoadout||child.userData?.activeWeapon)ch.root.remove(child);ch.heldWeapon=null;ch.holsteredWeapons=[];}
  async function attachActiveWeapon(ch,id){const w=WEAPON_MAP[id];if(!w)return;clearRemoteWeapons(ch);const m=await makeWeaponModel(id,thirdPersonWeaponSize(w)),g=new THREE.Group();g.userData.activeWeapon=true;g.userData.remoteLoadout=true;g.userData.esklWeapon=true;g.userData.weapon=w;g.add(m);ch.root.add(g);ch.heldWeapon=g;anchorHeldWeapon(ch,g,w);}
  async function rebuildRemoteLoadout(ch,loadout,activeSlot,key){ch.root.userData.remoteLoadoutKey=key;clearRemoteWeapons(ch);for(const slot of SLOT_ORDER){const id=loadout[slot],w=WEAPON_MAP[id];if(!w)continue;const active=slot===activeSlot,m=await makeWeaponModel(id,active?thirdPersonWeaponSize(w):holsteredWeaponSize(w));if(ch.root.userData.remoteLoadoutKey!==key)return;const g=new THREE.Group();g.userData.remoteLoadout=true;g.userData.esklWeapon=true;g.userData.weapon=w;g.add(m);ch.root.add(g);if(active){ch.heldWeapon=g;anchorHeldWeapon(ch,g,w);}else{ch.holsteredWeapons.push(g);anchorHolsteredWeapon(ch,g,w);}}}

  async function fpArmsTemplate(){if(fpArmsTemplatePromise)return fpArmsTemplatePromise;fpArmsTemplatePromise=loader.loadAsync(FP_ARMS_ASSET).catch(err=>{fpArmsTemplatePromise=null;console.warn('Egoshoot.KL First-Person-Arme konnten nicht geladen werden:',err);return null;});return fpArmsTemplatePromise;}
  function fpArmsIdleForWeapon(w){if(!w)return 'guard_idle';if(w.id==='knife')return 'knife_idle';if(w.type==='melee')return 'guard_idle';return 'finger_gun_idle';}
  function playFpArms(s,name,loop=true,fade=.08){if(!s?.fpArmsActions?.size)return false;const key=String(name||'').toLowerCase(),action=s.fpArmsActions.get(key);if(!action)return false;if(s.fpArmsAction===key&&loop)return true;for(const other of s.fpArmsActions.values())if(other!==action&&other.enabled)other.fadeOut?.(fade);action.reset();action.enabled=true;action.setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);action.clampWhenFinished=!loop;action.fadeIn?.(fade).play();s.fpArmsAction=key;return true;}
  async function ensureFpArms(s){if(!s||s.fpArms)return s?.fpArms||null;const build=++s.fpArmsBuildId,template=await fpArmsTemplate();if(!template?.scene||UI.session!==s||s.fpArmsBuildId!==build)return null;const raw=cloneSkeleton(template.scene);raw.traverse(o=>{if(o.isMesh||o.isSkinnedMesh){o.frustumCulled=false;o.renderOrder=996;for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m){m.depthTest=false;m.depthWrite=false;m.needsUpdate=true;}}});raw.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(raw),size=box.getSize(new THREE.Vector3()),scale=1.48/Math.max(.001,size.x,size.y,size.z);raw.scale.setScalar(scale);raw.rotation.y=Math.PI;raw.position.set(0,-.92,-.42);const group=new THREE.Group();group.name='egoshoot-first-person-arms';group.add(raw);s.camera.add(group);s.fpArms=group;s.fpArmsRaw=raw;s.fpArmsHand=raw.getObjectByName('hand.R_05')||raw.getObjectByName('handIK.R_049')||null;s.fpArmsMixer=new THREE.AnimationMixer(raw);s.fpArmsActions=new Map();for(const clip of template.animations||[]){const key=String(clip.name||'').replace(/^.*\|/,'').toLowerCase();s.fpArmsActions.set(key,s.fpArmsMixer.clipAction(clip));}playFpArms(s,fpArmsIdleForWeapon(WEAPON_MAP[activeWeaponId(s)]),true);return group;}
  function syncFpWeaponToHand(s,w){const g=s?.fpWeapon,hand=s?.fpArmsHand;if(!g||!hand)return false;hand.updateWorldMatrix?.(true,false);s.camera.updateWorldMatrix?.(true,false);const wp=new THREE.Vector3(),wq=new THREE.Quaternion(),cq=new THREE.Quaternion();hand.getWorldPosition(wp);hand.getWorldQuaternion(wq);s.camera.getWorldQuaternion(cq);const localPos=s.camera.worldToLocal(wp.clone()),localQ=cq.invert().multiply(wq),ahead=w?.type==='pistol'?.095:w?.type==='smg'?.12:w?.id==='knife'?.115:w?.type==='melee'?.14:.16;localPos.add(new THREE.Vector3(w?.id==='knife'?.015:0,ahead,0).applyQuaternion(localQ));const kick=Math.max(0,s.weaponKick||0),swing=Math.max(0,s.meleeSwing||0),phase=Math.sin((1-swing)*Math.PI);localPos.z+=kick*.035;if(w?.id==='knife')localPos.add(new THREE.Vector3(0,phase*.03,-phase*.20).applyQuaternion(localQ));g.position.lerp(localPos,.72);const grip=new THREE.Quaternion().setFromEuler(new THREE.Euler(Math.PI/2,w?.id==='knife'?.08:0,w?.type==='pistol'?.04:0)),targetQ=localQ.clone().multiply(grip);if(kick)targetQ.multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(kick*.16,0,0)));g.quaternion.slerp(targetQ,.76);return true;}
  function activeWeaponId(s){if(s?.gameMode==='gungame')return GUN_GAME_ORDER[clamp(Math.floor(s.gunLevel||0),0,GUN_GAME_ORDER.length-1)];return state().equipped[s?.currentSlot||'sidearm']||'glock';}
  function refreshFpArmsIdle(s){playFpArms(s,fpArmsIdleForWeapon(WEAPON_MAP[activeWeaponId(s)]),true);}
  async function updateFpWeapon(s){if(!s)return;const build=(s.fpBuildId||0)+1;s.fpBuildId=build;if(s.fpWeapon){s.camera.remove(s.fpWeapon);s.fpWeapon=null;}await ensureFpArms(s);const id=activeWeaponId(s),w=WEAPON_MAP[id];if(!w){refreshFpArmsIdle(s);return;}if(s.gameMode!=='gungame'&&!weaponState(id).owned){refreshFpArmsIdle(s);return;}const model=await makeWeaponModel(id,fpModelSize(w)*.88);if(UI.session!==s||s.fpBuildId!==build)return;const pose=fpPose(w),g=new THREE.Group();g.add(model);g.position.copy(pose.pos);g.rotation.copy(pose.rot);g.userData.basePos=pose.pos.clone();g.userData.adsPos=pose.ads.clone();g.userData.baseRot=pose.rot.clone();if(model.userData.esklAnimations?.length){g.userData.mixer=new THREE.AnimationMixer(model);const clip=model.userData.esklAnimations.find(a=>/shoot|fire/i.test(a.name||''))||model.userData.esklAnimations[0];if(clip){g.userData.shootAction=g.userData.mixer.clipAction(clip);g.userData.shootAction.setLoop(THREE.LoopOnce,1);g.userData.shootAction.clampWhenFinished=true;}}s.camera.add(g);s.fpWeapon=g;s.currentSlot=w.slot;s.ammo[id]=Number.isFinite(s.ammo[id])?s.ammo[id]:(w.mag||0);refreshFpArmsIdle(s);syncFpWeaponToHand(s,w);updateHud(s,true);}
  function updateFpPresentation(s,dt){const g=s.fpWeapon,w=WEAPON_MAP[activeWeaponId(s)];if(!g||!w)return;if(s.fpArmsHand&&syncFpWeaponToHand(s,w))return;const base=UI.mouse.ads?g.userData.adsPos:g.userData.basePos;if(!base)return;const kick=Math.max(0,s.weaponKick||0),swing=Math.max(0,s.meleeSwing||0),target=base.clone();target.z+=kick*(w.type==='pistol'?.105:.075);target.y+=kick*.02;if(swing){const ph=Math.sin((1-swing)*Math.PI);target.z-=ph*(w.id==='knife'?.34:.12);}g.position.lerp(target,Math.min(1,dt*18));const br=g.userData.baseRot||new THREE.Euler();g.rotation.x=br.x+kick*(w.type==='pistol'?.22:.12);g.rotation.y=br.y;g.rotation.z=br.z;}
  function setSlot(s,slot){if(s?.gameMode==='gungame'){toast('Im Waffengame bestimmt die Kill-Stufe deine Waffe.');return;}const id=state().equipped[slot];if(!SLOT_ORDER.includes(slot)||!id||!weaponState(id).owned)return;s.currentSlot=slot;s.reloadUntil=0;updateFpWeapon(s);updateHud(s,true);}

  function updateHud(s,force=false){const now=performance.now();if(!force&&now<s.hudNext)return;s.hudNext=now+80;const hpPct=clamp(s.hp/s.maxHp*100,0,100),shieldPct=s.maxShield?clamp(s.shield/s.maxShield*100,0,100):0;UI.body?.querySelector('[data-hp-bar]')?.style.setProperty('width',`${hpPct}%`);UI.body?.querySelector('[data-shield-bar]')?.style.setProperty('width',`${shieldPct}%`);const ht=UI.body?.querySelector('[data-hp-text]'),st=UI.body?.querySelector('[data-shield-text]');if(ht)ht.textContent=Math.ceil(s.hp);if(st)st.textContent=Math.ceil(s.shield);const id=activeWeaponId(s),w=id?weaponStats(id):null,wn=UI.body?.querySelector('[data-world-weapon]'),am=UI.body?.querySelector('[data-world-ammo]');if(wn)wn.textContent=w?.name||'-';if(am)am.textContent=w?(w.type==='melee'?'NAHKAMPF':`${s.ammo[id]??0}/${w.mag||0}${performance.now()<s.reloadUntil?' · LÄDT':''}`):'-';for(const iid of ['heal','speed','shield100','shield150','shield200']){const el=UI.body?.querySelector(`[data-count="${iid}"]`);if(el)el.textContent=fmt(state().inventory[iid]||0);}UI.body?.querySelectorAll('[data-slot]').forEach(b=>b.classList.toggle('active',s.gameMode!=='gungame'&&b.dataset.slot===s.currentSlot));const gg=UI.body?.querySelector('[data-gungame-box]');if(gg)gg.hidden=s.gameMode!=='gungame';const gl=UI.body?.querySelector('[data-gungame-level]');if(gl)gl.textContent=`${Math.min(GUN_GAME_ORDER.length,s.gunLevel+1)}/${GUN_GAME_ORDER.length} · ${s.matchKills} Kills`;const ml=UI.body?.querySelector('[data-mode-label]');if(ml)ml.textContent=s.mode==='lobby'?'TRAINING LOBBY':s.gameMode==='gungame'?'WAFFENGAME':'DEATHMATCH';const ol=UI.body?.querySelector('[data-online-label]');if(ol)ol.textContent=s.mode==='lobby'?'Schießen erlaubt · Treffer sind harmlos':s.online?`${Math.max(1,s.onlineCount||1)} Spieler · Online`:`${BOT_COUNT} Bots · Lokal`;}
  function updateLobbyPrompt(s){const p=UI.body?.querySelector('[data-world-prompt]');if(!p)return;if(s.mode!=='lobby'){s.nearPlace=null;p.textContent=s.gameMode==='gungame'?'Kill → nächste Waffe · R lädt · C duckt · SPACE springt · ESC Lobby':'WASD bewegen · R lädt · C duckt · SPACE springt · ESC Lobby';return;}let near=null;for(const place of Object.values(s.places||{}))if(Math.hypot(s.pos.x-place.x,s.pos.z-place.z)<place.radius){near=place;break;}s.nearPlace=near;p.textContent=near?.kind==='shop'?'E · Shop öffnen':near?.kind==='arsenal'?'E · Arsenal öffnen':near?.kind==='map'?`E · ${near.label.replace(' · E','')} auswählen`:'WASD · Maus zielen · Linksklick schießen · Trainingsziele verursachen keinen Schaden';}
  function interact(s){if(!s)return;if(s.mode!=='lobby')return;const p=s.nearPlace;if(!p)return;if(p.kind==='shop')openShop();else if(p.kind==='arsenal')openArsenal();else if(p.kind==='map')openModePicker(s,p.id);}
  function useConsumable(s,id){const inv=state().inventory;if(!s.alive||Number(inv[id]||0)<=0)return toast('Davon hast du nichts.','bad');if(id==='heal'){if(s.hp>=100)return toast('Leben ist bereits voll.');s.hp=Math.min(100,s.hp+60);}else if(id==='speed')s.speedBoostUntil=performance.now()+12000;else if(id.startsWith('shield')){const value=Number(id.replace('shield',''))||100;s.maxShield=value;s.shield=value;}else return;inv[id]--;persist();updateHud(s,true);toast('Benutzt.','good');}

  function showHitmarker(tone=''){const el=UI.body?.querySelector('[data-hitmarker]');if(!el)return;el.className=`eskl-hitmarker show ${tone}`;clearTimeout(el._t);el._t=setTimeout(()=>el.className='eskl-hitmarker',105);}
  function updateShooting(s,now){if(!s.alive||UI.modal)return;const id=activeWeaponId(s),base=WEAPON_MAP[id];if(!base)return;const w=s.gameMode==='gungame'?{...base,level:10,damage:base.damage*1.12,stability:Math.min(99,base.stability+8),rate:base.rate,durability:100}:weaponStats(id);if(s.mode!=='lobby'&&s.gameMode!=='gungame'&&w.durability<=0){if(UI.mouse.down&&now-s.lastShotAt>600){s.lastShotAt=now;toast(`${w.name} ist kaputt – im Shop reparieren.`,'bad');}return;}if(now<s.reloadUntil)return;if(w.type!=='melee'&&(s.ammo[id]??0)<=0){if(UI.mouse.down)beginReload(s,id);return;}if(!UI.mouse.down)return;if(now-s.lastShotAt<w.rate*1000)return;if((w.type==='pistol'||w.type==='sniper'||w.type==='shotgun')&&s.shotHeld)return;s.shotHeld=true;s.lastShotAt=now;fireWeapon(s,w);}
  function fireWeapon(s,w){const shoot=s.fpWeapon?.userData?.shootAction;if(shoot){shoot.reset();shoot.play();}const armsAttack=w.id==='knife'?(Math.random()<.5?'knife_hit_01':'knife_hit_02'):w.type==='melee'?'jab.r':'finger_gun_fire';playFpArms(s,armsAttack,false,.035);clearTimeout(s.fpArmsReturnTimer);s.fpArmsReturnTimer=setTimeout(()=>{if(UI.session===s)refreshFpArmsIdle(s);},w.id==='knife'?420:w.type==='melee'?360:180);if(w.type==='melee')s.meleeSwing=1;else s.weaponKick=1;if(w.type!=='melee')s.ammo[w.id]=Math.max(0,(s.ammo[w.id]??w.mag)-1);if(s.mode!=='lobby'&&s.gameMode!=='gungame'){weaponState(w.id).durability=clamp(weaponState(w.id).durability-w.durabilityLoss,0,100);persistSoon();}if(w.type==='melee')meleeAttack(s,w);else{for(let i=0;i<(w.pellets||1);i++)shootRay(s,w);muzzleFlash(s,w);}updateHud(s,true);}
  function shootRay(s,w){const spread=(100-w.stability)/100*(UI.mouse.ads?.006:.014)*(w.type==='shotgun'?3.8:1),x=(Math.random()-.5)*spread,y=(Math.random()-.5)*spread;s.raycaster||(s.raycaster=new THREE.Raycaster());s.raycaster.setFromCamera(new THREE.Vector2(x,y),s.camera);s.raycaster.far=w.range;const hits=s.raycaster.intersectObjects(s.shootables,true);for(const hit of hits){if(hit.object.userData?.practiceTarget){flashPracticeTarget(hit.object);showHitmarker('practice');return;}const meta=findTargetMeta(hit.object);if(hit.object.userData?.blockShot&&!meta){impactFx(s,hit.point);return;}if(meta){if(s.mode==='lobby'){showHitmarker('practice');return;}const head=meta.zone==='head',mult=head?(w.type==='sniper'?2.05:w.type==='pistol'?1.75:1.6):1,damage=Math.max(1,Math.round(w.damage*mult));applyOutgoingHit(s,meta,damage,false,head,w.id);showHitmarker(head?'head':'');return;}}}
  function flashPracticeTarget(obj){if(!obj?.material)return;const old=obj.material.emissive?.getHex?.()||0;obj.material.emissive?.setHex?.(0x36ff9d);setTimeout(()=>obj.material?.emissive?.setHex?.(old),130);}
  function impactFx(s,point){if(!point)return;const m=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),new THREE.MeshBasicMaterial({color:0xffd69a}));m.position.copy(point);s.scene.add(m);setTimeout(()=>s.scene?.remove(m),180);}
  function findTargetMeta(obj){let n=obj;while(n){if(n.userData?.esklTarget)return n.userData.esklTarget;n=n.parent;}return null;}
  function meleeAttack(s,w){if(s.mode==='lobby'){showHitmarker('practice');return;}const origin=s.pos.clone().add(new THREE.Vector3(0,1.15,0)),forward=forwardFromYaw(s.yaw);let best=null,dist=Infinity;for(const o of s.shootables){const meta=findTargetMeta(o);if(!meta)continue;const wp=new THREE.Vector3();o.getWorldPosition(wp);const d=origin.distanceTo(wp);if(d>w.range||d>=dist)continue;const dir=wp.clone().sub(origin).normalize();if(dir.dot(forward)<.55)continue;best=meta;dist=d;}if(best)applyOutgoingHit(s,best,w.damage,true,false,w.id);}
  function applyOutgoingHit(s,meta,damage,ignoreShield,headshot,weaponId){if(s.mode==='lobby')return;if(meta.kind==='bot'){const bot=s.bots.get(meta.id);if(bot)damageBot(s,bot,damage,ignoreShield,headshot,weaponId,true);}else if(meta.kind==='remote')sendOnlineHit(s,meta.id,damage,ignoreShield,headshot,weaponId);}
  function muzzleFlash(s){const l=new THREE.PointLight(0xffd37a,3,5,.8);l.position.copy(s.camera.position);s.scene.add(l);setTimeout(()=>s.scene?.remove(l),42);}
  function beginReload(s,id=activeWeaponId(s)){const w=WEAPON_MAP[id];if(!w?.mag||performance.now()<s.reloadUntil||(s.ammo[id]??0)>=w.mag)return;s.reloadUntil=performance.now()+w.reload*1000;updateHud(s,true);setTimeout(()=>{if(UI.session===s&&performance.now()+30>=s.reloadUntil){s.ammo[id]=w.mag;s.reloadUntil=0;updateHud(s,true);}},w.reload*1000);}

  function tagTarget(ch,id,kind){ch.head.userData.esklTarget={kind,id,zone:'head'};ch.body.userData.esklTarget={kind,id,zone:'body'};UI.session?.shootables.push(ch.head,ch.body);}
  async function createBots(s){for(let i=0;i<BOT_COUNT;i++){const gender=i%2?'woman':'man',ch=await makeCharacter(gender,`BOT ${i+1}`);if(UI.session!==s)return;const p=randomSpawn(s);p.x+=((i*7)%5)-2;p.z+=((i*11)%5)-2;ch.root.position.copy(p);s.scene.add(ch.root);const weapon=['glock','mini-uzi','m4','ak12','scar','shotgun'][i%6],bot={id:`bot-${i}`,ch,pos:p,yaw:Math.random()*Math.PI*2,hp:100,shield:i%3===0?100:0,maxShield:i%3===0?100:0,alive:true,weapon,lastDecision:0,lastShot:0,target:null,respawnAt:0};tagTarget(ch,bot.id,'bot');s.bots.set(bot.id,bot);await attachActiveWeapon(ch,weapon);}}
  function botHasLineOfSight(s,b){const origin=b.pos.clone().add(new THREE.Vector3(0,1.35,0)),tp=s.pos.clone().add(new THREE.Vector3(0,1.05,0)),dir=tp.clone().sub(origin),dist=dir.length();if(dist<=.01)return true;dir.normalize();const ray=new THREE.Raycaster(origin,dir,.05,dist),blockers=s.shootables.filter(o=>o?.userData?.blockShot),hit=ray.intersectObjects(blockers,true)[0];return !hit||hit.distance>=dist-.35;}
  function updateBots(s,dt){const now=performance.now();for(const b of s.bots.values()){if(!b.alive){if(now>b.respawnAt)respawnBot(s,b);continue;}updateCharacterAnimation(b.ch,dt);const vec=s.pos.clone().sub(b.pos),dist=vec.length();b.yaw=Math.atan2(-vec.x,-vec.z);if(dist>10){const step=Math.min(3.1*dt,Math.max(0,dist-8)),bf=forwardFromYaw(b.yaw),nx=b.pos.x+bf.x*step,nz=b.pos.z+bf.z*step;if(!collides(s,nx,nz)){b.pos.x=nx;b.pos.z=nz;setMotion(b.ch,'run');}else setMotion(b.ch,'idle');}else setMotion(b.ch,'idle');b.ch.root.position.copy(b.pos);b.ch.root.rotation.y=b.yaw;updateHeldWeaponPose(b.ch);if(s.alive&&dist<48&&now-b.lastShot>650+Math.random()*820&&botHasLineOfSight(s,b)){b.lastShot=now;const bw=WEAPON_MAP[b.weapon],dmg=bw.damage*(.58+Math.random()*.35);applyDamageToPlayer(s,Math.round(dmg),false,b.id,false,b.weapon);}}}
  function damageBot(s,b,damage,ignoreShield,headshot,weaponId,fromPlayer){if(!b?.alive)return;if(ignoreShield)b.hp-=damage;else{const take=Math.min(b.shield,damage);b.shield-=take;b.hp-=damage-take;}if(b.hp<=0){b.hp=0;b.alive=false;b.ch.root.visible=false;b.respawnAt=performance.now()+3200;if(fromPlayer)grantKill(s,'bot',headshot,weaponId);}}
  function respawnBot(s,b){b.pos.copy(randomSpawn(s));b.hp=100;b.shield=b.maxShield;b.alive=true;b.ch.root.visible=true;b.ch.root.position.copy(b.pos);}

  function applyDamageToPlayer(s,damage,ignoreShield,killerId,headshot,weaponId=''){if(s.mode==='lobby'||!s.alive||s.staff.god)return;if(ignoreShield)s.hp-=damage;else{const block=Math.min(s.shield,damage);s.shield-=block;s.hp-=damage-block;}if(s.hp<=0){s.hp=0;playerDied(s,killerId,headshot,weaponId);}updateHud(s,true);}
  function playerDied(s,killerId,headshot=false,weaponId=''){if(!s.alive)return;s.alive=false;state().deaths++;persist();if(s.online&&killerId&&killerId!==s.user?.uid)sendKillReward(s,killerId,headshot,weaponId);showDeath(s);}
  function grantKill(s,kind,headshot,weaponId){const st=state();st.totalKills++;st.killTokens++;if(headshot)st.headshots++;if(kind==='online')st.stats.onlineKills++;else st.stats.botKills++;s.streak=(s.streak||0)+1;s.matchKills=(s.matchKills||0)+1;st.stats.bestStreak=Math.max(st.stats.bestStreak||0,s.streak);if(s.gameMode==='gungame'){if(s.gunLevel>=GUN_GAME_ORDER.length-1){st.stats.gunGameWins=(st.stats.gunGameWins||0)+1;persist();toast('🏆 WAFFENGAME GEWONNEN! Waffenleiter startet neu.','good');s.gunLevel=0;s.matchKills=0;setTimeout(()=>{if(UI.session===s){for(const w of WEAPONS)s.ammo[w.id]=w.mag||0;updateFpWeapon(s);}},700);}else{s.gunLevel++;const nid=GUN_GAME_ORDER[s.gunLevel],nw=WEAPON_MAP[nid];s.currentSlot=nw.slot;s.ammo[nid]=nw.mag||0;s.reloadUntil=0;toast(`🔁 Nächste Waffe: ${nw.name}`,'good');updateFpWeapon(s);}}persist();refreshHeader();window.JKGamesAwardTopGameXp?.('egoshoot',8,'Egoshoot.KL Kill',{silent:true});if(s.gameMode!=='gungame')toast(`+1 Kill${headshot?' · HEADSHOT':''} · +1 Kill-Punkt`,'good');updateHud(s,true);}
  function showDeath(s){s.pointerLockBlocked=true;resetInputs();try{if(document.pointerLockElement)document.exitPointerLock?.();}catch{}const host=document.createElement('div');host.className='eskl-death';host.innerHTML=`<div><small>DU BIST AUSGESCHIEDEN</small><h2>Weiterkämpfen?</h2><p>Automatisch zur Lobby in <b data-death-count>8</b> Sekunden.</p><div><button data-death-respawn>Respawn</button><button data-death-lobby>Lobby</button></div></div>`;UI.body.append(host);let left=8;const timer=setInterval(()=>{left--;const el=host.querySelector('[data-death-count]');if(el)el.textContent=left;if(left<=0){clearInterval(timer);host.remove();startLobby();}},1000);host.querySelector('[data-death-respawn]').onclick=()=>{clearInterval(timer);host.remove();respawnPlayer(s);};host.querySelector('[data-death-lobby]').onclick=()=>{clearInterval(timer);host.remove();startLobby();};}
  function respawnPlayer(s){s.pos.copy(randomSpawn(s));s.hp=100;s.shield=0;s.maxShield=0;s.alive=true;s.streak=0;s.stance='stand';s.verticalVelocity=0;s.onGround=true;s.pointerLockBlocked=false;for(const w of WEAPONS)s.ammo[w.id]=w.mag||0;resetInputs();updateHud(s,true);}

  function loadoutForSession(s){if(s.gameMode!=='gungame'){const eq=state().equipped;return {melee:eq.melee||'knife',sidearm:eq.sidearm||'glock',long:eq.long||'',activeSlot:s.currentSlot,weaponId:activeWeaponId(s)};}const id=activeWeaponId(s),w=WEAPON_MAP[id],load={melee:'knife',sidearm:'glock',long:'',activeSlot:w.slot,weaponId:id};load[w.slot]=id;return load;}
  async function startOnline(s){const core=window.LifeBuilderFirebaseCore,fb=await core?.load?.(),user=await core?.waitForAuth?.(6500);if(!fb||!user||UI.session!==s)throw new Error('Firebase-Anmeldung fehlt.');s.fb=fb;s.user=user;s.displayName=String(user.displayName||user.email?.split('@')[0]||'Spieler').slice(0,48);const q=fb.query(fb.collection(fb.db,'egoshootKlOnline'),fb.orderBy('updatedAtMs','desc'),fb.limit(MAX_REMOTE));s.remoteUnsub=fb.onSnapshot(q,snap=>{if(UI.session!==s)return;const seen=new Set();snap.forEach(doc=>{if(doc.id===user.uid)return;const d=doc.data()||{};if(Date.now()-Number(d.updatedAtMs||0)>15000||d.vanish===true||d.mapId!==s.mapId||d.gameMode!==s.gameMode)return;seen.add(doc.id);upsertRemote(s,doc.id,d);});for(const id of [...s.remoteVisuals.keys()])if(!seen.has(id))removeRemote(s,id);s.onlineCount=seen.size+1;updateHud(s,true);},err=>{console.warn('Egoshoot.KL Online Listener',err);if(core?.isFatalFirestoreAssertion?.(err))core.scheduleHardFirestoreRecovery?.(err);});const hits=fb.collection(fb.db,'egoshootKlHits',user.uid,'events');s.hitUnsub=fb.onSnapshot(hits,snap=>{const remove=[];for(const ch of snap.docChanges()){if(ch.type!=='added'||s.seenHits.has(ch.doc.id))continue;s.seenHits.add(ch.doc.id);const d=ch.doc.data()||{};if(Date.now()-Number(d.createdAtMs||0)<30000)applyDamageToPlayer(s,Math.max(0,Number(d.damage)||0),d.ignoreShield===true,String(d.shooterUid||''),d.headshot===true,String(d.weaponId||''));remove.push(ch.doc.ref);}deleteEventRefs(fb,remove);},err=>console.warn('Egoshoot.KL Hit Listener',err));const rewards=fb.collection(fb.db,'egoshootKlRewards',user.uid,'events');s.rewardUnsub=fb.onSnapshot(rewards,snap=>{const remove=[];for(const ch of snap.docChanges()){if(ch.type!=='added'||s.seenRewards.has(ch.doc.id))continue;s.seenRewards.add(ch.doc.id);const d=ch.doc.data()||{};if(Date.now()-Number(d.createdAtMs||0)<60000)grantKill(s,'online',d.headshot===true,d.weaponId||'');remove.push(ch.doc.ref);}deleteEventRefs(fb,remove);},err=>console.warn('Egoshoot.KL Reward Listener',err));}
  function deleteEventRefs(fb,refs){if(!refs?.length)return;try{if(typeof fb.writeBatch==='function'){const batch=fb.writeBatch(fb.db);for(const ref of refs)batch.delete(ref);batch.commit().catch(()=>{});return;}}catch{}for(const ref of refs)fb.deleteDoc(ref).catch(()=>{});}
  async function upsertRemote(s,uid,d){let r=s.remoteVisuals.get(uid);if(!r){const ch=await makeCharacter(d.gender==='woman'?'woman':'man',d.displayName||'Spieler');if(UI.session!==s)return;s.scene.add(ch.root);r={ch,target:new THREE.Vector3(),yaw:0,data:{},loadoutKey:''};s.remoteVisuals.set(uid,r);tagTarget(ch,uid,'remote');}r.target.set(Number(d.x||0),Number(d.y||0),Number(d.z||0));r.yaw=Number(d.yaw||0);r.data=d;r.ch.root.visible=d.alive!==false;const key=[d.meleeId||'knife',d.sidearmId||'glock',d.longId||'',d.activeSlot||'sidearm',d.weaponId||''].join('|');if(r.loadoutKey!==key){r.loadoutKey=key;rebuildRemoteLoadout(r.ch,{melee:d.meleeId||'knife',sidearm:d.sidearmId||'glock',long:d.longId||''},d.activeSlot||'sidearm',key).catch(()=>{});}}
  function removeRemote(s,uid){const r=s.remoteVisuals.get(uid);if(r){s.scene.remove(r.ch.root);s.remoteVisuals.delete(uid);s.shootables=s.shootables.filter(o=>findTargetMeta(o)?.id!==uid);}}
  function updateRemoteLerp(s,dt){for(const r of s.remoteVisuals.values()){r.ch.root.position.lerp(r.target,1-Math.pow(.0005,dt));r.ch.root.rotation.y=r.yaw;const moving=Number(r.data.speed||0)>.2;setMotion(r.ch,moving?(Number(r.data.speed)>RUN_SPEED*.8?'run':'walk'):'idle');updateCharacterAnimation(r.ch,dt);updateHeldWeaponPose(r.ch);updateHolsteredWeaponPoses(r.ch);}}
  function syncOnlineWrite(s,now){if(!s.fb||!s.user||s.remoteWriteBusy)return;const lo=loadoutForSession(s),stable={uid:s.user.uid,displayName:s.displayName||'Spieler',gender:s.gender,x:Number(s.pos.x.toFixed(2)),y:Number(s.pos.y.toFixed(2)),z:Number(s.pos.z.toFixed(2)),yaw:Number(s.yaw.toFixed(4)),speed:Number((s.moving?(s.running?RUN_SPEED:WALK_SPEED)*s.staff.speed:0).toFixed(2)),weaponId:lo.weaponId,meleeId:lo.melee,sidearmId:lo.sidearm,longId:lo.long,activeSlot:lo.activeSlot,hp:Math.max(0,Math.round(s.hp)),shield:Math.max(0,Math.round(s.shield)),alive:!!s.alive,vanish:!!s.staff.vanish,flight:!!s.staff.fly,mapId:s.mapId,gameMode:s.gameMode},key=JSON.stringify(stable),changed=key!==s.lastRemoteKey,interval=changed?450:2800;if(now-s.lastRemoteWrite<interval)return;s.lastRemoteWrite=now;s.remoteWriteBusy=true;s.fb.setDoc(s.fb.doc(s.fb.db,'egoshootKlOnline',s.user.uid),{...stable,updatedAtMs:Date.now()},{merge:false}).then(()=>s.lastRemoteKey=key).catch(err=>{if(window.LifeBuilderFirebaseCore?.isFatalFirestoreAssertion?.(err))window.LifeBuilderFirebaseCore.scheduleHardFirestoreRecovery?.(err);}).finally(()=>s.remoteWriteBusy=false);}
  function sendOnlineHit(s,targetUid,damage,ignoreShield,headshot,weaponId){if(!s.fb||!s.user||targetUid===s.user.uid)return;const id=`${s.user.uid.slice(0,8)}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,ref=s.fb.doc(s.fb.db,'egoshootKlHits',targetUid,'events',id),data={shooterUid:s.user.uid,targetUid,damage:Math.min(9999,Math.max(1,Math.round(damage))),ignoreShield:!!ignoreShield,headshot:!!headshot,weaponId:String(weaponId||'').slice(0,32),createdAtMs:Date.now()};s.pendingHitWrites.push({ref,data});if(s.pendingHitWrites.length>=18)flushOnlineHitQueue(s);else if(!s.hitFlushTimer)s.hitFlushTimer=setTimeout(()=>{s.hitFlushTimer=0;flushOnlineHitQueue(s);},90);}
  function flushOnlineHitQueue(s){if(!s?.fb||!s.pendingHitWrites?.length)return;clearTimeout(s.hitFlushTimer);s.hitFlushTimer=0;const rows=s.pendingHitWrites.splice(0,18);try{if(typeof s.fb.writeBatch==='function'){const batch=s.fb.writeBatch(s.fb.db);for(const row of rows)batch.set(row.ref,row.data,{merge:false});batch.commit().catch(()=>{});return;}}catch{}Promise.allSettled(rows.map(row=>s.fb.setDoc(row.ref,row.data,{merge:false}))).catch(()=>{});}
  function sendKillReward(s,killerUid,headshot=false,weaponId=''){if(!s.fb||!s.user||!killerUid)return;const id=`${s.user.uid.slice(0,8)}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,ref=s.fb.doc(s.fb.db,'egoshootKlRewards',killerUid,'events',id);s.fb.setDoc(ref,{killerUid,victimUid:s.user.uid,headshot:!!headshot,weaponId:String(weaponId||'').slice(0,32),createdAtMs:Date.now()},{merge:false}).catch(()=>{});}

  function openStaffMenu(s){if(!isStaff())return;showModal(`<div class="eskl-modal-head"><div><small>OWNER / ADMIN</small><h2>Mod-Menü</h2></div><button data-modal-close>×</button></div><div class="eskl-mod-grid"><button data-mod="fly">Fliegen: <b>${s.staff.fly?'AN':'AUS'}</b></button><button data-mod="vanish">Vanish: <b>${s.staff.vanish?'AN':'AUS'}</b></button><button data-mod="god">Godmode: <b>${s.staff.god?'AN':'AUS'}</b></button><button data-mod="speed">Speed: <b>${s.staff.speed}×</b></button><button data-mod="weapons">Alle Waffen geben</button><button data-mod="heal">HP + Ultra Shield</button></div>`);UI.modal.querySelectorAll('[data-mod]').forEach(b=>b.onclick=()=>{const k=b.dataset.mod;if(k==='fly')s.staff.fly=!s.staff.fly;else if(k==='vanish')s.staff.vanish=!s.staff.vanish;else if(k==='god')s.staff.god=!s.staff.god;else if(k==='speed')s.staff.speed=s.staff.speed>=4?1:s.staff.speed*2;else if(k==='weapons'){for(const w of WEAPONS)state().weaponState[w.id]={owned:true,level:Math.max(1,weaponState(w.id).level),durability:100};persist();}else if(k==='heal'){s.hp=100;s.maxShield=200;s.shield=200;}closeModal();openStaffMenu(s);updateHud(s,true);});}

  function onKeyDown(e){if(!UI.overlay)return;UI.keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();const s=UI.session;if(!s||UI.modal)return;if(e.code==='Escape'){if(document.pointerLockElement)document.exitPointerLock?.();else if(s.mode==='combat')startLobby();}if(e.code==='KeyE'&&!e.repeat)interact(s);if(e.code==='Space'&&!e.repeat)jumpPlayer(s);if(e.code==='KeyC'&&!e.repeat)toggleStance(s);if(e.code==='Digit1')setSlot(s,'melee');if(e.code==='Digit2')setSlot(s,'sidearm');if(e.code==='Digit3')setSlot(s,'long');if(e.code==='KeyR'&&!e.repeat)beginReload(s);if(e.code==='KeyQ'&&!e.repeat&&isStaff())openStaffMenu(s);}
  function onKeyUp(e){UI.keys[e.code]=false;}
  function onMouseMove(e){const s=UI.session;if(!s||UI.modal)return;if(document.pointerLockElement===s.renderer?.domElement){s.yaw-=e.movementX*.0023;s.pitch=clamp(s.pitch-e.movementY*.0019,-1.15,1.1);}}
  function onMouseDown(e){const s=UI.session;if(!s||s.pointerLockBlocked||UI.modal||e.target?.closest?.('button'))return;if(e.button===0){UI.mouse.down=true;if(!document.pointerLockElement&&!isTouch())s.renderer.domElement.requestPointerLock?.();}if(e.button===2)UI.mouse.ads=true;}
  function onMouseUp(e){if(e.button===0){UI.mouse.down=false;if(UI.session)UI.session.shotHeld=false;}if(e.button===2)UI.mouse.ads=false;}
  function onContextMenu(e){if(UI.overlay)e.preventDefault();}

  function stopWorld(){const s=UI.session;if(!s)return;cancelAnimationFrame(s.raf);try{s.timer?.dispose?.();}catch{}flushOnlineHitQueue(s);try{s.remoteUnsub?.();s.hitUnsub?.();s.rewardUnsub?.();}catch{}clearTimeout(s.hitFlushTimer);clearTimeout(s.fpArmsReturnTimer);if(s.fpArms){try{s.camera?.remove?.(s.fpArms);}catch{}s.fpArms=null;s.fpArmsRaw=null;s.fpArmsHand=null;s.fpArmsMixer=null;s.fpArmsActions?.clear?.();}if(s.fb&&s.user)s.fb.deleteDoc(s.fb.doc(s.fb.db,'egoshootKlOnline',s.user.uid)).catch(()=>{});if(s.resize)window.removeEventListener('resize',s.resize);try{s.renderer?.dispose?.();s.renderer?.forceContextLoss?.();s.renderer?.domElement?.remove?.();}catch{}UI.session=null;resetInputs();}
  function grantJkCoinPurchase(kind,amount=1){if(kind!=='kills')return false;const n=Math.max(1,Math.floor(Number(amount)||1)),st=state();st.totalKills+=n;st.killTokens+=n;persist();refreshHeader();toast(`JK/Coin: +${n} Kills und Kill-Punkte`,'good');return true;}

  window.EgoShootKL=Object.freeze({version:VERSION,open,close,grantJkCoinPurchase,weapons:WEAPONS,maps:MAPS});
})();
