import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/addons/utils/SkeletonUtils.js';
import { EGOSHOOT_ASSETS } from './egoshoot-assets.js?v=20260808-egoshoot-assets-v249-bundle';

(() => {
  'use strict';

  const VERSION = '2026-08-08-egoshoot-kl-v261-third-person-controller-idle-rig-fix';
  const ASSET = 'assets/egoshoot-kl/';
  const STORAGE_KEY = 'jk-games-egoshoot-kl-v248';
  const MAX_REMOTE = 64;
  const WORLD_SIZE = 150;
  const WALK_SPEED = 4.8;
  const RUN_SPEED = 8.4;
  const BOT_COUNT = 10;

  const WEAPONS = [
    {id:'knife',name:'Messer Schwarz/Grau',file:'knife.glb',slot:'melee',type:'melee',starter:true,minKills:0,cost:0,damage:50,rate:.78,stability:100,range:2.25,durabilityLoss:.45,desc:'Nahkampf · ignoriert Shield · 2 Treffer auf 100 Leben.'},
    {id:'baseball',name:'Baseballschläger',file:'baseball-bat.glb',slot:'melee',type:'melee',minKills:25,cost:8,damage:50,rate:.92,stability:100,range:2.55,durabilityLoss:.5,desc:'Nahkampf · Rückenhalterung · ignoriert Shield.'},
    {id:'katana',name:'Katana-Schwert',file:'katana.glb',slot:'melee',type:'melee',minKills:60,cost:18,damage:50,rate:.62,stability:100,range:2.8,durabilityLoss:.35,desc:'Schneller Nahkampf · Rückenhalterung · ignoriert Shield.'},

    {id:'glock',name:'Glock',file:'glock.glb',slot:'sidearm',type:'pistol',starter:true,minKills:0,cost:0,damage:30,rate:.28,stability:88,mag:17,reload:1.45,range:105,durabilityLoss:.10,desc:'Starter-Pistole · präzise und zuverlässig.'},
    {id:'sand-pistol',name:'Pistole Grau/Sand',file:'sand-pistol.glb',slot:'sidearm',type:'pistol',minKills:15,cost:5,damage:34,rate:.31,stability:86,mag:14,reload:1.5,range:110,durabilityLoss:.11,desc:'Etwas stärker als die Glock.'},
    {id:'revolver',name:'Revolver',file:'revolver.glb',slot:'sidearm',type:'pistol',minKills:35,cost:10,damage:48,rate:.56,stability:82,mag:6,reload:1.8,range:120,durabilityLoss:.14,desc:'Langsam, aber hoher Einzelschaden.'},
    {id:'desert-eagle',name:'Desert Eagle',file:'desert-eagle.glb',slot:'sidearm',type:'pistol',minKills:60,cost:18,damage:56,rate:.5,stability:79,mag:7,reload:1.75,range:125,durabilityLoss:.15,desc:'Sehr schwere Pistole mit hoher Durchschlagskraft.'},
    {id:'mini-uzi',name:'Mini Uzi',file:'mini-uzi.glb',slot:'sidearm',type:'smg',minKills:100,cost:28,damage:17,rate:.085,stability:66,mag:28,reload:1.7,range:82,durabilityLoss:.075,desc:'Sehr schnell · niedriger Schaden pro Treffer.'},
    {id:'uzi',name:'Uzi',file:'uzi.glb',slot:'sidearm',type:'smg',minKills:130,cost:36,damage:19,rate:.09,stability:70,mag:32,reload:1.75,range:88,durabilityLoss:.075,desc:'Schnelle Maschinenpistole mit größerem Magazin.'},
    {id:'ump9',name:'UMP 9',file:'ump9.glb',slot:'sidearm',type:'smg',minKills:170,cost:48,damage:22,rate:.105,stability:76,mag:30,reload:1.8,range:96,durabilityLoss:.08,desc:'Stabilste Maschinenpistole.'},

    {id:'tommy',name:'Tommy Gun',file:'tommy-gun.glb',slot:'long',type:'rifle',minKills:210,cost:58,damage:27,rate:.115,stability:70,mag:40,reload:2.15,range:130,durabilityLoss:.08,desc:'Frühe Langwaffe mit großem Magazin.'},
    {id:'m4',name:'M4',file:'m4.glb',slot:'long',type:'rifle',minKills:260,cost:72,damage:32,rate:.105,stability:82,mag:30,reload:2.05,range:155,durabilityLoss:.075,desc:'Ausgewogenes Sturmgewehr.'},
    {id:'ak12',name:'AK-12',file:'ak12.glb',slot:'long',type:'rifle',minKills:320,cost:88,damage:35,rate:.11,stability:78,mag:30,reload:2.15,range:158,durabilityLoss:.08,desc:'Mehr Schaden, etwas mehr Rückstoß.'},
    {id:'an94',name:'AN-94',file:'an94.glb',slot:'long',type:'rifle',minKills:380,cost:105,damage:36,rate:.1,stability:81,mag:30,reload:2.15,range:165,durabilityLoss:.08,desc:'Schnelles, kontrollierbares Sturmgewehr.'},
    {id:'scar',name:'SCAR',file:'scar.glb',slot:'long',type:'rifle',minKills:450,cost:125,damage:39,rate:.12,stability:84,mag:30,reload:2.25,range:175,durabilityLoss:.085,desc:'Stark und sehr stabil.'},
    {id:'suppressed',name:'Sturmgewehr mit Schalldämpfer',file:'suppressed-rifle.glb',slot:'long',type:'rifle',minKills:520,cost:145,damage:37,rate:.1,stability:90,mag:30,reload:2.1,range:178,durabilityLoss:.075,desc:'Sehr präzise · reduzierte Mündungswirkung.'},
    {id:'ak47',name:'AK-47 Black Brown',file:'ak47-black-brown.glb',slot:'long',type:'rifle',minKills:600,cost:165,damage:43,rate:.125,stability:72,mag:30,reload:2.35,range:180,durabilityLoss:.09,desc:'Sehr hoher Sturmgewehr-Schaden.'},
    {id:'shotgun',name:'Shotgun',file:'shotgun.glb',slot:'long',type:'shotgun',minKills:700,cost:195,damage:13,rate:.82,stability:61,mag:8,reload:2.55,range:48,pellets:7,durabilityLoss:.16,desc:'7 Schrotkugeln · extrem stark auf kurze Distanz.'},
    {id:'barrett',name:'Sniper Barrett',file:'barrett.glb',slot:'long',type:'sniper',minKills:900,cost:250,damage:92,rate:1.25,stability:96,mag:5,reload:2.9,range:300,durabilityLoss:.18,desc:'Späte Sniper · Kopftreffer sind meist tödlich.'},
    {id:'raygun',name:'Raygun',file:'raygun.glb',slot:'long',type:'raygun',staffOnly:true,minKills:0,cost:0,damage:9999,rate:.32,stability:100,mag:99,reload:.7,range:320,durabilityLoss:0,desc:'OWNER/ADMIN · One-Shot-Spaßwaffe.'}
  ];
  const WEAPON_MAP = Object.fromEntries(WEAPONS.map(w => [w.id,w]));
  const SLOT_ORDER = ['melee','sidearm','long'];
  const UPGRADE_COSTS = [0,20,35,55,80,120,170,230,300,390];
  const SPAWNS = [
    new THREE.Vector3(-48,0,-48), new THREE.Vector3(48,0,-48),
    new THREE.Vector3(-48,0,48), new THREE.Vector3(48,0,48),
    new THREE.Vector3(0,0,-60), new THREE.Vector3(0,0,60)
  ];

  const loader = new GLTFLoader();
  const glbCache = new Map();
  const assetObjectUrls = new Map();
  const characterCache = new Map();
  const UI = { overlay:null, body:null, sourcePhone:'', session:null, keys:Object.create(null), mouse:{down:false,ads:false}, touch:{forward:false,back:false,left:false,right:false,fire:false,run:false}, modal:null, toastTimer:0 };
  let stateCache = null;
  let persistTimer = 0;

  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
  const lerpAngle=(a,b,t)=>{let d=(b-a+Math.PI)%(Math.PI*2)-Math.PI;if(d<-Math.PI)d+=Math.PI*2;return a+d*clamp(t,0,1);};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString('de-DE');
  const isTouch=()=>matchMedia('(pointer:coarse)').matches || innerWidth<760;
  const rootState=()=>window.JKGamesGetActiveState?.()||null;
  function roleKey(){return String(window.LifeBuilderSettingsMenu?.getRole?.()?.role||window.LifeBuilderSettingsMenu?.getRole?.()?.roleKey||'').toLowerCase();}
  function isStaff(){const r=roleKey();return r==='owner'||r==='admin'||!!window.LifeBuilderSettingsMenu?.isOwner?.();}

  function defaultState(){
    const weaponState={}; for(const w of WEAPONS) if(w.starter) weaponState[w.id]={owned:true,level:1,durability:100};
    if(isStaff()) weaponState.raygun={owned:true,level:10,durability:100};
    return {version:1,gender:'',totalKills:0,killTokens:0,deaths:0,headshots:0,weaponState,equipped:{melee:'knife',sidearm:'glock',long:''},inventory:{heal:0,speed:0,shield100:0,shield150:0,shield200:0},settings:{view:'fps'},stats:{onlineKills:0,botKills:0,bestStreak:0},lastMode:'lobby'};
  }
  function normalizeState(raw){
    const b=defaultState(),s=raw&&typeof raw==='object'?raw:{};
    b.gender=['man','woman'].includes(s.gender)?s.gender:'';
    b.totalKills=Math.max(0,Math.floor(Number(s.totalKills)||0));
    b.killTokens=Math.max(0,Math.floor(Number(s.killTokens)||0));
    b.deaths=Math.max(0,Math.floor(Number(s.deaths)||0));
    b.headshots=Math.max(0,Math.floor(Number(s.headshots)||0));
    b.weaponState={...b.weaponState};
    if(s.weaponState&&typeof s.weaponState==='object') for(const [id,v] of Object.entries(s.weaponState)){if(!WEAPON_MAP[id])continue;b.weaponState[id]={owned:!!v?.owned,level:clamp(Math.floor(v?.level||1),1,10),durability:clamp(v?.durability??100,0,100)};}
    if(isStaff()) b.weaponState.raygun={owned:true,level:10,durability:100};
    b.equipped={...b.equipped,...(s.equipped&&typeof s.equipped==='object'?s.equipped:{})};
    for(const slot of SLOT_ORDER){const id=b.equipped[slot];if(id&&(!WEAPON_MAP[id]||WEAPON_MAP[id].slot!==slot||!b.weaponState[id]?.owned||(WEAPON_MAP[id].staffOnly&&!isStaff())))b.equipped[slot]=slot==='melee'?'knife':slot==='sidearm'?'glock':'';}
    b.inventory={...b.inventory,...(s.inventory&&typeof s.inventory==='object'?s.inventory:{})};
    b.settings={...b.settings,...(s.settings&&typeof s.settings==='object'?s.settings:{})};
    b.stats={...b.stats,...(s.stats&&typeof s.stats==='object'?s.stats:{})};
    b.lastMode=String(s.lastMode||'lobby');
    return b;
  }
  function state(){const root=rootState();if(root){if(root.egoshootKL?.version!==1)root.egoshootKL=normalizeState(root.egoshootKL);if(isStaff()&&!root.egoshootKL.weaponState?.raygun)root.egoshootKL.weaponState.raygun={owned:true,level:10,durability:100};return root.egoshootKL;}if(stateCache?.version!==1){try{stateCache=normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'));}catch{stateCache=defaultState();}}if(isStaff()&&!stateCache.weaponState?.raygun)stateCache.weaponState.raygun={owned:true,level:10,durability:100};return stateCache;}
  function persist(){if(persistTimer){clearTimeout(persistTimer);persistTimer=0;}const s=state(),root=rootState();if(root){root.egoshootKL=s;window.JKGamesPersistState?.();}else try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}catch{};window.dispatchEvent(new CustomEvent('egoshoot-kl-state-changed',{detail:{kills:s.totalKills,tokens:s.killTokens,gender:s.gender}}));}
  function persistSoon(delay=1200){if(persistTimer)return;persistTimer=setTimeout(()=>{persistTimer=0;persist();},Math.max(250,Number(delay)||1200));}
  function weaponState(id){const s=state();if(!s.weaponState[id])s.weaponState[id]={owned:false,level:1,durability:100};return s.weaponState[id];}
  function weaponStats(id){const w=WEAPON_MAP[id]||WEAPON_MAP.glock,ws=weaponState(w.id),lvl=clamp(ws.level,1,10),damage=w.damage*(1+(lvl-1)*.04),stability=clamp(w.stability+(lvl-1)*2.1,0,99.5),rate=Math.max(.045,w.rate*(1-(lvl-1)*.012));return {...w,level:lvl,damage,stability,rate,durability:ws.durability};}

  function bundledAssetKey(url){return String(url||'').split(/[?#]/,1)[0].split('/').pop()||'';}
  function bundledAssetUrl(url){
    const key=bundledAssetKey(url),b64=EGOSHOOT_ASSETS[key];
    if(!b64)throw new Error(`Egoshoot.KL Asset fehlt im V249-Bundle: ${key||url}`);
    if(assetObjectUrls.has(key))return assetObjectUrls.get(key);
    const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
    const objectUrl=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'}));assetObjectUrls.set(key,objectUrl);return objectUrl;
  }
  function loadGLB(url){
    const key=bundledAssetKey(url);
    if(!glbCache.has(key))glbCache.set(key,new Promise((resolve,reject)=>{
      let source='';try{source=bundledAssetUrl(url);}catch(err){reject(err);return;}
      loader.load(source,g=>resolve(g),undefined,err=>reject(new Error(`Egoshoot.KL konnte ${key} nicht laden: ${String(err?.message||err)}`)));
    }));
    return glbCache.get(key);
  }
  async function characterTemplate(gender){
    if(characterCache.has(gender))return characterCache.get(gender);
    const p=(async()=>{const walk=await loadGLB(`${ASSET}${gender==='woman'?'woman-walk':'man-walk'}.glb`),run=await loadGLB(`${ASSET}${gender==='woman'?'woman-run':'man-run'}.glb`);return {walkScene:walk.scene,runScene:run.scene,walk:walk.animations?.[0]||null,run:run.animations?.[0]||null};})();
    characterCache.set(gender,p); return p;
  }
  function normalizeCharacter(scene){
    // Die gelieferten Mann/Frau-Rigs sind bereits Y-up. Die Mesh-Bind-Pose sieht in der
    // BoundingBox zwar liegend aus, die Bones stehen aber korrekt. Deshalb wird hier
    // KEINE 90-Grad-Korrektur mehr auf das gesamte Modell gelegt.
    const wrapper=new THREE.Group();wrapper.userData.esklCharacterWrapper=true;wrapper.add(scene);
    scene.position.set(0,0,0);scene.rotation.set(0,0,0);scene.scale.set(1,1,1);wrapper.updateMatrixWorld(true);

    // Groesse/Fussboden werden ueber das Skelett ermittelt, nicht ueber die ungepose-te
    // SkinnedMesh-BoundingBox. So bleibt die Figur dauerhaft hochkant und ca. 1,72 m gross.
    const bones=[];scene.traverse(o=>{if(o?.isBone||/^bip /i.test(String(o?.name||'')))bones.push(o);});
    const head=bones.find(o=>/^bip Head_/i.test(o.name))||bones.find(o=>/Head/i.test(o.name));
    const feet=bones.filter(o=>/^bip [LR] Foot_/i.test(o.name));
    const pelvis=bones.find(o=>/^bip Pelvis_/i.test(o.name));
    const wp=new THREE.Vector3(),headPos=new THREE.Vector3(),pelvisPos=new THREE.Vector3();
    if(head)head.getWorldPosition(headPos);
    if(pelvis)pelvis.getWorldPosition(pelvisPos);
    let floorY=Infinity;for(const foot of feet){foot.getWorldPosition(wp);floorY=Math.min(floorY,wp.y);}
    if(!Number.isFinite(floorY))floorY=0;
    const skeletonHeight=head?Math.max(.75,headPos.y-floorY+.20):1.72;
    const scale=clamp(1.72/skeletonHeight,.72,1.45);wrapper.scale.setScalar(scale);
    wrapper.position.set(-(pelvis?pelvisPos.x*scale:0),-floorY*scale,-(pelvis?pelvisPos.z*scale:0));
    wrapper.updateMatrixWorld(true);return wrapper;
  }
  function sanitizeCharacterClip(clip){
    if(!clip)return null;const c=clip.clone();
    // Nur echte In-Place-Bewegung: globale Export-Roots duerfen weder Position noch
    // Rotation der kompletten Figur veraendern. Arme, Beine, Oberkoerper usw. bleiben animiert.
    c.tracks=c.tracks.filter(track=>{
      const name=String(track.name||'');
      return !/(^|[./])(bip_01|bip Footsteps|RootNode|rig_CharRoot|_rootJoint)\.(position|quaternion|rotation|scale)$/i.test(name);
    });
    c.resetDuration?.();return c;
  }
  function buildStableIdleClip(walkClip){
    if(!walkClip?.tracks?.length)return null;
    // Der Export besitzt keine eigene Idle-Animation. Frame 0 der Laufdatei ist fuer
    // einige Skins jedoch keine gueltige zusammenhaengende Pose (Hüfte/Beine trennen sich).
    // Deshalb wird eine vollstaendige statische Pose aus zwei gegenueberliegenden,
    // gueltigen Gehphasen gemittelt. So bleiben ALLE Bones konsistent zueinander.
    const duration=Math.max(.001,Number(walkClip.duration)||1),ta=duration*.25,tb=duration*.75,tracks=[];
    for(const track of walkClip.tracks){
      try{
        const ia=track.createInterpolant(),ib=track.createInterpolant(),a=ia.evaluate(ta),b=ib.evaluate(tb);let values=[];
        if(track instanceof THREE.QuaternionKeyframeTrack){
          const qa=new THREE.Quaternion(a[0],a[1],a[2],a[3]),qb=new THREE.Quaternion(b[0],b[1],b[2],b[3]);if(qa.dot(qb)<0)qb.set(-qb.x,-qb.y,-qb.z,-qb.w);qa.slerp(qb,.5).normalize();values=[qa.x,qa.y,qa.z,qa.w];
        }else values=Array.from(a,(v,i)=>(Number(v)+Number(b[i]??v))*.5);
        tracks.push(new track.constructor(track.name,[0],values));
      }catch{}
    }
    return tracks.length?new THREE.AnimationClip('ESKL_StableIdle',1,tracks):null;
  }
  function normalizeWeapon(scene,target=.75){const box=new THREE.Box3().setFromObject(scene),size=new THREE.Vector3();box.getSize(size);const max=Math.max(size.x,size.y,size.z,.001),sc=target/max;scene.scale.setScalar(sc);box.setFromObject(scene);const c=new THREE.Vector3();box.getCenter(c);scene.position.sub(c);return scene;}
  function orientWeaponForward(scene,w){
    // Die meisten gelieferten Waffen zeigen in +X, einige in +/-Z. Fuer die Ego-Sicht
    // werden alle Modelle auf dieselbe Vorwaertsrichtung (-Z der Kamera) vereinheitlicht.
    const box=new THREE.Box3().setFromObject(scene),size=new THREE.Vector3();box.getSize(size);
    let yaw=0;if(size.x>size.z*1.18)yaw=Math.PI/2;
    else if(w?.id==='katana'||w?.id==='sand-pistol')yaw=Math.PI;
    else if(w?.id==='raygun')yaw=0;
    scene.rotation.y+=yaw;scene.userData.esklForwardYaw=yaw;scene.updateMatrixWorld(true);return scene;
  }
  function fpModelSize(w){if(!w)return .5;if(w.type==='pistol')return .46;if(w.type==='smg')return .55;if(w.type==='melee')return (w.id==='katana'||w.id==='baseball') ? .66 : .56;if(w.type==='raygun')return .68;return .72;}
  function fpPose(w){
    if(w.type==='melee')return {pos:new THREE.Vector3(.20,-.31,-.67),ads:new THREE.Vector3(.10,-.28,-.71),rot:new THREE.Euler(0,0,0,'XYZ')};
    if(w.type==='pistol')return {pos:new THREE.Vector3(.16,-.25,-.62),ads:new THREE.Vector3(0,-.215,-.66),rot:new THREE.Euler(0,0,0,'XYZ')};
    if(w.type==='smg')return {pos:new THREE.Vector3(.18,-.27,-.72),ads:new THREE.Vector3(0,-.225,-.76),rot:new THREE.Euler(0,0,0,'XYZ')};
    return {pos:new THREE.Vector3(.22,-.29,-.88),ads:new THREE.Vector3(0,-.235,-.91),rot:new THREE.Euler(0,0,0,'XYZ')};
  }
  async function makeCharacter(gender,label=''){
    const t=await characterTemplate(gender),walkVisual=normalizeCharacter(cloneSkeleton(t.walkScene)),runVisual=normalizeCharacter(cloneSkeleton(t.runScene));
    const root=new THREE.Group(),modelGroup=new THREE.Group();root.add(modelGroup);modelGroup.add(walkVisual,runVisual);
    // Die gelieferten Skins schauen in ihrer Modell-Datei genau entgegengesetzt zur
    // Spiel-Vorwaertsrichtung. Deshalb werden NUR die sichtbaren Rigs dauerhaft um 180°
    // gedreht. Der Controller/Root bleibt starr und teilt sich weiterhin exakt s.yaw.
    walkVisual.rotation.set(0,Math.PI,0);runVisual.rotation.set(0,Math.PI,0);runVisual.visible=false;
    const walkMixer=new THREE.AnimationMixer(walkVisual),runMixer=new THREE.AnimationMixer(runVisual),actions={},walkClip=sanitizeCharacterClip(t.walk),runClip=sanitizeCharacterClip(t.run),idleClip=buildStableIdleClip(walkClip);
    if(idleClip){actions.idle=walkMixer.clipAction(idleClip);actions.idle.play();actions.idle.setEffectiveWeight(1);}
    if(walkClip){actions.walk=walkMixer.clipAction(walkClip);actions.walk.play();actions.walk.setEffectiveWeight(0);actions.walk.timeScale=1;}
    if(runClip){actions.run=runMixer.clipAction(runClip);actions.run.play();actions.run.paused=true;actions.run.timeScale=1.05;}
    const head=new THREE.Mesh(new THREE.BoxGeometry(.34,.32,.32),new THREE.MeshBasicMaterial({visible:false}));head.position.set(0,1.59,0);head.userData.hitZone='head';root.add(head);
    const body=new THREE.Mesh(new THREE.BoxGeometry(.72,1.16,.5),new THREE.MeshBasicMaterial({visible:false}));body.position.set(0,.82,0);body.userData.hitZone='body';root.add(body);
    if(label){const sp=makeLabel(label);sp.position.y=2.15;root.add(sp);}
    const findRigBones=visual=>{const rig={};visual?.traverse?.(o=>{const n=String(o?.name||'');if(!(o?.isBone||/^bip /i.test(n)))return;if(/bip Pelvis|Pelvis/i.test(n))rig.pelvis=o;else if(/bip Spine1|Spine1|Chest/i.test(n))rig.spine1=o;else if(/bip Spine|Spine/i.test(n))rig.spine=o;else if(/bip L UpperArm|LeftUpperArm|L_UpperArm/i.test(n))rig.lUpper=o;else if(/bip L Forearm|LeftForearm|L_Forearm/i.test(n))rig.lFore=o;else if(/bip L Hand|LeftHand|L_Hand/i.test(n))rig.lHand=o;else if(/bip R UpperArm|RightUpperArm|R_UpperArm/i.test(n))rig.rUpper=o;else if(/bip R Forearm|RightForearm|R_Forearm/i.test(n))rig.rFore=o;else if(/bip R Hand|RightHand|R_Hand/i.test(n))rig.rHand=o;else if(/bip L Thigh|LeftThigh|L_Thigh/i.test(n))rig.lThigh=o;else if(/bip L Calf|LeftCalf|L_Calf/i.test(n))rig.lCalf=o;else if(/bip L Foot|LeftFoot|L_Foot/i.test(n))rig.lFoot=o;else if(/bip R Thigh|RightThigh|R_Thigh/i.test(n))rig.rThigh=o;else if(/bip R Calf|RightCalf|R_Calf/i.test(n))rig.rCalf=o;else if(/bip R Foot|RightFoot|R_Foot/i.test(n))rig.rFoot=o;});rig.rest={};for(const k of ['pelvis','spine','spine1','lUpper','lFore','lHand','rUpper','rFore','rHand','lThigh','lCalf','lFoot','rThigh','rCalf','rFoot']){const b=rig[k];if(b)rig.rest[k]={q:b.quaternion.clone(),p:b.position.clone()};}return rig;};
    const walkRig=findRigBones(walkVisual),runRig=findRigBones(runVisual);
    return {root,modelGroup,walkVisual,runVisual,walkMixer,runMixer,actions,motion:'',stance:'stand',idlePhase:Math.random()*Math.PI*2,head,body,walkRig,runRig,walkHand:walkRig.rHand,runHand:runRig.rHand,heldWeapon:null,holsteredWeapons:[]};
  }
  function setMotion(ch,motion){
    if(!ch||ch.motion===motion)return;ch.motion=motion;const running=motion==='run',walking=motion==='walk'||motion==='walk-back';ch.walkVisual.visible=!running;ch.runVisual.visible=running;
    if(ch.actions.idle){ch.actions.idle.enabled=true;ch.actions.idle.paused=false;ch.actions.idle.setEffectiveWeight(running||walking?0:1);}
    if(ch.actions.walk){ch.actions.walk.enabled=true;ch.actions.walk.paused=false;ch.actions.walk.setEffectiveWeight(walking?1:0);ch.actions.walk.timeScale=motion==='walk-back'?.78:1;}
    if(ch.actions.run){ch.actions.run.paused=!running;if(running)ch.actions.run.setEffectiveWeight(1);ch.actions.run.timeScale=1.05;}
  }
  function setCharacterStance(ch,stance='stand'){if(!ch)return;ch.stance=stance;const crouch=stance==='crouch',prone=stance==='prone';ch.head.position.set(0,prone?.43:crouch?1.08:1.59,prone?-.48:0);ch.body.position.set(0,prone?.35:crouch?.69:.82,prone?-.16:0);ch.head.scale.set(1,1,1);ch.body.scale.set(1,crouch?.82:prone?.50:1,prone?1.65:1);}
  function activeRig(ch){return ch?.runVisual?.visible?(ch.runRig||ch.walkRig):(ch?.walkRig||ch?.runRig);}
  function rootLocalToWorld(ch,x,y,z){const v=new THREE.Vector3(x,y,z);ch.root.updateMatrixWorld(true);return ch.root.localToWorld(v);}
  function restoreRigBone(rig,key,restorePosition=true){const b=rig?.[key],r=rig?.rest?.[key];if(!b||!r)return;if(restorePosition&&r.p)b.position.copy(r.p);if(r.q)b.quaternion.copy(r.q);}
  function aimBoneFromRest(rig,boneKey,childKey,targetWorld){const bone=rig?.[boneKey],child=rig?.[childKey],rest=rig?.rest?.[boneKey];if(!bone?.parent||!child||!rest?.q||!targetWorld)return false;bone.parent.updateMatrixWorld(true);const targetLocal=bone.parent.worldToLocal(targetWorld.clone()),dir=targetLocal.sub(bone.position);if(dir.lengthSq()<1e-8)return false;dir.normalize();const base=child.position.clone();if(base.lengthSq()<1e-8)return false;base.normalize().applyQuaternion(rest.q).normalize();const delta=new THREE.Quaternion().setFromUnitVectors(base,dir);bone.quaternion.copy(delta.multiply(rest.q));bone.updateMatrixWorld(true);return true;}
  function solveLimbFromRest(rig,upperKey,lowerKey,endKey,elbowWorld,endWorld){if(!rig)return false;restoreRigBone(rig,upperKey,false);restoreRigBone(rig,lowerKey,false);const a=aimBoneFromRest(rig,upperKey,lowerKey,elbowWorld);rig?.[upperKey]?.updateWorldMatrix?.(true,true);const b=aimBoneFromRest(rig,lowerKey,endKey,endWorld);return a&&b;}
  function updateCharacterAnimation(ch,dt){if(!ch)return;ch.walkMixer?.update?.(dt);ch.runMixer?.update?.(dt);const stance=ch.stance||'stand',prone=stance==='prone',crouch=stance==='crouch',ease=Math.min(1,dt*16),targetY=prone?.43:0,targetZ=prone?.16:0,targetX=prone?-Math.PI/2:0,targetScaleY=crouch?.84:1;ch.modelGroup.position.x=0;ch.modelGroup.position.y+=(targetY-ch.modelGroup.position.y)*ease;ch.modelGroup.position.z+=(targetZ-ch.modelGroup.position.z)*ease;ch.modelGroup.rotation.x+=(targetX-ch.modelGroup.rotation.x)*ease;ch.modelGroup.rotation.y=0;ch.modelGroup.rotation.z=0;ch.modelGroup.scale.x=1;ch.modelGroup.scale.z=1;ch.modelGroup.scale.y+=(targetScaleY-ch.modelGroup.scale.y)*ease;}

  function makeLabel(text){const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d');x.fillStyle='rgba(5,9,15,.82)';x.fillRect(4,12,504,72);x.fillStyle='#fff';x.font='700 29px system-ui';x.textAlign='center';x.fillText(String(text).slice(0,30),256,58);const tex=new THREE.CanvasTexture(c),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.scale.set(4.8,.9,1);return sp;}
  async function makeWeaponModel(id,target=.72){const w=WEAPON_MAP[id],g=await loadGLB(`${ASSET}${w.file}`),scene=orientWeaponForward(normalizeWeapon(cloneSkeleton(g.scene),target),w);scene.userData.esklAnimations=g.animations||[];scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return scene;}

  function open(sourcePhone=''){
    close(false);UI.sourcePhone=sourcePhone||window.JKGamesOwnedPhoneItem?.()||'';
    const overlay=document.createElement('div');overlay.className='eskl-overlay';overlay.dataset.egoshootKl='1';overlay.innerHTML=`<div class="eskl-shell"><header class="eskl-topbar"><div><small>JK.GAMES · TOP GAME</small><h1>Egoshoot.KL</h1></div><div class="eskl-stats"><span><small>KILLS</small><b data-eskl-kills>0</b></span><span><small>KILL-PUNKTE</small><b data-eskl-tokens>0</b></span></div><div class="eskl-actions"><button data-eskl-jk title="JK/Coin-Shop">JK</button><button data-eskl-arsenal>Arsenal</button><button data-eskl-shop>Shop</button><button data-eskl-info>i</button><button data-eskl-close>×</button></div></header><main class="eskl-body" data-eskl-body></main><div class="eskl-toast" data-eskl-toast></div></div>`;
    document.body.append(overlay);document.body.classList.add('egoshoot-kl-open');UI.overlay=overlay;UI.body=overlay.querySelector('[data-eskl-body]');
    overlay.querySelector('[data-eskl-close]').onclick=()=>close(true);
    overlay.querySelector('[data-eskl-jk]').onclick=()=>window.JKCoinApp?.openForGame?.('egoshoot');
    overlay.querySelector('[data-eskl-arsenal]').onclick=()=>UI.session?.mode==='lobby'?openArsenal():toast('Loadout kann nur in der Lobby geändert werden.','bad');
    overlay.querySelector('[data-eskl-shop]').onclick=()=>UI.session?.mode==='lobby'?openShop():toast('Der Shop ist nur in der Lobby verfügbar.','bad');
    overlay.querySelector('[data-eskl-info]').onclick=()=>openInfo();
    window.addEventListener('keydown',onKeyDown,{passive:false});window.addEventListener('keyup',onKeyUp,{passive:false});window.addEventListener('mousemove',onMouseMove,{passive:true});window.addEventListener('mousedown',onMouseDown,{passive:false});window.addEventListener('mouseup',onMouseUp,{passive:true});window.addEventListener('contextmenu',onContextMenu);
    refreshHeader();
    if(!state().gender)renderGenderChoice();else startLobby();
    setTimeout(()=>window.JKCoinApp?.applyPendingGameEntitlements?.(),500);
  }
  function close(returnTopGames=false){stopWorld();if(persistTimer)persist();closeModal();window.removeEventListener('keydown',onKeyDown);window.removeEventListener('keyup',onKeyUp);window.removeEventListener('mousemove',onMouseMove);window.removeEventListener('mousedown',onMouseDown);window.removeEventListener('mouseup',onMouseUp);window.removeEventListener('contextmenu',onContextMenu);try{document.exitPointerLock?.();}catch{}UI.overlay?.remove();UI.overlay=null;UI.body=null;document.body.classList.remove('egoshoot-kl-open');if(returnTopGames)setTimeout(()=>window.JKGamesOpenTopGames?.(UI.sourcePhone),80);}
  function refreshHeader(){if(!UI.overlay)return;UI.overlay.querySelector('[data-eskl-kills]').textContent=fmt(state().totalKills);UI.overlay.querySelector('[data-eskl-tokens]').textContent=fmt(state().killTokens);}
  function toast(message,tone=''){const el=UI.overlay?.querySelector('[data-eskl-toast]');if(!el)return;clearTimeout(UI.toastTimer);el.textContent=message;el.className=`eskl-toast show ${tone}`;UI.toastTimer=setTimeout(()=>el.className='eskl-toast',2600);}

  function renderGenderChoice(){stopWorld();UI.body.innerHTML=`<section class="eskl-choice"><small>CHARAKTER FESTLEGEN</small><h2>Wähle deinen Egoshoot.KL-Charakter</h2><p>Die Wahl wird in deinem normalen JK.Games-Spielstand gespeichert. Danach musst du sie nicht erneut auswählen.</p><div class="eskl-choice-grid"><button data-gender="man"><b>♂ Mann</b></button><button data-gender="woman"><b>♀ Frau</b></button></div></section>`;UI.body.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{state().gender=b.dataset.gender;persist();startLobby();});}

  function openInfo(){showModal(`<div class="eskl-modal-head"><div><small>SPIELINFO</small><h2>Egoshoot.KL</h2></div><button data-modal-close>×</button></div><div class="eskl-info-grid"><article><b>🎯 Kampf</b><p>Standard ist Ego-Perspektive. V wechselt zwischen Ego und Third Person. WASD bewegt relativ zur Kamera wie im 3D-Online-Game; in Third Person kann die Maus frei um den Charakter schauen und die Figur dreht sich automatisch in Laufrichtung. Linksklick schießt, Rechtsklick zielt, R lädt nach. SPACE springt, C duckt und Z legt den Charakter hin. 1/2/3 wechseln Nahkampf, Pistole/SMG und Langwaffe.</p></article><article><b>❤️ Leben & Shield</b><p>100 Leben. Shield gibt +100, +150 oder +200 blaue Schutzpunkte. Kugeln treffen zuerst Shield. Messer, Katana und Baseballschläger ignorieren Shield und benötigen zwei Treffer auf volle 100 Leben.</p></article><article><b>🌐 Online</b><p>Der Online-Teleport setzt dich zufällig an einen von mehreren Spawnpunkten. Andere eingeloggte Spieler sind sichtbar und können bekämpft werden.</p></article><article><b>🤖 Bot-Teleport</b><p>10 Bots kämpfen gegeneinander und gegen dich. Ideal zum Trainieren und Sammeln von Kills.</p></article><article><b>🛠 Waffen</b><p>Alle 20 Waffen besitzen Schaden, Stabilität, Feuerrate, Haltbarkeit und Level. Waffen können bis Level 10 verbessert und im Shop repariert werden.</p></article><article><b>🏆 Fortschritt</b><p>Kills schalten nach und nach neue Waffen frei. Waffen lassen sich bis Level 10 verbessern, müssen gepflegt und bei Bedarf repariert werden.</p></article></div>`);}

  function openShop(){const s=state();showModal(`<div class="eskl-modal-head"><div><small>LOBBY SHOP</small><h2>Waffen, Schutz & Versorgung</h2><p>${fmt(s.totalKills)} Kills · ${fmt(s.killTokens)} verfügbare Kill-Punkte</p></div><button data-modal-close>×</button></div><div class="eskl-shop-tabs"><button class="active" data-shop-tab="weapons">Waffen</button><button data-shop-tab="supply">Versorgung</button><button data-shop-tab="repair">Reparatur/Level</button></div><div data-shop-body></div>`);const render=()=>renderShopTab(UI.modal?.querySelector('.eskl-shop-tabs .active')?.dataset.shopTab||'weapons');UI.modal.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{UI.modal.querySelectorAll('[data-shop-tab]').forEach(x=>x.classList.toggle('active',x===b));renderShopTab(b.dataset.shopTab);});render();}
  function renderShopTab(tab){const host=UI.modal?.querySelector('[data-shop-body]');if(!host)return;const s=state();if(tab==='weapons')host.innerHTML=`<div class="eskl-shop-grid">${WEAPONS.filter(w=>!w.staffOnly||isStaff()).map(w=>{const ws=weaponState(w.id),locked=s.totalKills<w.minKills;return `<article class="${w.staffOnly?'staff':''}"><small>${w.slot.toUpperCase()} · ${w.type.toUpperCase()}</small><h3>${esc(w.name)}</h3><p>${esc(w.desc)}</p><div class="eskl-mini-stats"><span>DMG <b>${Math.round(weaponStats(w.id).damage)}</b></span><span>STAB <b>${Math.round(weaponStats(w.id).stability)}%</b></span><span>${w.type==='melee'?'TEMPO':'RPM'} <b>${w.type==='melee'?(1/weaponStats(w.id).rate).toFixed(1):Math.round(60/weaponStats(w.id).rate)}</b></span>${w.mag?`<span>MAG <b>${w.mag}</b></span>`:''}<span>LVL <b>${ws.level}/10</b></span></div>${ws.owned?`<button disabled>Besitzt du</button>`:locked?`<button disabled>🔒 ab ${fmt(w.minKills)} Kills</button>`:`<button data-buy-weapon="${w.id}">${w.cost} Kill-Punkte · kaufen</button>`}</article>`;}).join('')}</div>`;
    else if(tab==='supply')host.innerHTML=`<div class="eskl-shop-grid">${[{id:'heal',name:'Lebenstrank',cost:4,text:'+60 Leben im Kampf'},{id:'speed',name:'Speed-Trank',cost:6,text:'12 Sekunden deutlich schneller'},{id:'shield100',name:'Shield',cost:10,text:'+100 blaue Schutzpunkte'},{id:'shield150',name:'Verbesserter Shield',cost:18,text:'+150 blaue Schutzpunkte'},{id:'shield200',name:'Ultra-Shield',cost:30,text:'+200 blaue Schutzpunkte'}].map(x=>`<article><small>VERSORGUNG</small><h3>${x.name}</h3><p>${x.text}</p><button data-buy-supply="${x.id}" data-cost="${x.cost}">${x.cost} Kill-Punkte · kaufen</button></article>`).join('')}</div>`;
    else host.innerHTML=`<div class="eskl-shop-grid">${WEAPONS.filter(w=>weaponState(w.id).owned).map(w=>{const ws=weaponState(w.id),next=UPGRADE_COSTS[ws.level]||0,repair=Math.max(2,Math.ceil((100-ws.durability)/20)+ws.level);return `<article><small>${esc(w.name)}</small><h3>Level ${ws.level}/10</h3><p>Haltbarkeit: ${Math.round(ws.durability)}%</p><div class="eskl-row-buttons"><button data-repair="${w.id}" ${ws.durability>=99.9?'disabled':''}>Reparieren · ${repair}</button><button data-upgrade="${w.id}" ${ws.level>=10?'disabled':''}>${ws.level>=10?'MAX':'Level +1 · '+next}</button></div></article>`;}).join('')}</div>`;
    bindShopActions();}
  function bindShopActions(){UI.modal?.querySelectorAll('[data-buy-weapon]').forEach(b=>b.onclick=()=>{const w=WEAPON_MAP[b.dataset.buyWeapon],s=state();if(!w||s.totalKills<w.minKills||s.killTokens<w.cost)return toast('Noch nicht genug Kills/Kill-Punkte.','bad');s.killTokens-=w.cost;weaponState(w.id).owned=true;weaponState(w.id).durability=100;persist();refreshHeader();renderShopTab('weapons');toast(`${w.name} freigeschaltet.`,'good');});UI.modal?.querySelectorAll('[data-buy-supply]').forEach(b=>b.onclick=()=>{const s=state(),cost=Number(b.dataset.cost)||0,id=b.dataset.buySupply;if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;s.inventory[id]=Number(s.inventory[id]||0)+1;persist();refreshHeader();renderShopTab('supply');toast('Gekauft.','good');});UI.modal?.querySelectorAll('[data-repair]').forEach(b=>b.onclick=()=>{const id=b.dataset.repair,ws=weaponState(id),cost=Math.max(2,Math.ceil((100-ws.durability)/20)+ws.level),s=state();if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;ws.durability=100;persist();refreshHeader();renderShopTab('repair');});UI.modal?.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const id=b.dataset.upgrade,ws=weaponState(id),cost=UPGRADE_COSTS[ws.level]||99999,s=state();if(ws.level>=10)return;if(s.killTokens<cost)return toast('Nicht genug Kill-Punkte.','bad');s.killTokens-=cost;ws.level++;persist();refreshHeader();renderShopTab('repair');toast(`${WEAPON_MAP[id].name} ist jetzt Level ${ws.level}.`,'good');});}

  function openArsenal(){const s=state();showModal(`<div class="eskl-modal-head"><div><small>LOADOUT</small><h2>Waffenset bauen</h2><p>Genau eine Nahkampfwaffe, eine Pistole/SMG und eine Langwaffe.</p></div><button data-modal-close>×</button></div><div class="eskl-loadout">${SLOT_ORDER.map(slot=>`<section><h3>${slot==='melee'?'Nahkampf':slot==='sidearm'?'Pistole / Maschinenpistole':'Sturmgewehr / Shotgun / Sniper'}</h3><div>${WEAPONS.filter(w=>w.slot===slot&&weaponState(w.id).owned&&(!w.staffOnly||isStaff())).map(w=>`<button class="${s.equipped[slot]===w.id?'active':''}" data-equip="${w.id}"><b>${esc(w.name)}</b><small>Lvl ${weaponState(w.id).level} · ${Math.round(weaponState(w.id).durability)}%</small></button>`).join('')||'<p>Noch keine Waffe.</p>'}</div></section>`).join('')}</div>`);UI.modal.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const w=WEAPON_MAP[b.dataset.equip];if(!w)return;s.equipped[w.slot]=w.id;persist();closeModal();if(UI.session)rebuildLocalWeapons(UI.session);openArsenal();});}

  function showModal(html){closeModal();try{document.exitPointerLock?.();}catch{}const m=document.createElement('div');m.className='eskl-modal-wrap';m.innerHTML=`<div class="eskl-modal-card">${html}</div>`;document.body.append(m);UI.modal=m;m.querySelector('[data-modal-close]')?.addEventListener('click',closeModal);m.addEventListener('mousedown',e=>{if(e.target===m)closeModal();});return m;}
  function closeModal(){UI.modal?.remove();UI.modal=null;}

  async function startLobby(){await startWorld('lobby');}
  async function startCombat(mode){await startWorld(mode);}
  function worldHtml(mode){return `<div class="eskl-world"><div class="eskl-canvas" data-eskl-canvas></div><div class="eskl-hud"><div class="eskl-bars"><label>HP <span data-hp-text>100</span><i><em class="hp" data-hp-bar></em></i></label><label>SHIELD <span data-shield-text>0</span><i><em class="shield" data-shield-bar></em></i></label></div><div class="eskl-combat-stats"><span><small>${mode==='lobby'?'LOBBY':'KILLS'}</small><b data-world-kills>${fmt(state().totalKills)}</b></span><span><small>WAFFE</small><b data-world-weapon>-</b></span><span><small>HALTBARKEIT</small><b data-world-dura>-</b></span></div><div class="eskl-crosshair" data-crosshair><i></i><i></i></div><div class="eskl-prompt" data-world-prompt></div><div class="eskl-ammo" data-world-ammo></div><div class="eskl-slotbar"><button data-slot="melee">1 · Nah</button><button data-slot="sidearm">2 · Side</button><button data-slot="long">3 · Long</button><button data-reload>R</button><button data-view-toggle>V</button><button data-stance="crouch">C · Ducken</button><button data-stance="prone">Z · Liegen</button><button data-jump>SPACE · Sprung</button><button data-interact>E</button></div><div class="eskl-consumables"><button data-use="heal">❤️ <b data-count="heal">0</b></button><button data-use="speed">⚡ <b data-count="speed">0</b></button><button data-use="shield100">🛡100 <b data-count="shield100">0</b></button><button data-use="shield150">🛡150 <b data-count="shield150">0</b></button><button data-use="shield200">🛡200 <b data-count="shield200">0</b></button>${isStaff()?'<button class="staff" data-staff-mod>◆ MOD</button>':''}</div><div class="eskl-touch"><div class="move"><button data-touch="forward">▲</button><button data-touch="left">◀</button><button data-touch="back">▼</button><button data-touch="right">▶</button></div><div class="combat"><button data-touch="run">RUN</button><button data-action="crouch">DUCK</button><button data-action="jump">JUMP</button><button data-touch="ads">ADS</button><button class="fire" data-touch="fire">FIRE</button></div></div></div></div>`;}

  async function startWorld(mode){
    stopWorld();closeModal();state().lastMode=mode;persist();UI.body.innerHTML=worldHtml(mode);
    const wrap=UI.body.querySelector('[data-eskl-canvas]'),scene=new THREE.Scene();scene.background=new THREE.Color(mode==='lobby'?0x07131a:0x071019);scene.fog=new THREE.FogExp2(scene.background,mode==='lobby'?.008:.0065);
    const camera=new THREE.PerspectiveCamera(72,1,.05,450),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});scene.add(camera);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;wrap.append(renderer.domElement);
    scene.add(new THREE.HemisphereLight(0xbfe5ff,0x12251e,2.1));const sun=new THREE.DirectionalLight(0xfff1cf,3.2);sun.position.set(35,60,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
    const timer=new THREE.Timer();try{timer.connect(document);}catch{}timer.update();
    const s={mode,scene,camera,renderer,timer,wrap,player:null,gender:state().gender,pos:new THREE.Vector3(),yaw:0,bodyYaw:0,pitch:0,view:String(state().settings.view||'fps'),velocity:new THREE.Vector3(),moving:false,running:false,hp:100,maxHp:100,shield:0,maxShield:0,alive:true,currentSlot:'sidearm',ammo:{},reloadUntil:0,lastShotAt:0,speedBoostUntil:0,collision:[],shootables:[],worldObjects:[],bots:new Map(),remote:new Map(),remoteVisuals:new Map(),remoteWriteBusy:false,lastRemoteWrite:0,lastRemoteKey:'',seenHits:new Set(),seenRewards:new Set(),pendingHitWrites:[],hitFlushTimer:0,staff:{fly:false,vanish:false,god:false,speed:1},raf:0,worldTime:0,streak:0,weaponKick:0,meleeSwing:0,stance:'stand',verticalVelocity:0,onGround:true,pointerLockBlocked:false};UI.session=s;
    for(const w of WEAPONS)s.ammo[w.id]=w.mag||0;
    createBaseMap(s);if(mode==='lobby')createLobbyPlaces(s);else createCombatPlaces(s);
    const spawn=mode==='lobby'?new THREE.Vector3(0,0,28):randomSpawn();s.pos.copy(spawn);s.player=await makeCharacter(s.gender);if(UI.session!==s)return;s.bodyYaw=s.yaw;s.player.root.position.copy(s.pos);s.player.root.rotation.y=s.bodyYaw;scene.add(s.player.root);await rebuildLocalWeapons(s);
    if(mode==='bots')createBots(s);if(mode==='online')startOnline(s).catch(err=>toast(`Online nicht verfügbar: ${String(err?.message||err).slice(0,80)}`,'bad'));
    bindWorldUi(s);resizeWorld(s);window.addEventListener('resize',s.resize=()=>resizeWorld(s));renderer.domElement.addEventListener('click',()=>{if(!isTouch()&&!document.pointerLockElement&&!s.pointerLockBlocked&&!UI.modal)renderer.domElement.requestPointerLock?.();});bindTouchLook(s,renderer.domElement);
    updateHud(s);s.raf=requestAnimationFrame(t=>loop(s,t));
  }

  function createBaseMap(s){const ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD_SIZE,WORLD_SIZE),new THREE.MeshStandardMaterial({color:s.mode==='lobby'?0x18352b:0x14251f,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;s.scene.add(ground);const roadMat=new THREE.MeshStandardMaterial({color:0x18202a,roughness:.9});[-45,0,45].forEach(v=>{const a=new THREE.Mesh(new THREE.BoxGeometry(12,.04,WORLD_SIZE-4),roadMat);a.position.set(v,.02,0);s.scene.add(a);const b=new THREE.Mesh(new THREE.BoxGeometry(WORLD_SIZE-4,.04,12),roadMat);b.position.set(0,.025,v);s.scene.add(b);});const lineMat=new THREE.MeshBasicMaterial({color:0xf3d98f});for(let p=-65;p<=65;p+=10){for(const x of [-45,0,45]){const line=new THREE.Mesh(new THREE.BoxGeometry(.12,.025,4),lineMat);line.position.set(x,.06,p);s.scene.add(line);}for(const z of [-45,0,45]){const line=new THREE.Mesh(new THREE.BoxGeometry(4,.025,.12),lineMat);line.position.set(p,.061,z);s.scene.add(line);}}
    const mats=[0x263749,0x313d35,0x3e3144,0x49362f,0x24424a].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.85}));let idx=0;for(let gx=-2;gx<=2;gx++)for(let gz=-2;gz<=2;gz++){const x=gx*27,z=gz*27;if(Math.abs(x%45)<10||Math.abs(z%45)<10)continue;const w=9+(idx%3)*2,d=9+((idx+1)%3)*2,h=6+(idx%5)*2;addBuilding(s,x,z,w,h,d,mats[idx++%mats.length]);}
    const coverMat=new THREE.MeshStandardMaterial({color:0x47505b,roughness:.8});for(let i=0;i<18;i++){const x=((i*37)%116)-58,z=((i*61)%116)-58;if(Math.abs(x)<8||Math.abs(z)<8)continue;const c=new THREE.Mesh(new THREE.BoxGeometry(3+(i%3),1.4+(i%2),2.4),coverMat);c.position.set(x,c.geometry.parameters.height/2,z);c.castShadow=true;s.scene.add(c);addCollider(s,c.position.x,c.position.z,c.geometry.parameters.width,c.geometry.parameters.depth,c);}
    const wallMat=new THREE.MeshStandardMaterial({color:0x431d2b,emissive:0x21040b,emissiveIntensity:.5});[[0,-75,150,2],[0,75,150,2],[-75,0,2,150],[75,0,2,150]].forEach(([x,z,w,d])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,4,d),wallMat);m.position.set(x,2,z);s.scene.add(m);addCollider(s,x,z,w,d,m);});}
  function addBuilding(s,x,z,w,h,d,mat){const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);b.position.set(x,h/2,z);b.castShadow=true;b.receiveShadow=true;s.scene.add(b);addCollider(s,x,z,w,d,b);for(let yy=2;yy<h-1;yy+=2.5){const win=new THREE.Mesh(new THREE.PlaneGeometry(.9,.65),new THREE.MeshBasicMaterial({color:0x8bd6ff}));win.position.set(x+w/2+.006,yy,z);win.rotation.y=Math.PI/2;s.scene.add(win);}}
  function addCollider(s,x,z,w,d,mesh){s.collision.push({minX:x-w/2-.35,maxX:x+w/2+.35,minZ:z-d/2-.35,maxZ:z+d/2+.35});if(mesh){mesh.userData.blockShot=true;s.shootables.push(mesh);}}
  function addPlace(s,id,x,z,color,label){const ring=new THREE.Mesh(new THREE.RingGeometry(4.2,5.4,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.62,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.06,z);s.scene.add(ring);const p=new THREE.PointLight(color,3,18);p.position.set(x,3.5,z);s.scene.add(p);const sp=makeLabel(label);sp.position.set(x,3.1,z);s.scene.add(sp);s[`place_${id}`]={x,z,radius:6,label};}
  function createLobbyPlaces(s){addPlace(s,'shop',-26,-28,0x64e0b6,'SHOP · E');addPlace(s,'online',0,-32,0x54a8ff,'ONLINE TELEPORT · E');addPlace(s,'bots',26,-28,0xffb65e,'BOT TELEPORT · E');addPlace(s,'safe',0,20,0x7a69ff,'SAFE LOBBY');}
  function createCombatPlaces(s){for(const [i,p] of SPAWNS.entries()){const ring=new THREE.Mesh(new THREE.RingGeometry(1.5,2,24),new THREE.MeshBasicMaterial({color:0x57a9ff,transparent:true,opacity:.25,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.copy(p).setY(.04);s.scene.add(ring);}}
  function randomSpawn(){return SPAWNS[Math.floor(Math.random()*SPAWNS.length)].clone();}

  function bindWorldUi(s){UI.body.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>useConsumable(s,b.dataset.use));UI.body.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>setSlot(s,b.dataset.slot));UI.body.querySelector('[data-reload]')?.addEventListener('click',()=>beginReload(s));UI.body.querySelector('[data-interact]')?.addEventListener('click',()=>interact(s));UI.body.querySelector('[data-view-toggle]')?.addEventListener('click',()=>{s.view=s.view==='fps'?'third':'fps';state().settings.view=s.view;persist();updateFpWeapon(s);});UI.body.querySelectorAll('[data-stance]').forEach(b=>b.onclick=()=>toggleStance(s,b.dataset.stance));UI.body.querySelector('[data-jump]')?.addEventListener('click',()=>jumpPlayer(s));UI.body.querySelector('[data-staff-mod]')?.addEventListener('click',()=>openStaffMenu(s));UI.body.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='jump')jumpPlayer(s);else if(b.dataset.action==='crouch')toggleStance(s,'crouch');});UI.body.querySelectorAll('[data-touch]').forEach(b=>{const k=b.dataset.touch;const set=v=>{UI.touch[k]=v;if(k==='fire'){UI.mouse.down=v;if(!v)s.shotHeld=false;}if(k==='ads')UI.mouse.ads=v;};for(const ev of ['pointerdown','touchstart'])b.addEventListener(ev,e=>{e.preventDefault();set(true);},{passive:false});for(const ev of ['pointerup','pointercancel','touchend','touchcancel'])b.addEventListener(ev,e=>{e.preventDefault();set(false);},{passive:false});});}
  function bindTouchLook(s,canvas){let pointer=null,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;pointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;try{canvas.setPointerCapture(pointer);}catch{}},{passive:true});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||e.pointerType!=='touch')return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;s.yaw-=dx*.006;s.pitch=clamp(s.pitch-dy*.0048,-1.15,1.1);},{passive:true});const end=e=>{if(e.pointerId===pointer)pointer=null;};canvas.addEventListener('pointerup',end,{passive:true});canvas.addEventListener('pointercancel',end,{passive:true});}
  function resizeWorld(s){if(!s?.renderer||!s.wrap)return;const r=s.wrap.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);s.renderer.setSize(w,h,false);s.camera.aspect=w/h;s.camera.updateProjectionMatrix();}

  function loop(s,t){if(UI.session!==s)return;s.timer.update(t);const dt=Math.min(.05,s.timer.getDelta());s.worldTime+=dt;s.fpWeapon?.userData?.mixer?.update?.(dt);advanceWeaponAnimation(s,dt);updateMovement(s,dt);updateCharacter(s,dt);if(s.mode==='bots')updateBots(s,dt);if(s.mode==='online'){syncOnlineWrite(s,performance.now());updateRemoteLerp(s,dt);}updateShooting(s,performance.now());updateCamera(s,dt);updateLobbyPrompt(s);updateHud(s);s.renderer.render(s.scene,s.camera);s.raf=requestAnimationFrame(n=>loop(s,n));}
  function advanceWeaponAnimation(s,dt){s.weaponKick=Math.max(0,(Number(s.weaponKick)||0)-dt*7.5);s.meleeSwing=Math.max(0,(Number(s.meleeSwing)||0)-dt*4.7);}
  function forwardFromYaw(yaw,out=new THREE.Vector3()){return out.set(-Math.sin(yaw),0,-Math.cos(yaw));}
  function moveInput(){return {f:(UI.keys.KeyW||UI.keys.ArrowUp||UI.touch.forward?1:0)-(UI.keys.KeyS||UI.keys.ArrowDown||UI.touch.back?1:0),r:(UI.keys.KeyD||UI.keys.ArrowRight||UI.touch.right?1:0)-(UI.keys.KeyA||UI.keys.ArrowLeft||UI.touch.left?1:0),run:!!(UI.keys.ShiftLeft||UI.keys.ShiftRight||UI.touch.run)};}
  function updateMovement(s,dt){if(!s.alive)return;const inp=moveInput(),staffSpeed=isStaff()?s.staff.speed:1,boost=performance.now()<s.speedBoostUntil?1.55:1,stanceMult=s.stance==='prone'?.28:s.stance==='crouch'?.56:1,canRun=s.stance==='stand',runningForward=inp.f>0&&inp.run&&canRun,speed=(runningForward?RUN_SPEED:WALK_SPEED)*staffSpeed*boost*stanceMult;
    // Gleiche Steuerlogik wie im 3D-Online-Game: Die Maus steuert nur die Kamera.
    // WASD bewegt relativ zur Kamerarichtung; die sichtbare Figur dreht weich in die
    // tatsaechliche Bewegungsrichtung. Dadurch kann man in Third Person frei um sie schauen.
    const len=Math.hypot(inp.f,inp.r)||1,f=inp.f/Math.max(1,len),r=inp.r/Math.max(1,len),forward=forwardFromYaw(s.yaw),rightX=Math.cos(s.yaw),rightZ=-Math.sin(s.yaw),moveX=forward.x*f+rightX*r,moveZ=forward.z*f+rightZ*r,dx=moveX*speed*dt,dz=moveZ*speed*dt,old=s.pos.clone();
    if(isStaff()&&s.staff.fly){s.pos.x+=dx;s.pos.z+=dz;if(UI.keys.Space)s.pos.y+=speed*dt;if(UI.keys.ControlLeft||UI.keys.ControlRight)s.pos.y-=speed*dt;s.pos.y=clamp(s.pos.y,.1,80);s.verticalVelocity=0;s.onGround=false;}else{tryMove(s,dx,0);tryMove(s,0,dz);s.verticalVelocity-=17.5*dt;s.pos.y+=s.verticalVelocity*dt;if(s.pos.y<=0){s.pos.y=0;s.verticalVelocity=0;s.onGround=true;}else s.onGround=false;}
    s.moving=Math.hypot(s.pos.x-old.x,s.pos.z-old.z)>.002;s.backward=s.view==='fps'&&s.moving&&inp.f<0&&!inp.r;s.running=s.moving&&runningForward;
    if(s.view==='fps')s.bodyYaw=s.yaw;else if(s.moving){const movementYaw=Math.atan2(-moveX,-moveZ);s.bodyYaw=lerpAngle(Number(s.bodyYaw)||0,movementYaw,Math.min(1,dt*11));}
    s.player?.root.position.copy(s.pos);s.player?.root.rotation.set(0,Number(s.bodyYaw)||0,0);
  }
  function toggleStance(s,next){if(!s?.alive||s.staff?.fly)return;if(next==='prone')s.stance=s.stance==='prone'?'stand':'prone';else s.stance=s.stance==='crouch'?'stand':'crouch';setCharacterStance(s.player,s.stance);updateHud(s);}
  function jumpPlayer(s){if(!s?.alive||s.staff?.fly||!s.onGround||s.stance==='prone')return;if(s.stance==='crouch'){s.stance='stand';setCharacterStance(s.player,'stand');}s.verticalVelocity=6.2;s.onGround=false;}
  function tryMove(s,dx,dz){const nx=s.pos.x+dx,nz=s.pos.z+dz;if(nx<-72||nx>72||nz<-72||nz>72)return;for(const c of s.collision)if(nx>c.minX&&nx<c.maxX&&nz>c.minZ&&nz<c.maxZ)return;s.pos.x=nx;s.pos.z=nz;}
  function updateCharacter(s,dt){if(!s.player)return;setCharacterStance(s.player,s.stance);setMotion(s.player,s.stance==='prone'?'idle':s.running?'run':s.moving?(s.backward?'walk-back':'walk'):'idle');updateCharacterAnimation(s.player,dt);updateHeldWeaponPose(s.player,s);updateHolsteredWeaponPoses(s.player);}
  function updateCamera(s,dt){if(!s.player)return;const fps=s.view==='fps',eye=s.stance==='prone'?.52:s.stance==='crouch'?1.10:1.58;s.player.modelGroup.visible=!fps&&!s.staff.vanish;for(const child of s.player.root.children)if(child.userData?.esklWeapon)child.visible=!fps&&!s.staff.vanish;if(s.fpWeapon)s.fpWeapon.visible=fps;if(fps){s.camera.position.set(s.pos.x,s.pos.y+eye,s.pos.z);s.camera.rotation.order='YXZ';s.camera.rotation.y=s.yaw;s.camera.rotation.x=s.pitch;s.camera.rotation.z=0;const targetFov=UI.mouse.ads?54:72;s.camera.fov+=(targetFov-s.camera.fov)*Math.min(1,dt*12);s.camera.updateProjectionMatrix();updateFpPresentation(s,dt);}else{if(s.camera.fov!==72){s.camera.fov+=(72-s.camera.fov)*Math.min(1,dt*10);s.camera.updateProjectionMatrix();}const forward=forwardFromYaw(s.yaw),right=new THREE.Vector3(Math.cos(s.yaw),0,-Math.sin(s.yaw)),target=s.pos.clone().add(new THREE.Vector3(0,Math.max(.45,eye-.22),0)),want=target.clone().addScaledVector(forward,-4.5).addScaledVector(right,.68).add(new THREE.Vector3(0,2.05+Math.sin(-s.pitch)*1.35,0));s.camera.position.lerp(want,Math.min(1,dt*10));const aim=target.clone().addScaledVector(forward,2.9+Math.cos(s.pitch)*.75);aim.y+=s.pitch*2.15;s.camera.lookAt(aim);}}
  function updateFpPresentation(s,dt){
    const g=s.fpWeapon;if(!g)return;const id=state().equipped[s.currentSlot],w=WEAPON_MAP[id];if(!w)return;
    const base=UI.mouse.ads?g.userData.adsPos:g.userData.basePos;if(!base)return;
    const kick=Math.max(0,Number(s.weaponKick)||0),swing=Math.max(0,Number(s.meleeSwing)||0);
    const target=base.clone();if(kick){target.z+=kick*(w.type==='pistol'?.105:.075);target.y+=kick*(w.type==='pistol'?.035:.018);}if(swing){const phase=Math.sin((1-swing)*Math.PI);if(w.id==='knife'){target.z-=phase*.34;target.y+=phase*.025;}else target.x-=phase*.13;}
    g.position.lerp(target,Math.min(1,dt*18));const br=g.userData.baseRot||new THREE.Euler();
    const phase=Math.sin((1-swing)*Math.PI);g.rotation.x=br.x+kick*(w.type==='pistol'?.22:w.type==='smg'?.14:.11)+(w.id==='knife'?phase*.035:phase*.12);g.rotation.y=br.y-(w.id==='knife'?0:phase*.28);g.rotation.z=br.z+(w.id==='knife'?phase*.025:phase*.22);
  }

  function thirdPersonWeaponSize(w){if(!w)return .22;if(w.id==='knife')return .17;if(w.type==='pistol')return .16;if(w.type==='smg')return .24;if(w.id==='katana')return .48;if(w.id==='baseball')return .54;if(w.type==='sniper'||w.type==='shotgun'||w.type==='rifle')return .48;if(w.type==='raygun')return .44;return .42;}
  function holsteredWeaponSize(w){if(!w)return .22;if(w.id==='knife')return .16;if(w.type==='pistol')return .16;if(w.type==='smg')return .24;if(w.id==='katana')return .50;if(w.id==='baseball')return .56;return .48;}
  const ESKL_TMP_POS=new THREE.Vector3(),ESKL_TMP_POS2=new THREE.Vector3(),ESKL_TMP_Q=new THREE.Quaternion(),ESKL_TMP_Q2=new THREE.Quaternion(),ESKL_TMP_E=new THREE.Euler();
  function anchorWeaponToHand(ch,g,w){const rig=activeRig(ch),hand=rig?.rHand;if(!hand||!g)return false;ch.root.updateMatrixWorld(true);hand.updateWorldMatrix(true,false);hand.getWorldPosition(ESKL_TMP_POS);ch.root.worldToLocal(ESKL_TMP_POS);hand.getWorldQuaternion(ESKL_TMP_Q);ch.root.getWorldQuaternion(ESKL_TMP_Q2).invert();const localQ=ESKL_TMP_Q2.multiply(ESKL_TMP_Q);let forward=.045;if(w?.type==='smg')forward=.075;else if(w?.slot==='long')forward=.105;else if(w?.type==='melee')forward=w.id==='knife'?.035:.09;ESKL_TMP_POS2.set(forward,0,0).applyQuaternion(localQ);g.position.copy(ESKL_TMP_POS).add(ESKL_TMP_POS2);const correction=new THREE.Quaternion().setFromEuler(ESKL_TMP_E.set(0,-Math.PI/2,w?.id==='knife'?-.04:0,'XYZ'));g.quaternion.copy(localQ).multiply(correction);g.scale.set(1,1,1);return true;}
  function anchorHolsteredWeapon(ch,g,w){
    if(!ch||!g||!w)return false;const rig=activeRig(ch),bone=(w.slot==='sidearm'||w.id==='knife')?(rig?.pelvis||rig?.[w.id==='knife'?'lThigh':'rThigh']):(rig?.spine1||rig?.spine||rig?.pelvis);if(!bone)return false;
    ch.root.updateMatrixWorld(true);bone.updateWorldMatrix(true,false);bone.getWorldPosition(ESKL_TMP_POS);ch.root.worldToLocal(ESKL_TMP_POS);
    if(w.id==='knife'){g.position.copy(ESKL_TMP_POS).add(new THREE.Vector3(-.145,-.035,.015));g.rotation.set(-Math.PI/2,0,.05);}
    else if(w.slot==='sidearm'){g.position.copy(ESKL_TMP_POS).add(new THREE.Vector3(.145,-.035,.015));g.rotation.set(-Math.PI/2,0,-.04);}
    else if(w.id==='katana'||w.id==='baseball'){g.position.copy(ESKL_TMP_POS).add(new THREE.Vector3(-.08,.02,.14));g.rotation.set(-1.05,0,-.52);}
    else{g.position.copy(ESKL_TMP_POS).add(new THREE.Vector3(0,-.02,.13));g.rotation.set(-.88,0,.05);}g.scale.set(1,1,1);return true;
  }
  function updateHolsteredWeaponPoses(ch){if(!ch?.holsteredWeapons)return;for(const g of ch.holsteredWeapons){const w=g?.userData?.weapon;if(w)anchorHolsteredWeapon(ch,g,w);}}
  function updateHeldWeaponPose(ch,session=null){const g=ch?.heldWeapon,w=g?.userData?.weapon;if(!g||!w)return;const rig=activeRig(ch),stance=ch.stance||'stand',pitch=clamp(Number(session?.pitch)||0,-.72,.72),kick=Math.max(0,Number(session?.weaponKick)||0),swing=Math.max(0,Number(session?.meleeSwing)||0),phase=Math.sin((1-swing)*Math.PI),pitchLift=Math.tan(pitch)*.12;
    // Beim Ducken/Liegen wird kein aggressives Bone-IK erzwungen. Die Waffe bleibt stattdessen
    // sauber an der echten Hand und kann dadurch nicht mehr vom Koerper wegfliegen.
    if(stance==='stand'){
      if(w.type==='melee'){
        const knife=w.id==='knife',reach=knife?phase*.34:phase*.13,rHand=new THREE.Vector3(.15,1.04+pitchLift*.22,-.22-reach),rElbow=new THREE.Vector3(.27,1.11,-.04-reach*.34);solveLimbFromRest(rig,'rUpper','rFore','rHand',rootLocalToWorld(ch,rElbow.x,rElbow.y,rElbow.z),rootLocalToWorld(ch,rHand.x,rHand.y,rHand.z));
      }else{
        const isLong=w.slot==='long',recoil=kick*(w.type==='pistol'?.05:.03),rHand=new THREE.Vector3(isLong?.14:.11,1.17+pitchLift,-(isLong?.34:.33)+recoil),lHand=new THREE.Vector3(isLong?-.14:-.055,1.16+pitchLift*.9,-(isLong?.53:.39)+recoil),rElbow=new THREE.Vector3(.27,1.14+pitchLift*.38,-.08),lElbow=new THREE.Vector3(-.27,1.13+pitchLift*.34,-.10);solveLimbFromRest(rig,'rUpper','rFore','rHand',rootLocalToWorld(ch,rElbow.x,rElbow.y,rElbow.z),rootLocalToWorld(ch,rHand.x,rHand.y,rHand.z));solveLimbFromRest(rig,'lUpper','lFore','lHand',rootLocalToWorld(ch,lElbow.x,lElbow.y,lElbow.z),rootLocalToWorld(ch,lHand.x,lHand.y,lHand.z));
      }
    }
    anchorWeaponToHand(ch,g,w);
  }
  function clearCharacterWeaponGroups(ch,remoteOnly=false){if(!ch)return;for(const parent of [ch.root,ch.modelGroup])for(const child of [...parent.children]){if(remoteOnly?child.userData?.remoteLoadout:child.userData?.esklWeapon)parent.remove(child);}ch.heldWeapon=null;ch.holsteredWeapons=[];}
  async function rebuildLocalWeapons(s){if(!s?.player)return;const buildId=(s.weaponBuildId||0)+1;s.weaponBuildId=buildId;clearCharacterWeaponGroups(s.player,false);if(s.fpWeapon){s.camera.remove(s.fpWeapon);s.fpWeapon=null;}for(const slot of SLOT_ORDER){const id=state().equipped[slot];if(!id||!weaponState(id).owned)continue;const w=WEAPON_MAP[id],active=slot===s.currentSlot,model=await makeWeaponModel(id,active?thirdPersonWeaponSize(w):holsteredWeaponSize(w));if(UI.session!==s||s.weaponBuildId!==buildId)return;const group=new THREE.Group();group.userData.esklWeapon=true;group.userData.weaponId=id;group.userData.weapon=w;group.add(model);if(active){group.userData.esklHeldWeapon=true;s.player.heldWeapon=group;s.player.root.add(group);updateHeldWeaponPose(s.player,s);}else{group.userData.esklHolstered=true;s.player.root.add(group);s.player.holsteredWeapons.push(group);anchorHolsteredWeapon(s.player,group,w);}}
    await updateFpWeapon(s);}
  function positionHolstered(g,w,active){if(active){g.position.set(.18,1.05,-.20);g.rotation.set(-.04,0,0);return;}if(w.slot==='sidearm'){g.position.set(.31,.82,.01);g.rotation.set(-Math.PI/2,0,.02);}else if(w.id==='knife'){g.position.set(-.30,.81,.01);g.rotation.set(-Math.PI/2,0,.07);}else if(w.id==='katana'||w.id==='baseball'){g.position.set(-.10,1.18,.21);g.rotation.set(-1.05,0,-.58);}else{g.position.set(0,1.06,.22);g.rotation.set(-.88,0,.06);}}

  async function updateFpWeapon(s){if(!s)return;const fpBuild=(s.fpBuildId||0)+1;s.fpBuildId=fpBuild;if(s.fpWeapon){s.camera.remove(s.fpWeapon);s.fpWeapon=null;}const id=state().equipped[s.currentSlot];if(!id||!weaponState(id).owned)return;const w=WEAPON_MAP[id],model=await makeWeaponModel(id,fpModelSize(w));if(UI.session!==s||s.fpBuildId!==fpBuild)return;const pose=fpPose(w),g=new THREE.Group();g.add(model);g.position.copy(pose.pos);g.rotation.copy(pose.rot);g.userData.basePos=pose.pos.clone();g.userData.adsPos=pose.ads.clone();g.userData.baseRot=pose.rot.clone();if(model.userData.esklAnimations?.length){g.userData.mixer=new THREE.AnimationMixer(model);const clip=model.userData.esklAnimations.find(a=>/shoot|fire/i.test(a.name||''))||model.userData.esklAnimations[0];if(clip){g.userData.shootAction=g.userData.mixer.clipAction(clip);g.userData.shootAction.setLoop(THREE.LoopOnce,1);g.userData.shootAction.clampWhenFinished=true;}}s.camera.add(g);s.fpWeapon=g;}
  function setSlot(s,slot){if(!SLOT_ORDER.includes(slot)||!state().equipped[slot])return;s.currentSlot=slot;rebuildLocalWeapons(s);s.reloadUntil=0;updateHud(s);}

  function updateHud(s){const hpPct=clamp(s.hp/s.maxHp*100,0,100),shieldPct=s.maxShield?clamp(s.shield/s.maxShield*100,0,100):0;UI.body?.querySelector('[data-hp-bar]')?.style.setProperty('width',`${hpPct}%`);UI.body?.querySelector('[data-shield-bar]')?.style.setProperty('width',`${shieldPct}%`);const ht=UI.body?.querySelector('[data-hp-text]'),st=UI.body?.querySelector('[data-shield-text]');if(ht)ht.textContent=Math.ceil(s.hp);if(st)st.textContent=Math.ceil(s.shield);const wid=state().equipped[s.currentSlot],w=wid?weaponStats(wid):null;const wn=UI.body?.querySelector('[data-world-weapon]'),du=UI.body?.querySelector('[data-world-dura]'),am=UI.body?.querySelector('[data-world-ammo]');if(wn)wn.textContent=w?.name||'-';if(du)du.textContent=w?`${Math.round(w.durability)}% · L${w.level}`:'-';if(am)am.textContent=w?(w.type==='melee'?'NAHKAMPF':`${s.ammo[w.id]??0}/${w.mag||0}${performance.now()<s.reloadUntil?' · LÄDT…':''}`):'';const wk=UI.body?.querySelector('[data-world-kills]');if(wk)wk.textContent=fmt(state().totalKills);for(const id of ['heal','speed','shield100','shield150','shield200']){const el=UI.body?.querySelector(`[data-count="${id}"]`);if(el)el.textContent=fmt(state().inventory[id]||0);}}

  function updateLobbyPrompt(s){const p=UI.body?.querySelector('[data-world-prompt]');if(!p)return;if(s.mode!=='lobby'){p.textContent=s.view==='fps'?'V: Third Person · C Ducken · Z Liegen · SPACE Springen':'V: Ego-Perspektive · C Ducken · Z Liegen · SPACE Springen';return;}let near=null;for(const id of ['shop','online','bots']){const q=s[`place_${id}`];if(q&&Math.hypot(s.pos.x-q.x,s.pos.z-q.z)<q.radius){near=id;break;}}s.nearPlace=near;p.textContent=near==='shop'?'E · Shop öffnen':near==='online'?'E · Online-Welt betreten':near==='bots'?'E · Bot-Welt mit 10 Bots betreten':'WASD bewegen · Maus frei umsehen · SPACE springen · C ducken · Z liegen · E Teleport/Shop';}
  function interact(s){if(s.mode!=='lobby')return;if(s.nearPlace==='shop')openShop();else if(s.nearPlace==='online')startCombat('online');else if(s.nearPlace==='bots')startCombat('bots');}

  function useConsumable(s,id){const inv=state().inventory;if(!s.alive||Number(inv[id]||0)<=0)return toast('Davon hast du nichts.','bad');if(id==='heal'){if(s.hp>=100)return toast('Leben ist bereits voll.');s.hp=Math.min(100,s.hp+60);}else if(id==='speed'){s.speedBoostUntil=performance.now()+12000;}else if(id.startsWith('shield')){const value=Number(id.replace('shield',''))||100;s.maxShield=value;s.shield=value;}else return;inv[id]--;persist();updateHud(s);toast('Benutzt.','good');}

  function updateShooting(s,now){if(!s.alive||s.mode==='lobby')return;const id=state().equipped[s.currentSlot];if(!id)return;const w=weaponStats(id);if(w.durability<=0){if(UI.mouse.down&&now-s.lastShotAt>600){s.lastShotAt=now;toast(`${w.name} ist kaputt – im Shop reparieren.`,'bad');}return;}if(now<s.reloadUntil)return;if(w.type!=='melee'&&(s.ammo[id]??0)<=0){if(UI.mouse.down)beginReload(s,id);return;}if(!UI.mouse.down)return;if(now-s.lastShotAt<w.rate*1000)return;if((w.type==='pistol'||w.type==='sniper'||w.type==='shotgun')&&s.shotHeld)return;s.shotHeld=true;s.lastShotAt=now;fireWeapon(s,w);}
  function fireWeapon(s,w){const shootAction=s.fpWeapon?.userData?.shootAction;if(shootAction){shootAction.reset();shootAction.play();}if(w.type==='melee')s.meleeSwing=1;else s.weaponKick=1;if(w.type!=='melee'){s.ammo[w.id]=Math.max(0,(s.ammo[w.id]??w.mag)-1);weaponState(w.id).durability=clamp(weaponState(w.id).durability-w.durabilityLoss,0,100);}else weaponState(w.id).durability=clamp(weaponState(w.id).durability-w.durabilityLoss,0,100);persistSoon();if(w.type==='melee')return meleeAttack(s,w);const pellets=w.pellets||1;for(let i=0;i<pellets;i++)shootRay(s,w,i,pellets);muzzleFlash(s,w);}
  function shootRay(s,w,index,pellets){const spread=(100-w.stability)/100*(UI.mouse.ads?.006:.014)*(w.type==='shotgun'?3.8:1),x=(Math.random()-.5)*spread,y=(Math.random()-.5)*spread;s.raycaster||(s.raycaster=new THREE.Raycaster());s.raycaster.setFromCamera(new THREE.Vector2(x,y),s.camera);s.raycaster.far=w.range;const hits=s.raycaster.intersectObjects(s.shootables,true);for(const hit of hits){const meta=findTargetMeta(hit.object);if(hit.object.userData?.blockShot&&!meta)break;if(meta){const head=meta.zone==='head',mult=head?(w.type==='sniper'?2.05:w.type==='pistol'?1.75:1.6):1,damage=Math.max(1,Math.round(w.damage*mult));applyOutgoingHit(s,meta,damage,false,head,w.id);break;}}}
  function findTargetMeta(obj){let n=obj;while(n){if(n.userData?.esklTarget)return n.userData.esklTarget;n=n.parent;}return null;}
  function meleeAttack(s,w){const origin=s.pos.clone().add(new THREE.Vector3(0,1.15,0)),forward=forwardFromYaw(s.yaw);let best=null,dist=Infinity;for(const o of s.shootables){const meta=findTargetMeta(o);if(!meta)continue;const wp=new THREE.Vector3();o.getWorldPosition(wp);const d=origin.distanceTo(wp);if(d>w.range||d>=dist)continue;const dir=wp.clone().sub(origin).normalize();if(dir.dot(forward)<.55)continue;best=meta;dist=d;}if(best)applyOutgoingHit(s,best,50,true,false,w.id);}
  function applyOutgoingHit(s,meta,damage,ignoreShield,headshot,weaponId){if(meta.kind==='bot'){const bot=s.bots.get(meta.id);if(bot)damageBot(s,bot,damage,ignoreShield,headshot,weaponId,true);}else if(meta.kind==='remote')sendOnlineHit(s,meta.id,damage,ignoreShield,headshot,weaponId);}
  function muzzleFlash(s,w){const l=new THREE.PointLight(w.type==='raygun'?0x8b5cff:0xffd37a,w.type==='raygun'?8:3,5,.8);l.position.copy(s.camera.position);s.scene.add(l);setTimeout(()=>s.scene?.remove(l),45);}
  function beginReload(s,id=state().equipped[s.currentSlot]){const w=WEAPON_MAP[id];if(!w?.mag||performance.now()<s.reloadUntil||(s.ammo[id]??0)>=w.mag)return;s.reloadUntil=performance.now()+w.reload*1000;setTimeout(()=>{if(UI.session===s&&performance.now()+25>=s.reloadUntil){s.ammo[id]=w.mag;s.reloadUntil=0;updateHud(s);}},w.reload*1000);}

  async function createBots(s){for(let i=0;i<BOT_COUNT;i++){const gender=i%2?'woman':'man',ch=await makeCharacter(gender,`BOT ${i+1}`);if(UI.session!==s)return;const p=randomSpawn();p.x+=((i*7)%9)-4;p.z+=((i*11)%9)-4;ch.root.position.copy(p);s.scene.add(ch.root);const weapon=['glock','mini-uzi','m4','ak12','scar'][i%5];setCharacterStance(ch,'stand');const bot={id:`bot-${i}`,ch,pos:p,yaw:Math.random()*Math.PI*2,hp:100,shield:i%3===0?100:0,maxShield:i%3===0?100:0,alive:true,weapon,lastDecision:0,lastShot:0,target:null,respawnAt:0};tagTarget(ch,bot.id,'bot');s.bots.set(bot.id,bot);await attachActiveWeapon(ch,weapon);}}
  function tagTarget(ch,id,kind){ch.head.userData.esklTarget={kind,id,zone:'head'};ch.body.userData.esklTarget={kind,id,zone:'body'};if(UI.session){UI.session.shootables.push(ch.head,ch.body);}}
  async function attachActiveWeapon(ch,id){for(const parent of [ch.root,ch.modelGroup])for(const child of [...parent.children])if(child.userData?.activeWeapon)parent.remove(child);const w=WEAPON_MAP[id],m=await makeWeaponModel(id,thirdPersonWeaponSize(w)),g=new THREE.Group();g.userData.activeWeapon=true;g.userData.esklWeapon=true;g.userData.esklHeldWeapon=true;g.userData.weapon=w;g.add(m);ch.root.add(g);ch.heldWeapon=g;updateHeldWeaponPose(ch);}
  async function rebuildRemoteLoadout(ch,loadout,activeSlot,key){ch.root.userData.remoteLoadoutKey=key;clearCharacterWeaponGroups(ch,true);for(const slot of SLOT_ORDER){const id=loadout[slot];if(!id||!WEAPON_MAP[id])continue;const w=WEAPON_MAP[id],active=slot===activeSlot,m=await makeWeaponModel(id,active?thirdPersonWeaponSize(w):holsteredWeaponSize(w));if(ch.root.userData.remoteLoadoutKey!==key)return;const g=new THREE.Group();g.userData.remoteLoadout=true;g.userData.esklWeapon=true;g.userData.weapon=w;g.userData.loadoutKey=key;g.add(m);if(active){g.userData.esklHeldWeapon=true;ch.heldWeapon=g;ch.root.add(g);updateHeldWeaponPose(ch);}else{g.userData.esklHolstered=true;ch.root.add(g);ch.holsteredWeapons||(ch.holsteredWeapons=[]);ch.holsteredWeapons.push(g);anchorHolsteredWeapon(ch,g,w);}}}
  function botHasLineOfSight(s,b,target){const origin=b.pos.clone().add(new THREE.Vector3(0,1.35,0)),tp=(target.player?s.pos:target.pos).clone().add(new THREE.Vector3(0,1.05,0)),dir=tp.clone().sub(origin),dist=dir.length();if(dist<=.01)return true;dir.normalize();const ray=new THREE.Raycaster(origin,dir,.05,dist);const blockers=s.shootables.filter(o=>o?.userData?.blockShot);const hit=ray.intersectObjects(blockers,true)[0];return !hit||hit.distance>=dist-.35;}
  function updateBots(s,dt){const now=performance.now(),aliveBots=[...s.bots.values()].filter(b=>b.alive);for(const b of s.bots.values()){if(!b.alive){if(now>b.respawnAt)respawnBot(s,b);continue;}updateCharacterAnimation(b.ch,dt);if(now>b.lastDecision){b.lastDecision=now+900+Math.random()*900;const candidates=[...aliveBots.filter(x=>x!==b),...(s.alive?[{id:'player',pos:s.pos,hp:s.hp,alive:true,player:true}]:[])];b.target=candidates[Math.floor(Math.random()*candidates.length)]||null;}const target=b.target;if(!target||!target.alive)continue;const tp=target.player?s.pos:target.pos,vec=tp.clone().sub(b.pos),dist=vec.length();b.yaw=Math.atan2(-vec.x,-vec.z);if(dist>10){const step=Math.min(3.2*dt,Math.max(0,dist-8)),bf=forwardFromYaw(b.yaw);const nx=b.pos.x+bf.x*step,nz=b.pos.z+bf.z*step;if(!collides(s,nx,nz)){b.pos.x=nx;b.pos.z=nz;setMotion(b.ch,'run');}else setMotion(b.ch,'idle');}else setMotion(b.ch,'idle');b.ch.root.position.copy(b.pos);b.ch.root.rotation.y=b.yaw;updateHeldWeaponPose(b.ch);updateHolsteredWeaponPoses(b.ch);if(dist<45&&now-b.lastShot>650+Math.random()*900&&botHasLineOfSight(s,b,target)){b.lastShot=now;const dmg=WEAPON_MAP[b.weapon].damage*(.65+Math.random()*.35);if(target.player)applyDamageToPlayer(s,Math.round(dmg),false,b.id,false,b.weapon);else damageBot(s,target,Math.round(dmg),false,false,b.weapon,false);}}}
  function collides(s,x,z){if(x<-71||x>71||z<-71||z>71)return true;return s.collision.some(c=>x>c.minX&&x<c.maxX&&z>c.minZ&&z<c.maxZ);}
  function damageBot(s,b,damage,ignoreShield,headshot,weaponId,fromPlayer){if(!b?.alive)return;if(ignoreShield)b.hp-=damage;else{const take=Math.min(b.shield,damage);b.shield-=take;b.hp-=damage-take;}if(b.hp<=0){b.hp=0;b.alive=false;b.ch.root.visible=false;b.respawnAt=performance.now()+4000;if(fromPlayer)grantKill(s,'bot',headshot,weaponId);}}
  function respawnBot(s,b){b.pos.copy(randomSpawn());b.hp=100;b.shield=b.maxShield;b.alive=true;b.ch.root.visible=true;b.ch.root.position.copy(b.pos);}

  function applyDamageToPlayer(s,damage,ignoreShield,killerId,headshot,weaponId=''){if(!s.alive||s.staff.god)return;if(ignoreShield)s.hp-=damage;else{const block=Math.min(s.shield,damage);s.shield-=block;s.hp-=damage-block;}if(s.hp<=0){s.hp=0;playerDied(s,killerId,headshot,weaponId);}updateHud(s);}
  function playerDied(s,killerId,headshot=false,weaponId=''){if(!s.alive)return;s.alive=false;state().deaths++;persist();if(s.mode==='online'&&killerId&&killerId!==s.user?.uid)sendKillReward(s,killerId,headshot,weaponId);showDeath(s);}
  function grantKill(s,kind,headshot,weaponId){const st=state();st.totalKills++;st.killTokens++;if(headshot)st.headshots++;if(kind==='online')st.stats.onlineKills++;else st.stats.botKills++;s.streak=(s.streak||0)+1;st.stats.bestStreak=Math.max(st.stats.bestStreak||0,s.streak);persist();refreshHeader();window.JKGamesAwardTopGameXp?.('egoshoot',8,'Egoshoot.KL Kill',{silent:true});toast(`+1 Kill${headshot?' · HEADSHOT':''} · +1 Kill-Punkt`,'good');}

  function showDeath(s){s.pointerLockBlocked=true;UI.mouse.down=false;UI.mouse.ads=false;s.shotHeld=false;try{if(document.pointerLockElement)document.exitPointerLock?.();}catch{}const host=document.createElement('div');host.className='eskl-death';host.innerHTML=`<div><small>DU BIST AUSGESCHIEDEN</small><h2>Respawn oder Lobby?</h2><p>Automatisch zur Lobby in <b data-death-count>10</b> Sekunden.</p><div><button data-death-respawn>Respawn</button><button data-death-lobby>Lobby</button></div></div>`;UI.body.append(host);let left=10;const timer=setInterval(()=>{left--;const el=host.querySelector('[data-death-count]');if(el)el.textContent=left;if(left<=0){clearInterval(timer);host.remove();startLobby();}},1000);host.querySelector('[data-death-respawn]').onclick=()=>{clearInterval(timer);host.remove();respawnPlayer(s);};host.querySelector('[data-death-lobby]').onclick=()=>{clearInterval(timer);host.remove();startLobby();};}
  function respawnPlayer(s){s.pos.copy(randomSpawn());s.hp=100;s.shield=0;s.maxShield=0;s.alive=true;s.streak=0;s.stance='stand';s.bodyYaw=s.yaw;s.verticalVelocity=0;s.onGround=true;s.pointerLockBlocked=false;s.player.root.visible=true;setCharacterStance(s.player,'stand');for(const w of WEAPONS)s.ammo[w.id]=w.mag||0;updateHud(s);}

  async function startOnline(s){const core=window.LifeBuilderFirebaseCore,fb=await core?.load?.(),user=await core?.waitForAuth?.(6500);if(!fb||!user||UI.session!==s)throw new Error('Firebase-Anmeldung fehlt.');s.fb=fb;s.user=user;s.displayName=String(user.displayName||user.email?.split('@')[0]||'Spieler').slice(0,48);
    const q=fb.query(fb.collection(fb.db,'egoshootKlOnline'),fb.orderBy('updatedAtMs','desc'),fb.limit(MAX_REMOTE));s.remoteUnsub=fb.onSnapshot(q,snap=>{if(UI.session!==s)return;const seen=new Set();snap.forEach(doc=>{if(doc.id===user.uid)return;const d=doc.data()||{};if(Date.now()-Number(d.updatedAtMs||0)>15000||d.vanish===true)return;seen.add(doc.id);upsertRemote(s,doc.id,d);});for(const id of [...s.remoteVisuals.keys()])if(!seen.has(id))removeRemote(s,id);},err=>{console.warn('Egoshoot.KL Online Listener',err);if(core?.isFatalFirestoreAssertion?.(err))core.scheduleHardFirestoreRecovery?.(err);});
    const hits=fb.collection(fb.db,'egoshootKlHits',user.uid,'events');s.hitUnsub=fb.onSnapshot(hits,snap=>{const remove=[];for(const ch of snap.docChanges()){if(ch.type!=='added'||s.seenHits.has(ch.doc.id))continue;s.seenHits.add(ch.doc.id);const d=ch.doc.data()||{};if(Date.now()-Number(d.createdAtMs||0)<30000)applyDamageToPlayer(s,Math.max(0,Number(d.damage)||0),d.ignoreShield===true,String(d.shooterUid||''),d.headshot===true,String(d.weaponId||''));remove.push(ch.doc.ref);}deleteEventRefs(fb,remove);},err=>console.warn('Egoshoot.KL Hit Listener',err));
    const rewards=fb.collection(fb.db,'egoshootKlRewards',user.uid,'events');s.rewardUnsub=fb.onSnapshot(rewards,snap=>{const remove=[];for(const ch of snap.docChanges()){if(ch.type!=='added'||s.seenRewards.has(ch.doc.id))continue;s.seenRewards.add(ch.doc.id);const d=ch.doc.data()||{};if(Date.now()-Number(d.createdAtMs||0)<60000)grantKill(s,'online',d.headshot===true,d.weaponId||'');remove.push(ch.doc.ref);}deleteEventRefs(fb,remove);},err=>console.warn('Egoshoot.KL Reward Listener',err));}
  function deleteEventRefs(fb,refs){if(!refs?.length)return;try{if(typeof fb.writeBatch==='function'){const batch=fb.writeBatch(fb.db);for(const ref of refs)batch.delete(ref);batch.commit().catch(()=>{});return;}}catch{}for(const ref of refs)fb.deleteDoc(ref).catch(()=>{});}
  async function upsertRemote(s,uid,d){let r=s.remoteVisuals.get(uid);if(!r){const ch=await makeCharacter(d.gender==='woman'?'woman':'man',d.displayName||'Spieler');if(UI.session!==s)return;s.scene.add(ch.root);r={ch,target:new THREE.Vector3(),yaw:0,data:{},loadoutKey:''};s.remoteVisuals.set(uid,r);tagTarget(ch,uid,'remote');}r.target.set(Number(d.x||0),Number(d.y||0),Number(d.z||0));r.yaw=Number(d.yaw||0);r.data=d;r.ch.root.visible=d.alive!==false;const loadoutKey=[d.meleeId||'knife',d.sidearmId||'glock',d.longId||'',d.activeSlot||'sidearm'].join('|');if(r.loadoutKey!==loadoutKey){r.loadoutKey=loadoutKey;rebuildRemoteLoadout(r.ch,{melee:d.meleeId||'knife',sidearm:d.sidearmId||'glock',long:d.longId||''},d.activeSlot||'sidearm',loadoutKey).catch(()=>{});}}
  function removeRemote(s,uid){const r=s.remoteVisuals.get(uid);if(r){s.scene.remove(r.ch.root);s.remoteVisuals.delete(uid);s.shootables=s.shootables.filter(o=>findTargetMeta(o)?.id!==uid);}}
  function updateRemoteLerp(s,dt){for(const r of s.remoteVisuals.values()){r.ch.root.position.lerp(r.target,1-Math.pow(.0005,dt));r.ch.root.rotation.y=r.yaw;const moving=Number(r.data.speed||0)>.2;setMotion(r.ch,moving?(Number(r.data.speed)>RUN_SPEED*.8?'run':'walk'):'idle');updateCharacterAnimation(r.ch,dt);updateHeldWeaponPose(r.ch);updateHolsteredWeaponPoses(r.ch);}}
  function syncOnlineWrite(s,now){if(!s.fb||!s.user||s.remoteWriteBusy)return;const eq=state().equipped,wid=eq[s.currentSlot]||'glock',stable={uid:s.user.uid,displayName:s.displayName||'Spieler',gender:s.gender,x:Number(s.pos.x.toFixed(2)),y:Number(s.pos.y.toFixed(2)),z:Number(s.pos.z.toFixed(2)),yaw:Number((Number(s.bodyYaw)||0).toFixed(4)),speed:Number((s.moving?(s.running?RUN_SPEED:WALK_SPEED)*s.staff.speed:0).toFixed(2)),weaponId:wid,meleeId:eq.melee||'knife',sidearmId:eq.sidearm||'glock',longId:eq.long||'',activeSlot:s.currentSlot,hp:Math.max(0,Math.round(s.hp)),shield:Math.max(0,Math.round(s.shield)),alive:!!s.alive,vanish:!!s.staff.vanish,flight:!!s.staff.fly};const key=JSON.stringify(stable),changed=key!==s.lastRemoteKey,interval=changed?500:3500;if(now-s.lastRemoteWrite<interval)return;s.lastRemoteWrite=now;s.remoteWriteBusy=true;s.fb.setDoc(s.fb.doc(s.fb.db,'egoshootKlOnline',s.user.uid),{...stable,updatedAtMs:Date.now()},{merge:false}).then(()=>s.lastRemoteKey=key).catch(err=>{if(window.LifeBuilderFirebaseCore?.isFatalFirestoreAssertion?.(err))window.LifeBuilderFirebaseCore.scheduleHardFirestoreRecovery?.(err);}).finally(()=>s.remoteWriteBusy=false);}
  function sendOnlineHit(s,targetUid,damage,ignoreShield,headshot,weaponId){if(!s.fb||!s.user||targetUid===s.user.uid)return;const id=`${s.user.uid.slice(0,8)}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const ref=s.fb.doc(s.fb.db,'egoshootKlHits',targetUid,'events',id),data={shooterUid:s.user.uid,targetUid,damage:Math.min(9999,Math.max(1,Math.round(damage))),ignoreShield:!!ignoreShield,headshot:!!headshot,weaponId:String(weaponId||'').slice(0,32),createdAtMs:Date.now()};s.pendingHitWrites.push({ref,data});if(s.pendingHitWrites.length>=18)flushOnlineHitQueue(s);else if(!s.hitFlushTimer)s.hitFlushTimer=setTimeout(()=>{s.hitFlushTimer=0;flushOnlineHitQueue(s);},90);}
  function flushOnlineHitQueue(s){if(!s?.fb||!s.pendingHitWrites?.length)return;clearTimeout(s.hitFlushTimer);s.hitFlushTimer=0;const rows=s.pendingHitWrites.splice(0,18);try{if(typeof s.fb.writeBatch==='function'){const batch=s.fb.writeBatch(s.fb.db);for(const row of rows)batch.set(row.ref,row.data,{merge:false});batch.commit().catch(()=>{});return;}}catch{}Promise.allSettled(rows.map(row=>s.fb.setDoc(row.ref,row.data,{merge:false}))).catch(()=>{});}
  function sendKillReward(s,killerUid,headshot=false,weaponId=''){if(!s.fb||!s.user||!killerUid)return;const id=`${s.user.uid.slice(0,8)}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;const ref=s.fb.doc(s.fb.db,'egoshootKlRewards',killerUid,'events',id);s.fb.setDoc(ref,{killerUid,victimUid:s.user.uid,headshot:!!headshot,weaponId:String(weaponId||'').slice(0,32),createdAtMs:Date.now()},{merge:false}).catch(()=>{});}

  function openStaffMenu(s){if(!isStaff())return;showModal(`<div class="eskl-modal-head"><div><small>OWNER / ADMIN</small><h2>Mod-Menü</h2></div><button data-modal-close>×</button></div><div class="eskl-mod-grid"><button data-mod="fly">Fliegen: <b>${s.staff.fly?'AN':'AUS'}</b></button><button data-mod="vanish">Vanish: <b>${s.staff.vanish?'AN':'AUS'}</b></button><button data-mod="god">Godmode: <b>${s.staff.god?'AN':'AUS'}</b></button><button data-mod="speed">Speed: <b>${s.staff.speed}×</b></button><button data-mod="weapons">Alle Waffen geben</button><button data-mod="raygun">Raygun ausrüsten</button><button data-mod="heal">HP + Ultra Shield</button></div>`);UI.modal.querySelectorAll('[data-mod]').forEach(b=>b.onclick=()=>{const k=b.dataset.mod;if(k==='fly')s.staff.fly=!s.staff.fly;else if(k==='vanish'){s.staff.vanish=!s.staff.vanish;s.player.modelGroup.visible=!s.staff.vanish;for(const child of s.player.root.children)if(child.userData?.esklWeapon)child.visible=!s.staff.vanish;}else if(k==='god')s.staff.god=!s.staff.god;else if(k==='speed')s.staff.speed=s.staff.speed>=4?1:s.staff.speed*2;else if(k==='weapons'){for(const w of WEAPONS)if(!w.staffOnly||isStaff())state().weaponState[w.id]={owned:true,level:Math.max(1,weaponState(w.id).level),durability:100};persist();}else if(k==='raygun'){state().weaponState.raygun={owned:true,level:10,durability:100};state().equipped.long='raygun';s.currentSlot='long';persist();rebuildLocalWeapons(s);}else if(k==='heal'){s.hp=100;s.maxShield=200;s.shield=200;}closeModal();openStaffMenu(s);});}

  function onKeyDown(e){if(!UI.overlay)return;UI.keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();const s=UI.session;if(!s)return;if(e.code==='Escape'){if(document.pointerLockElement)document.exitPointerLock?.();else startLobby();}if(e.code==='KeyE')interact(s);if(e.code==='KeyV'){s.view=s.view==='fps'?'third':'fps';state().settings.view=s.view;persist();updateFpWeapon(s);}if(e.code==='Space'&&!e.repeat)jumpPlayer(s);if(e.code==='KeyC'&&!e.repeat)toggleStance(s,'crouch');if(e.code==='KeyZ'&&!e.repeat)toggleStance(s,'prone');if(e.code==='Digit1')setSlot(s,'melee');if(e.code==='Digit2')setSlot(s,'sidearm');if(e.code==='Digit3')setSlot(s,'long');if(e.code==='KeyR')beginReload(s);if(e.code==='KeyQ'&&isStaff())openStaffMenu(s);}
  function onKeyUp(e){UI.keys[e.code]=false;}
  function onMouseMove(e){const s=UI.session;if(!s)return;if(document.pointerLockElement===s.renderer.domElement){s.yaw-=e.movementX*.0023;s.pitch=clamp(s.pitch-e.movementY*.0019,-1.15,1.1);}}
  function onMouseDown(e){const s=UI.session;if(!s||s.pointerLockBlocked||e.target?.closest?.('button'))return;if(e.button===0){UI.mouse.down=true;if(!document.pointerLockElement&&!isTouch())s.renderer.domElement.requestPointerLock?.();}if(e.button===2)UI.mouse.ads=true;}
  function onMouseUp(e){if(e.button===0){UI.mouse.down=false;if(UI.session)UI.session.shotHeld=false;}if(e.button===2)UI.mouse.ads=false;}
  function onContextMenu(e){if(UI.overlay)e.preventDefault();}

  function stopWorld(){const s=UI.session;if(!s)return;cancelAnimationFrame(s.raf);try{s.timer?.dispose?.();}catch{};flushOnlineHitQueue(s);try{s.remoteUnsub?.();s.hitUnsub?.();s.rewardUnsub?.();}catch{};clearTimeout(s.remoteRetry);clearTimeout(s.hitFlushTimer);if(s.fb&&s.user)s.fb.deleteDoc(s.fb.doc(s.fb.db,'egoshootKlOnline',s.user.uid)).catch(()=>{});if(s.resize)window.removeEventListener('resize',s.resize);try{s.renderer?.setAnimationLoop?.(null);s.renderer?.dispose?.();s.renderer?.forceContextLoss?.();s.renderer?.domElement?.remove?.();}catch{};UI.session=null;UI.mouse.down=false;UI.mouse.ads=false;UI.touch={forward:false,back:false,left:false,right:false,fire:false,run:false,ads:false};}

  function grantJkCoinPurchase(kind,amount=1){if(kind!=='kills')return false;const n=Math.max(1,Math.floor(Number(amount)||1)),s=state();s.totalKills+=n;s.killTokens+=n;persist();refreshHeader();toast(`JK/Coin: +${n} Kills und Kill-Punkte`,'good');return true;}

  window.EgoShootKL=Object.freeze({version:VERSION,open,close,grantJkCoinPurchase,weapons:WEAPONS});
})();
